language: r
cache: packages
env:
  global:
    secure: dXYAqDZPWjuT6oVvMMaxb3Xw1fVYGj5W8sii9/GCUF9VhRTPvWqaN7FKtH8c0qlh5cM91pSc08m3NwfY6jwLM0db3euzvSPjp3YAs2uUIYWuXKKLXjOWbcACo3vo8VkXfrRg9B4sf+T0lSIynOFlJ8eLSyxdEeMsl8vP2iAp2NZg6sSWQUN30ifDiwKEa6albUHBgBJlzky4mOwYtdRh7KSAzXV0W9np4Cb54VVqW/VFhnoQr+3BaHn0bNL8Jy6A2IITKKwrrlWdeY7d5aV4zv0rgIye84o2vuB5D5DBpDX9ikk36DLrn0s2cRr3lunysNJlA6wHLBOigIIiFvuuNtPDY6Dzrvi7CGDzdjJjWruHa4vUEOTVj9RzYMtZ8BPx5Ci7EcLq0So4IbSaVWsXnp3YzM6WszLZ+OKSmfT203GQvDHDXFa+gly+KNkWeh8Nmh1wrZd7MzcVIgPv/vLRJuPhiBKtManSaIHg0ZN2j5dHT69NN7eUi881T6BDZpnHCD0V1Imsm9L0ArgEIjw+wE7JWezcj8maxuVJznG/aW1CtycX6PioUQGpMIakVlg7HZKnquQuR/TGywJSSA0smgaCxBO5gUAsC7tOQVzNHQMllZSvvDmthsLiLw+8kF1MAzBQiZtwGhxyKcMJveU5uZX9VN9pgdqDbYYv4a7u0iE=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
stages:
- name: test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    script: ./_build.sh
  - stage: deploy
    script: ./_deploy.sh
