# 攻读博士学位的程序

在攻读博士学位的时候，你将会遇到很多的程序、关键时刻和最后期限等等。如果你没有以理智的方式处理好，那么这些事情可能会白白耗费你很多时间而且还会让你无谓地难过。本章将讨论你该如何处理这些事情以及这样做的原因。

就程序而言，你需要记住有关正义战争论的一些观点。如果你一下子想不起来，那么请记住关键的一条：完全没有希望获胜的战争就没有进行的必要。在你攻读博士学位期间，你能说服学院改变程序的可能性可以说是零，因此你需要做的是与该体制达成一致。第一种方式就是把学院的程序看成是为了今后学术生涯所需的重要技能而进行的有用实践。无论你选择从哪个角度来看待这些程序，制定这些程序的目的则是要以一系列标准来衡量你，而绝不会考虑你对于这些标准能否正好体现你的才能的意见。你需要做的是先了解这些标准然后使你自己真正、完全符合这些标准。

攻读博士学位需经过好几个阶段，每一个阶段都有其程序和不得不跨越的障碍。以下按照倒叙的方式将这些阶段列出来，或许这样做会让你觉得很恼火，因为你可能更倾向于按部就班顺次关注每一阶段，而不是先关注最终结果，但是如果你从最后一步着眼的话整个程序会更有意义。

## 取得博士学位的程序

### 提交论文和答辩

博士学位的取得是一个漫长的过程，但最终结果却只是由一篇论文和一次讨论而定。论文即你写的博士论文，而讨论即答辩。参加答辩时你会被一组睿智、知识渊博、难对付的评审人问及一些尖锐的问题。学术体制只通过测评你的论文和答辩中的表现来决定你是否能获得博士学位，你其他的努力都与之毫不相关。人们对此通常持
三种主要观点：

* 你仍需重视各个阶段并恰当地处理。因为如果不这样做的话，你就不能到达提交论文和答辩这个阶段；
* 论文和答辩是整个过程中最为重要的。前面的阶段只要通过就可以了；
* 整套程序是为了你获得博士学位之后所从事的工作做的准备工作。

第一种观点最为普遍，持这一观点的主要是学校的管理者和担心拿不到学位的学生（可能占博士生的大多数）。因为这样的想法能降低由于目标不高而轻易失败的风险，就像跨栏一样。如果不瞄准更高的目标，那么很容易刚开始就被绊倒。持第二种观点的人较少。其目的性较强。容易使人忽略中间程序。持第三种观点的人最少，但事实上这一观点对于博士学位本身和以后的学术生涯都是最有好处的。

这是最后的一个阶段。或许此时你对于这些内容还不是很感兴趣，但是它对你来说的确很有益处。而且这还涉及公平明智地合理分配问题。但是尽管如此，这并非只是一个单独的阶段。在许多学院。你必须先通过其他阶段才能进行答辩。

### 候选人申报表（The candidate declaration form）

提交论文之前你需要通过一份表格正式通知你所在学院你已经做好准备，这个表被称为“候选人申报表”。它主要有两个目的：

* 它要求你的导师保证你研究作品的质量，因为在为申报表签字的时候他们必须声明已经阅读过完整的稿件且肯定该作品有被考核的价值；
* 它促使组织开始为你选定评审人，这个过程可能需要花些时间，因为要递交简历，填好完整表格以及获得相关委员会的批准。

### 年度报告（The annual report）

攻读博土的每个学年，大多数学院都会要求你的研究生导师每年交一个报告概括你当年所取得的进步，评估你继续完成学业的潜能并且提出你能否继续下一学年学习的建议。有个很明智的策略，即找出你上一年度的报告，在填写当年报告的时候清楚地写明你所取得的进步一委员会的相关人员很有可能会对照去年的报告来审查今年，有点像是在玩“找差别”的游戏。

### 升级（Transfer）

在进行论文和答辩之前，你要经历一个被称为“升级”的过程，它的全称是“注册升级成为博士生”，有时也被叫做“通过试用期”。这个阶段不论对学术还是行政来说都很重要。

博士生可能认为学院不管他们是否成功取得博士学位，而事实上学院的的确确关心博士生的通过率，因为博士生的通过率太低会给学校带来负面的影响并且会影响学院获得赞助的多少。一种能减少学生在论文和答辩阶段的失败率并且简单有效的方法就是在他们到达这一痛苦棘手的阶段之前使之改变路线——如果他们尚未到达这一阶段的话自然也就不存在失败了。这个阶段被称为升级阶段。这个转折点介于第一学年末和博士学业的中途，到这个时候你已经为学术体制做了很多工作并且基于这些工作学术体制已经对你的能力有了客观公正的了解。（如果你没有足够努力，或者体制尚未对你的能力有一个公正的了解，那么这就意味若你比较笨拙，鉴于你比较笨拙，达不到完成任务的要求，因此你就不得不改变路线了。）在这个转折点，校方会通过正式的决议表明你应该着手博士论文的提交还是应该以另外一条途径获得其他的证书（注意这里并没有出现 “失败”的字眼）。升级是过渡到提交博士论文阶段的必要步骤。

升级是一个很重要的阶段。一般情况下涉及对你的表现做出一些真实的学术评定。这通常需要你创造两件东西。其一是一份文件，该文件能体现： (1)你做了很多细致的工作； (2)你了解了包括描述和介绍作品在内的相关学术技能。其二是临场的表现，在答辩会或是学院的研讨会上，你能够向大家介绍你的研究成果，演示你准备的文件上的很多东西，这里涉及口头演说的技巧。非常巧合的是。这两者对于论文写作和论文答辩都可被视为是十分有用的训练。这些文件准备工作和口头陈述是为了展示你的能力——不是要求你尽善尽美，也不是要把你的研究计划具体化。

在评定升级之前，一些学生认定读博士并不适合自己。光荣的退出，或是接到可以选择攻读研究硕士 (MPhil）学位的通知，对于学生导师以及学术体制来说都是一种成功。对于所有的人来说。这样的选择比数年的焦虑和失败的经历要令人开心得多。

### 小升级（The lesser transfer）

一些学院在升级之前的有一个预备阶段，我们称之为小升级。它是另一个“控制质量”的阶段，通常在博士课程学习的第6个月到第12个月之间。如果你所在的学院存在这个阶段，那么你应该正确填写表格，写恰当的文章对之表示支持并声明你在研究中将要做什么及如何去做。好的策略包括：完整而正确地填写表格，简洁地介绍你的研究，工整地书写，列出丰富且有价值的论文参考文献和条理清晰有可行性的工作计划。而不好的策略则包括：老是问该阶段的价值体现在哪里这类问题。

### 签约（Signing on）

签约表明你被学院录取并开始攻读博士学位。注意这个表述：你是以未来博士的名义签约。整个过程的表述表明你必须主动地从一个阶段进行到下一个阶段，而不是想当然地断定一旦你开始攻读博士学位，只要没有干愚蠢的事情，就会自动到达考评的最后阶段完成学业，拿到学位。

因为学院担心不能取得学位的学生比例，所以采取这些程序来筛选申请攻读博士学位的学生。这些筛选程序都利于查明申请者中有可能有“祸害”学院的类型，也给导师和申请者一个见面的机会让他们对彼此有个第一印象，看会不会讨厌对方。这是一个很重要的问题，因为导师和学生之间的关系可能会像很多婚姻一样长久，并且同样亲密无间。而筛选程序如何利于识别其他一些有问题的学生或是预测申请人的成功几率则是另外一回事。

## 一些有用的习惯

### 填写表格

一些有用的习惯，排列顺序不分先后：

* 开始填表之前将每一份表格从头至尾通读一遍；
* 如果这份表格很重要而你只有一份的话，复印一份并先在这份复制的表格上填写，然后再抄写到原表上；
* 如果你不确定表格中某一栏该如何填写，那么请参考注释绝大多数的表格都会附有注释，但是很多人却不愿意花工夫去看一下；
* 如果你觉得自己很怕填表，那么向他人求援；如果你的恐惧很严重，那么试着考虑请能治疗恐惧症的人来帮助你这样做通常是快速而且令人愉快欣喜的。
* 填完表后将每一份填好的表格都复印，把这些表整齐的归档放好它们会有助于提醒你如何填表，也是你上次申请的记录。

## 博士的标准

博士生常常担心他们的研究是否足以获得博士学位。记住大多数大学的博士学位评估的核心标准（原创性和对知识的重要贡献）是十分有用的。很巧的是，绝大多数的期刊和会议的成功稿件常常能够达得“原创性和对知识的重要贡献”的标准。因此，你可以在提交论文之前将你的文章在指定的期刊或讨论会文集上发表，以此来证明你的“重要性”、“独创性”和“对知识的贡献”。本书后边还有很多篇幅会谈及这个话题。你并不是非要有重大的发现才能获得博土学位——你只需要表现你能够很好地进行独立研究。
