# 学术体制

这一部分描述了学术体制的一些关键特征，其中之一是学术追求等级头衔、角色、岗位等，另一个是学术体制之中的潜在问题的形式。

## 头衔和岗位

学者的头衔、等级和角色的传统可以追溯到拜占庭帝国（Byrnn-tine Empire）甚至更早。以下的内容可以被当做一系列概括性的原则，而不是绝对真理。让我们先从最低的职位开始（也就是一个在研究团体看来仅仅比管理员和接受课程教育的学生略高一点的职位），然后再逐渐上升到最高职位。需要记住的很直要的一点是，尽管这些头衔为全世界所知所用，但同样的头衔在不同的大学经常有十分不同的用法。

### 研究助理 (Research assistant)

研究助理是被聘请来协助学术研究人员开展研究工作的人员。这个研究工作通常是为了某个研究课题而开展的，而这个研究课题之所以能够进行，是因为之前这个研究人员争取到该课题的科研经费。这意味着该研究课题有可能是提前就计划好了的，而且很可能是相当详细的计划。拿到研究经费的人很可能持有这样的观点：这项工程带来的任何荣耀（包括论文的最初原创作者）都应该归功于那个计划好这个项目并争取到研究经费，从而让这个项目得以实施的人（也就是他们自己八而研究助理则可能持不同的观点，争取研究经费的项目申请书中包含着大量似是而非的主张，这些东西如果没有进一步细节的工作，是无法转化为有意义的研究的。这些细节的工作都是由研究助理来完成的。因此在这项工程带来的任何荣耀（包括论文的最初原创作者）中都该有他们应得的一份。在这样的情况中，如果是刚刚修完一个学位的研究助理，在这场争辩中是不可能有发言资格的。博士后研究助理的情况可能会有些不同，但通常也不是完全不同的。

### 博士后研究助理（Postdoctoral research assistant)

博士后研究助理有自己的博士学位，他们在这个职位上会从一个没经验的新手慢慢成长为一名业务熟练的老手（对这个研究领域的了解至少和拿到研究经费的人相当）。

### 讲师（Lecturer）

取得讲师职位通常是职业生涯中坚实的第一步。研究助理的生活常常是从一个短期合同到另一个短期合同。而讲师职位的聘任时间相对较长，而且通常有一定的稳定性允许你完成一些事情。当然。在成为正式的职员前还有许多重要的事情是你不能做的，比如向提供研究经费的机构申请课题的科研基金。因此成为讲师是职业生涯中一个重大的转变，这表明你可以作为正式职员申请科研基金了。

### 高级讲师（Senior lecturer）

这是比讲师高一级的职位，也是许多（甚至大多数）人学术生涯终结的地方。这已经是一个受人尊敬的级别了。但是如果你想要的是事业，而不仅仅是工作的话，你还是很有必要考虑从这里继续往上爬，成为主要讲师、普通教授或者资深教授。

### 主要讲师（Principal lecturer）

这个角色通常（但并非总是）被认为是一个行政角色而并非一个研究角色。从事这个职位的人通常是（但并非总是）那些由于疲倦、工作过度、未得到赏识而“早生华发”的人。可以说如果没有这些主要讲师，几乎没有哪个部门可以支撑多久。

### 普通教授（Reader）[^rdr_prf]

[^rdr_prf]: 参见：《什么是世界一流大学》，丁学良著，北京大学出版社，2004年12月版，第52-56页。

在英国的研究序列中，普通教授的职位通常是向资深教授职位迈进的一个踏脚石。一般情况下，普通教授从这个位置往上爬是很快的，如果他们继续按照自已取得普通教授资格的方式工作的话——在核心学术期刊上发表论文、争取研究经费，并表示出还可能争取到更多经费的迹象。但也有不少人直接绕过这一阶段，因为不少大学赞成把普通教授看作一个试用阶段，而其他一些大学根本不愿意在这个上面多费周折。也有一些大学泛泛地把普通教授职位等同于资深研究员。

### 资深研究员 (Proper research fellow)

通常是在一些非常显赫的历史悠久的大学。资深研究员是一个全职的、终身的研究职位。也是一个令人觊觎、享有相当高声望的职位。尽管其食宿待遇并不一定很好。

### 资深教授 ( Professor）[^rdr_prf]

资深教授也有许多不同的类型。要理解这一点。我们有必要提到一个头衔、一个职位和一个人三者之间的区别。有些人之所以是资深教授，是因为他们所处的职位给他们提供了一个较高的席位，比如说系主任一职就很有可能伴随着资深教授职位。还有些人之所以是资深教授，是因为他们成功地申请到了一个特殊的席位，一个有自己独立身份的席位，比如迪斯尼考古学席位 (Disney Chair of Archaeology)。其他的一些人之所以成为资深教授，是因为他们是多才多艺全面发展的人（也就是说，他们表现出来的学术潜质已经足以让他们自己给自己一个私人的“教授”头衔）。还有一些人是被其他大学授予荣誉教授的称号，这很有可能是这样的情况：某个人在这个大学是一个主要讲师，但他同时也兼任另外一个大学的荣誉教授。也有一些人是在自己所在的大学被授予资深教授的称谓，但却只是作为普通教授的身份被聘任。还有的是退休的荣誉教授，因为他们有过不少值得称赞的业绩，因而不能被忽略。

如何成为一个资深教授，这是个复杂的问题。到我们的大部分读者真正达到这个崇高的职位的时候，那些基本程序肯定已经发生了巨大的变化。但这仍然是一个非常有趣而不容忽略的话题。从形式上来说，如今想要成为资深教授的人通常必须向一个评判小组提交申请表，还要遵循若干规章制度，包括应该提出一些证据来证明。哪些人可以出现在评判小组中，哪些不可以等等。最核心的问题是这个申请者应该有一系列完整连贯的著作，而且至少在全国范围内享有一定的重要影响力。此外诸如发表文章的频率、收入水平、指导的博士生完成学位的情况、学术角色等等一系列间题都是评判标准。在这个过程中，形式上的学术资格证明是没有人会去注意的。事实上，一些年长的教授根本就没有博士学位。

但是，事情远远没有上述的这么简单。如果有人想要以投机圆滑的手段爬到这个高度，他必须相当擅长权力政治，或者有大笔可供投人的资产，或者二者兼具。一个有手段的申请者通常会明确地表示出他们对于这个大学来说是一笔相当数橇的资产。没有哪个大学愿意冒风险拒绝一个意味着大笔资产的人，或者随之而来的潜在的风险万一这个人在被拒绝后。一怒之下改去了其他地方却在其他地方得到了重视。在这个阶段，不少谨慎明智的决定很有可能是在双方当事人协商下作出的。

## 了解你的“敌人”

你的敌人不仅仅是指“狼群”（比如你做演讲时的遇到的不友好的观众）。你的敌人也并不都是指人。有的物也是你的“敌人”；有的“敌人”甚至是你自己的习惯。

### 人

滥竿充数者
:   棒球帽对于指导教师识别滥竿充数者是很有用的，因为通常情况下，这能够让他们有理由相信这个学生的博士论文应该由别人来指导（最好是由一个令自己讨厌的同事来指导）。一般情况下，滥竿充数者除了戴棒球帽之外，还会伴有闲散等坏习惯，这类人认为研究就是浪费时间，因此倾向于去因特网上搜索，而不去做适当的文献调查；更加令人吃惊的是，他们非常喜欢设计鳖脚的调查，其中往往夹杂一些惨不忍睹的问卷，或者一些完全没有现场记录的所谓采访稿件。这种论文通常以一些众人皆知的简单的常识开始，不是关于因特网的普及就是关于他们的研究领域的任何一个热门话题，然后就极尽修剪缩短之能事，随后“写”出来的论文充斥着拼写错误和漏洞百出的语法，另外还附加了彩色饼状图标，目的是为了给评审人留下深刻的印象，但是这样做会适得其反。

    如果你现在正在读这本书，那么你就很可能不属于这类人，不可能再犯他们犯的错误。然而，你同样需要了解这些内容，因为这些内容也不是一无是处，其副产品便是为优秀研究者们提供了这些有发展前途的不错的话题。

    在这里，典型的例子就是任何关于因特网的研究题目。由于这是“戴棒球帽的人”的最爱，任何一位认真严谨的研究者在开始这方面研究工作时，需要从文章第一句就非常清楚地声明这篇论文不是什么滥竿充数的“戴着棒球帽的孩子”所作。下面我们举出些例子供大家参考：

    ```{example, amt}
    一个成功的网页设计对于网络企业的成功与否至关重要。
    ```

    ```{example, prf}
    虽然很少公之于世，但是软件设计的中心或内核就是两种需求达到的一种平衡，一方面是对标准与规矩的渴望与需求，另一方面是对避免发生抄袭剽窃与侵犯他人版权的渴望与需求。
    ```
    <br/>
    例\@ref(exm:amt)可能出自一位网页设计的权威之手，也可能出自一个没有任何专业知识，只是懂得皮毛的人之手。

    对于例\@ref(exm:prf)而言，不是任何人都能够写出来的，这个人必须对论题有细致的了解，具备高深的专业知识，同时对此题目具有独创的想法。

    事实上例\@ref(exm:amt)和例\@ref(exm:prf)出自同一人之手。例\@ref(exm:amt)出现在第一稿中；例\@ref(exm:prf)出自第二稿，作者为了表明该论文不是出自滥竿充数的＂戴着棒球帽的人”之手，对原句作了修改，重新写了出来。

    流行趋势来得快，去得也快。但是流行的追随者或实践者（与他们的不良习惯精神传承者），会永远留在那里，等待着那个可以预见的未来。当然，任何喜欢＂棒球帽＂的学生，可能同时又非常勤奋用功，也许有一天”棒球帽“会成为一种优秀学生的象征。

校外评审人
:   有两种主要类型的校外评审人。事实上，校外评审人是你的朋友，但是几乎没有人能够体会理解到这个深度，所以他们就被当做敌人了。他们这类人要么会毁掉你，要么使你更加坚强。

    如果你现在正在攻读博士学位课程，那么学校就会有专门为你聘请的校外评审人来监督你（一般每个学生有两位评审人，但是具体数目根据学校情况各异）。担任校外评审人的人都是你论文主题领域的权威人土。大多数校外评审人都是挑剔的学究式人物，他们往往会逐字逐句地阅读你的论文，用尺子或其他东西辅助他们勾出上次读到的地方，这样就不会错过任何一行字了。他们的作用在于确保你的论文能够达到国内任何一所大学的博士论文标准。博士生对于校外评审人的批判很担忧，可见这种担忧不是完全没有缘由的。

    一般情况下，相关的规章制度会写明担任校外评审人的条件与资历。例如，与你合作发表最新三篇期刊论文的人，由于与你的论文关系密切而存在可能的利益冲突，一般被认为不能胜任。如果你的领域非常特殊，可以担任校外评审人的人又非常少，在这种情况下，可能会存在问题。明智的指导教师在你刚开始写论文时就会指出一些可以充当校外评审人的专业人士，这样你就会在学术上适当与他们保持足够的距离，将来可以请他们担任自己的校外评审人，他们也会比较公平地对待你，虽然不一定比较温和但是能够保证公平公正。在很多地方，不公正的校外评审人不会受到邀请。一旦评判不公正的消息传播开了，就很少有人会请他了。

    校外评审人期望你的文章具备足够的分量，从而使你成为 “他们中的一员”。你要在论文中表明这一点，因为校外评审人可能从来都没有见过你，所以评审时着重看论文本身，而不去看你是个多么善良的人或你有多么用功。你的论文最好看起来像是专业人士的作品，注意重要的细节（你引用的文章是不是完整？是不是正确？）。你需要用专业语言写作，就像写给另外一个专业人士一样，避免用教材或通俗文摘中所用的简单语言。

    如果你在攻读理学硕士学位，那么你可能需要和其他人共用校外评审人。选出这些校外评审人。目的是为了保证能够达到此课程所要求的学术标准，这些评审人通常来自其他学术机构或其他行业，都是一些德高望重的人物。

你的导师
:   你的导师扮演着平衡者的角色。一方面，你作为一个有潜质的学术新人，将来可能会发表文章，成为导师与外界的混乱、黑暗、对手等斗争中的有力支持。另一方面，你需要时间和精力，这些又很匮乏，而你又可能花费时间与精力去做其他短期盈利的事情，比如说，申请基金、发表期刊文章、专注学术政治，还有在家自己动手做些事情或偶尔照顾一下家庭。

    导师也是人，他们有很多不同的方法来指导监督你的学习：包括听到你走近的声音就藏在衣柜里，或者做出禅宗般神秘的评论，或者非常细致地告诉你应该做什么与怎么去做。有些方法很好，有些却很糟糕，但是分清哪些方法有效、哪些方法很糟糕，也不是一件容易的事。如果导师清楚地告诉你哪一步要做什么的话，你可能会感觉良好，但是你工作了以后呢？工作了以后，你要单独完成很多事情，没有导师指导你，你该怎么办呢？

其他学生
:   其他同学可能是提供支持与启发的资源。但是他们也可能是误导者和沮丧心情产生的源泉，这也是为什么他们也被归在敌人之列的原因。

    在研究生中流传着很多传言，其中有一两个可能是真实的，但是大部分至多属于传言，甚至有些会产生危险的误导。如果对此有疑问的话，你最好去咨询一下你的导师，并且请他们解释为什么这些传言是不真实的。他们提供的答案可能帮你明白很多事情。

    研究生最喜欢的事情之一就是与他人做比较然后因为“攀比”结果不满意而沮丧。这种思维游戏有益于销售巧克力（巧克力可以使人心情愉悦），除此没有什么其他益处。避免这种思维的有效方法之一就是撒谎（“噢！进展很顺利，谢谢关心——很多有趣的发现，写作也很顺利”)。这样就能非常迅速地阻止宿命论者向你传播其信条，劝说他们不再打扰你。

### 物

书籍
:   书籍有很多种。教科书适合于本科生，其内容都是很简单的叙述。作为研究生你应该阅读真正的书籍。你一般会在期刊文童中或专业书籍中才能看到这样复杂的文字。在大多数学科中，书籍只能提供最前沿最时尚的信息；书籍是非常有用的参考资源，尤其是那些曾经改变某个领域的经典书籍。但这些书并不是唾手可得的，需要通过寻找得到。

    事情之所以这样，是因为这与资源有关系。完成一本书的写作需要大量时间与精力，除非你确实有大量材料可以写成一本书，否则打算写书的想法根本就没有意义。一般情况下，一项研究发现只能作为书中一个章节的内容，或者也能够构成一篇论文发表在期刊上。而且，这些书中的单项研究发现也不可能引起世界的足够注意，不足以拥有满意的销售量，能够卖掉几本就很不错了。对于一位职业研究者而言，写书不是他的最优选择：只要付出同样的努力，就可以创造出很好的期刊论文，这些在最近几年内会受到业内人士的关注，所以他们一般对写那类只能卖几本的专业类书籍不太感兴趣。（教科书和参考用书不同于上述情况，这类书籍是以市场为导向的，但是，却不是旨在用来做基本研究工具之用的。）

    然而，有些书是无价的，并且是经典信息的来源。比如，由卡尼曼（Kahneman）斯拉维克（Slavic）和塔沃斯基（Tversky）合著的书，该书主要阐述人类判断力和决策力的不足之处，可以作为该领域的经典之作。能够写出这样的一本书将对你的事业有非同寻常的影响，条件是你能够找到这样一个值得付出努力的主题。

    书籍有一点对你很重要也很有帮助，那就是可以让你先对这个领域有个大概的了解，然后再决定是否继续钻研下去。正常情况下，书中的一章涵盖了你所需要了解的这个层面的所有细节——比如，你不知道要不要在研究中涵盖博弈论，正在犹豫不决。这时候，关于这个论题的论文或者书籍对你来说篇幅有点长，很有可能使你失去耐心或者颇受打击，而书的一章可能对你比较合适。而且如果你决定沿着这个方向继续研究的话，这些章节可以提供你所需要的基本概念，并且这些概念又是你弄明白更多的高级文献所必须了解的知识。

期刊论文
:   发表在期刊上面的论文是你的朋友而非敌人，但是我们在这里探讨期刊论文，目的是为了重新阐述一些观点。你应该时不时地阅读期刊上面的论文，不管是关于你的研究方向的还是其他领域的，因为这些可以帮助你见识其他一些有趣的学科。这些也许将来在哪个地方就会大有用途。如果你的研究领域是理科类的，那么读一些类似于《新科学家》（*New Scientist*）、《科学》（*Science*）、《自然》（*Nature*）和《科学美国人》（*Scientific American*）等期刊，会对你很有裨益，这样可以及时了解世界其他地方都发生了什么事情。不论你学的是什么学科，你应该了解本专业最主要的期刊是什么刊物，并且定期阅读。

    作为一个博士生，你应该把目标放在发表论文上面。发表论文并没有人们想象得那么困难，关键是你必须知道自己在做什么。详细情况请参考关于如何在期刊上面发表文章的章节，了解这些细节就是个不错的开始。同样也要仔细阅读你打算投稿的杂志的“投稿须知”（Notes to contributors）部分。很多人都不屑于细读这部分内容，而因为懒惰付出了代价。

因特网
:   因特网很受“滥竿充数者”的喜欢。因特网可以帮我们搜索众所周知的消息，比如对于某个具体的问题这“瓦格兰姆战争是什么时候发生的“，你想要获得唯一的答案，但你可能得不到唯一的答案，退一步说，即使你得到了，答案也可能是错的。（因为爱达荷州的任何一个少年都有可能制造一个网页，上面充斥着不可靠的信息。）

    对于其他的问题，网络可能提供很多不可靠的非专业的消息源。这些消息中有的是虚假信息，也有的是完全的谎话。某次搜索你可能偶尔会找到一个不错的最新参考文献，但是这不能反映该领域的最新概况，因为你无从查核该信息的真伪。

    你永远无法了解事实上发生的事情与人为放在网络上的内容反映的情况之间存在怎样的关系。对于你的研究领域内的系统信息而言，你需要采用适当的信息来源，比如文献数据库这（bibliographic databases）这些能够反映出最新发现的状况。你应该了解自己专业的主要信息源，要和相关的图书管理员处好关系，因为我们查资料的时候，他们有时候能够帮上大忙。学会如何做研究也非常有用处。

### 习惯

习得无助感（learned helplessness）
:   如果动物试图逃跑，你用电击可以使他们无处可逃，直到它们不再想逃为止，甚至到最后——即使情况允许它们成功逃脱，它们也不会再逃了。[就像米尔格兰姆（Milgram）主持的生存适应试验一样，其研究试验可能没有办法通过道德委员会的讨论，但是这样的研究却很有意义：因为通过研究，我们可以洞察到一些在人类看来一般不可能发生的行为的存在。］

    博士研究生尤其倾向于有这种无助感。一般情况下，段时间内，他们感觉到学业没有进展，就会感到没有必要继续下去了。如果你也曾经经历过完全如上面所述的情形的话，也曾经想过就这样放弃研究，那么你要鼓起勇气（“吃些巧克力”可以帮你重新鼓足勇气），找一本关于自助的书来读，比如《感受恐惧与战胜恐惧》（*Feel the Fear and Do It Anyway*）。仔细阅读你找来的书，给自己设立一些可以实现的目标，但是这些目标至少和研究课题有些关系。找一个能够给你提供明智建议的人聊一聊，并从他那里获取一些建议和支持。同样，除了常规的研究工作，还要与此领域以外的人或事保持一定的联系，从而能够获得一种洞察力。一旦你完成了这些事情，就足够帮你走出意志消沉的状态，并且为自己规划出明智的道路迈步向前。

    设计周全的研究有很多优点，其中之一便是在每个研究阶段，你都准确地知道自己在做什么工作，而且为了迎接即将到来的每种可能性，你都能做到未雨绸缪，知道如何应对。这样做的缺点便是你可能提前知道自已将要花很长的时间去啃资料，但是这样也有好处，既然已经知道要做什么，你就应该清楚地知道如何去啃掉资料以及如何处理最后得到的结果。如果不能提前知道这一点，那么你就需要重新考虑你的研究设计了。

表现性行为
:   表现性行为经常伴随着习得性无助出现。工具性行为指能够帮助我们实现目标的行为。表现性行为指那些旨在向他人表现你是什么样的人的行为。一个学生坐在图书馆里辛苦研读6篇其研究领域中的核心教材，其行为被称为工具性行为。坐在旁边桌子的学生，正在读一篇不相关的论文，反反复复看着同一页，看起来像濒临精神崩溃的样子，此学生的行为就是我们所说的表现性行为。他用行为想表达：看看我吧！我多么用功啊！请可怜一下我吧！如果某个学生的论文中包含了校外评审人喜欢的所有特征，那么这个学生也使用了表现性行为，但是这样的行为却很有裨益。评审人一般给你的论文打分，却不关心你是怎样的人，有人在两天内成功写出一篇很优秀的文章，有人也许花了几个月的时间结果只是一篇普普通通的文章，这种情况下，前者会比后者更受欢迎，分数也会更高。所以要懂得适时地运用表现性行为。

时间大把花费，研究毫无进展
:   出现这种事倍功半的情况，是有很多不同的原因的。

    ```{proposition}
    虽然你花了很多时间，但是研究却毫无进展，原因在于你根本不知道自己在做什么，也不知道这样做是为了什么。
    ```
    <br/>
    在这样的情况下，重新设计你的研究不失为一个好主意。这指的是；你需要修改研究课题，确保不是把所有赌注放在哪个具体的发现上面。拿自己几年的生命作赌注，是很不明智的；只有自已完全确信时才开始做研究，深信研究结果一定能够证明自己一开始时的想法，这样做是非常不可靠的：如果研究发现与你以前的想法不相符，你怎么办呢？伪造数据，还是面对现实，改变自己的想法呢？

    ```{proposition}
    你忙于做些无形的准备活动。这些活动对于做好研究尤其重要；从定义上看，虽然付出努力，但是却不能够创造任何可见的成果。比方说，你忙于准备文具，或者你在做文献准备，查看有没有人已经做过类似的研究；或者你在做大量泛读，了解一些背景知识（相对于精读而言）。这些事情必须要做。文具很重要，背景知识也不可或缺。
    ```
    <br/>
    这里大力推荐泛读，因为很多一流的作品都来自于将一部作品应用于另外一部作品。（我们中有人曾经指导过一篇本科论文，那篇文章就是用一位19世纪的研究者的形式主义来研究俄国民间故事结构，并且将其用于电脑游戏情节研究，非常优秀，也很有趣，对于电脑游戏业有很多启发。）问题是你从来都不能够事先就知道哪些东西在哪些时候在哪里有用：俄罗斯民间故事就是从20年前的主题中读到的。这样做的好处在于，当你碰到类似于这种可以 “异体受精 ”的有关主题，你就可以毫不费力地创造出很优秀的文章。我们建议涉及这个领域，你可以等到一切准备就绪，可以发表文章时，再将你的想法公布于众。因为问题的关键不在于实际的发现本身，而在于将一种具体的作品主体用于其他领域这个想法本身。

其他不同种类的不良习惯
:   研究者面临着很多令人头痛的坏习惯，比如说不善于安排时间、习惯于拖拖拉拉、不愿意费力气去了解这一行的关键。为了能够适当处理自己所有的问题和困难，你需要学着去找出这些不良习惯然后加以改正。这并不是说你为了改正而去改正。很多习惯属于个人喜好和选择，对于这样的不良习惯你需要明确一点，那就是这个不良习惯的积极方面值得肯定、值得付出一定代价。例如，有人习惯于根据自己的兴趣做研究，而不去顾及这是否看起来像是不错的职业行为。除此之外，还有一些不良习惯存在，比如拒绝承认自己的错误，就是一个对你不利的坏毛病。没有变化，你就不会有进步。你经历的任何变化都不是一帆风顺没有痛苦的。学会接受痛苦，这样你的生活才会发生变化。

    也许有人会担心与痛苦紧密接触会造成一些长期的后果。对于这点，你大可放心，因为总有一些做研究的方法可以帮你不必冒险承认自己的错误，你的任务就是学会这些风险很小的方法。其中很典型的例子就是，在措词撰写研究课题的时候，表明你不会对任何可能出现的结果负责：不管发生什么事情（除了完全混乱的状态），你都能够证明自己已经在文章一开始指出了该问题可能存在。
