# 阅读 {#sec-reading}

读博士期间你必须进行大量的阅读。阅读材料必须选对，同时你要正确地利用这些材料。本章讨论的就是这方面的内容。

这一章与讲写作的第八章有不少重叠。原因有很多，其中之一是，你通过阅读才能获取写作需要的信息（比如写论文）。另一个原因是，如果你了解了有经验的学者是如何构思和组织他们的文章的，你就能更有效地进行阅读。

本章将涉及在线搜索（online searching）的许多细节。在线搜索与因特网搜索是不同的。如果你想要成为一名优秀的专业研究员，你就必须对两者进行区分，并且熟练有效地掌握这些搜索工具。

我们在这一章里还将对不同种类的论文和不同种类的研究做很多讨论。了解了这些概念，关于文献的很多东西就会变明白易懂。如果你正在考虑写论文，或者正计划做一些论文课题以外的研究来发表文章，那么这部分的内容会对你很有帮助清晰地认识自己的目标，你才能更有效地汁划和进行研究。

## 找到正确的参考文献

你在写作时必须传递正确的信息，这就意味着你在下笔前应该下工夫阅读你该读的东西（第一条黄金法则是：不要撒谎，即不要假装读过你没有读过的书）。当然，也没有必要太过分。一般一篇好的学术论文在第一页的每一段会出现8次引用。但第24页还会出现同样数目的引用吗？不会，因为没有必要——作者在这时候已经引用了基本上所有需要被引用的参考文献。那么你怎么知道哪些文献是你需要引用的呢？

最简单的办法是礼貌地询问你的导师，该从哪儿着手。如果你的导师不知道，礼貌地问别人，并时时向导师汇报你的进程，以免步入写作误区。你应该传达这样的信息，那就是，你是一个勤奋的、能从别人的建议中受益的学生，而不是一个不想自己动脑筋做研究的懒虫（可以先说明自己已经读了什么，然后询问下一步该做哪些工作）。导师在这方面能起到举足轻重的作用。

如果你很用功也很走运的话，你的导师可能会对你说类似这样的话：“这方面你需要找的人是X，我已经发了电子邮件给他，他会很乐意给你一些指导。这是他的电子邮件地址。”这类话是一个令人鼓舞的信号，在学术界，它传达了以下这些意思：

* 你可以省去很多麻烦；
* 你可以得到机会与领域内的专家接触；
* 我对你有足够的信任，所以才让你自己去与这些重要人物谈话。

如果导师给你这样的机会，一定不要错过。

## 研究者的核心文献库

大多数优秀的研究者都在记忆中储存了一个相关文献的数据库。这就意味着，从所有阅读过的资料中，他们会选择50-100篇文章记在脑子里。随着阅读不断进行，这个脑子里的核心文献库也会随若学科发展或研究者的兴趣转变而做相应调整。然而核心的某些部分会留在记忆中长达数年。有趣的是，一篇论文的参考书目在理想情况下至少应该包含的文献数目恰好是100左右。博士生应该做的一件事就是组建第一个“核心”文献库。（当然，库存可能有大有小，但数目其实并不重要，重要的是能够在记忆中储存一系列相关文献的信息。）

那么，应该从哪里着手寻找参考文献呢？你的导师可能会提醒你留意在你已经读过的学术文章里出现过的文献综述，以及评论性文章。导师也可能会指点你进行在线搜索。搜索的关键词可以是你的导师提供的，也可以是你在读过的文章中找到的。接下来我们还会更具体地讨论这方面的问题。我们的讨论不仅将涉及文献综述，还包括论文整体的构架。

除此之外，你的一个任务就是要对阅读材料的质量进行评估。一般来说，这项任务对学生并不容易。如果你看到一篇完全读不懂的文章，是因为它写得太好、太深奥而使你无法理解，还是因为它只是一堆做作的、故意让人迷糊的垃圾？这一章的末尾将给出一些方法，从而使你能够（a）评估你的阅读能力，（b）提高你的论文写作水平。

## 文献综述

学术文章或论文一般都是以文献综述开始的。有很多原因可以解释这种安排。

一个显而易见的原因是为论文将要涉及的研究工作进行铺垫（比如告诉读者前人已经做了哪些工作）。引用前人的研究要采用标准的引用格式，以方便感兴趣的和持怀疑意见的读者查找原文出处，与文献综述的内容作对照。第二个原因也同样重要，那就是通过文献综述证明你已经系统地做了相关研究，让读者相信读你的论文不会是浪费时间。

文献综述应该有一个清晰的结构以方便读者阅读，因为即使是再好的学术性文章也会比较艰深难懂。清晰的结构也可以显示出你了解自己在做什么，以及为什么要这么做。让读者读懂你的文章是你的责任，而不是读者的责任。如果你从网上找来一些参考资料不加区分地堆在一起，那么读者没有责任帮你从一篇混乱的文章中理出思路。

文献综述最常用的，也是我们赞同的一种结构，是从某领域的最早研究开始以时间顺序讨论所有迄今为止的重要研究。按照这种结构，你的引用就应该从该领域最早的文献开始，接着介绍一些各个时期最重要的文献，最后写当下的童要文献。之后，你的参考文献则一般从旧的研讨会参考文献开始，接若是近期的关键参考文献和次重要的参考文献，最后是最新的重要参考文献。

有一个问题常常会引起混淆，那就是文献综述与引言之间的关系。这方面不同学校和个人有不同的做法。有的喜欢把文献综述和引言作为单独的两部分，有的则喜欢把两者合在一起写。我们的建议是要弄清楚，你所在的学校在这方面有没有相关规定，如果有，就按照规定写，如果没有，就按照你自己的喜好写。没有必要纠缠于这个问题上。

文献综述的核心是一个好的“情节”。文献综述应该以某个问题开头（比如，一个神话故事可以从一条巨龙摧毁了整个国家开始讲起，研究性质的论文可以用某个领域的一个问题来吸引读者）。文献综述和／或引言接着就可以讨论前人为了解决这个问题做了哪些努力。文献综述和／或引文应该以你（主角）的登场结束。你是故事中的主角，带着神秘武器，也就是你的研究方法登场。接下来的论文或文章就沿着你探险的足迹发展到你取得胜利的那一刻为止。如果你在最后没有取得胜利，那就说明你在一开始就没有一个正确的实验设计，这也就是你的问题所在。串联全文的线索有很多名字，比如不“情节”，“叙述线索”，大部分经验丰富的出色作家都很重视它的作用。

新手往往觉得“叙述线索”难以掌握。如果你有意识地下工夫练习，那么你就会慢慢地得心应手，否则问题不会自动解决。你可以用很多办法来帮助自己练习。一个简单的方法就是进行自上而下的分解。将故事里的重点列在一张单子里，单子不要太长最多6句简短的句子，比如：

用卡片归类法对软件进行量化评估

* 对软件量化很难
* 卡片归类法会在量化方面比先前的方法更具优势
* 在这个领域采取卡片归类法会出现什么情况？
* 卡片归类法的确较先前的方法具有优势

你对这样的上层结构满意了之后，就可以将其中每个部分分解为几个小部分，如果必要的话，可以不断重复这个过程。最后你得到的应该是各部分的小标题，次级小标题等等，而这些就组成了论文的整体框架。

事实上，即使论文结构清晰，读者们在阅读过程中往往很容易“迷路”，因为论文里包含的信息量实在太大了。因此一个聪明的作者会使用过渡段和指向标。过渡段是将文中的两个部分连接起来的段落，它总结上一段，引出下一段的内容，并向读者解释上下段的联系。指向标是告诉（或暗示）读者接下来会出现什么内容的段落。

在这个阶段，你应该广泛地参考学术期刊，将其作为主要信息来源。教科书和因特网在开始阶段很有用，但不适合作为主要的信息来源，因为它们往往在陈述时过于简化。

我们听说一些挑剔的导师会给学生明确的指示，规定哪些资料是只能作为前期熟悉某个领域的工具来阅读，而不能在论文中作为信息来源引用的。可以举出很多这样的资料，比如《统计陷阱》，以及《飘虫系列电脑入门》（*The Ladybird Book of Computers*）。

## 在线搜索

文献综述虽然是指导你了解文献的有用媒介，但它并不是万能的。文献综述的作者在写作时也不可能考虑到你的特殊需要。所以你有必要自己去摸索，寻找与你的研究有关的文献。

如果一个学生在文献综述中写了类似这样的话，“在网上没有找到与这个课题的相关的前人研究成果”，导师和校外评审人虽然不能杀了这个学生，却能判这个学生不及格，并在那一页让人气愤的纸上写上尖锐却不失风度的批评，这多多少少弥补了法律体系在这方面的漏洞。

为什么导师和校外评审人对这句话如此反感呢？答案是：因为这等于是明目张胆地告诉读者：“我很无知，或很懒惰，或者既无知又懒惰。”这可不是你想向你的读者传达的信息。

### 传达正确的信息

如果你希望别人认为你很专业，你就必须传达能显示你很专业的信号。每一行的专业人士都精通他们那一行的工具比如，脑外科医生应该掌握手术器械和相关知识，比如脑的生理机能。

任何属于学术圈的人都应该掌握学术圈的工具。学术等级不同，需要掌握的细节数目也不同一比如，要求本科生了解的信息比要求博士生了解的信息少，同样的，对博士生的要求又比对某领域专业级学者的要求低。但如果你掌握了你这个阶段还不需要了解的信息，这当然是一件好事。

学者打交道的对象是知识与信息，所以应该知道怎样获取、解释和展示知识与信息。其中一个重要环节就是要找到最好的信息来源，以确保你对研究课题的评估是建立在最为可靠的知识与信息的基础上的。学术文献有一个长幼尊卑的排名。这个排名在某种程度上是一种势利行为，但基本上还是依据每份刊物的质瞿监管水平得出的结果。一份刊物的质量监管越严格，它享有的声誉也就越高。这个概念简单合理，它也给研究人员带去了方便和可靠感。当你要在一个课题上花去数月数年的时间，或许还有一大笔钱的时候，你会希望你得到的原始信息有可靠的来源，能确保这一点会给你带来很多安全感。

百科全书中的文章和顶级期刊占据着排名的最高位置。百科全书一般会邀请领域内的著名专家为其写文章能被邀请是一种极大的荣誉。被顶级期刊接受的文章一般都需要有若干个相关领域的国际权威进行仔细的审核才能发表。任何不符合标准的文章都会被拒之门外。

排名接下来就是一些中等水平的期刊。它们也有审核的制度，但聘请的专家往往不是最有名的。排在最下面的是一些专业性的业务通讯和行业杂志，它们刊登的文章可能也经过筛选，但是由编辑而不是专业评委来做这项工作。

一份刊物的实际地位会受一些个别因素的影响——比如，一些专业的业务通讯因为由非常著名的权威人士编辑，会有极高的投稿率，在排名上也会胜过某些期刊。书的权威性等级也有很大差别。一个基本原则是，教科书排在后面，因为它们往往为学生陈述简化了的事实，而专业性书籍却有可能享有极高的声誉。

善于观察的读者应该已经注意到了，我们对排名的描述到现在为止还未涉及因特网、报纸或大众杂志。这是有原因的。因特网对网站内容完全没有质量监管。如果你发现了一个和你研究有关的、看上去很有趣的网站，它可能是某个权威创办的，但也可能是某个幻想着自己的头脑里装了外星人的控制装置、从皮奥里亚一家比萨店楼上的大学拿了个学位的家伙创办的。报纸和大众杂志至少还有一定的质量监管，但如果你认为读报纸能体现出你是一个经验丰富的专业人士，那你还不如去那家比萨店楼上的大学念书呢。要记住，“在线”指的是图书馆数据库和光盘检索，“在线”不需要你上因特网。

### 在线检索概述

在线检索的一个主要目的就是要找出已经取得的研究成果，这样你就不用浪费时间去解决已经有答案的问题了。如果研究已经取得了一些成果，你应该对其有清楚的认识。如果你没有找到任何别人做过的研究工作，你应该确认自己的检索是否全面，必须在很有把握的情况下，你才能说，“这个领域到目前为止还没有人研究过”。如果存在重要的文献，而你没有找到，那么最轻的后果是，你会显得挺可笑，最糟糕的后果是，你可能被认为是为了确立自己研究的优先地位而忽略前人的研究成果，并被指控为学术舞弊（本科生不大可能受这种指控，而有志于学术事业的博士生则要小心了）。因为这个原因，声称“这个领域到目前为止还没有人研究过”其实就是明摆着给自己找麻烦，大多数聪明的专业人士会选择其他表达方式，比如“这个领域在过去似乎没有引起人们的注意”。如果存在着他们没有发现的文献，这种说法能使他们不至于完全丢面子。

那么，你该如何去寻找已经取得的研究成果呢？你需要考虑三方面的因素：来源、策略和技巧。“来源”指的是去哪儿找，“策略”指的是如何去安排搜索的过程；“技巧”指的是该选用什么样特点的搜索引擎这类问题。

### 来源

这个世界包含的信息数目宏大。举个例子，每年都会出版数量很多的物理学期刊，一个人一天24小时不间断地阅读，读上一年也读不完——你完全没有办法跟上当下的出版速度，当然也就更不用提19世纪开始积累起来的庞大库存了。

为了方便大家，图书管理员和专业的索引编制机构为期刊内容（也包括其他信息来源）设立了索引。这就意味若，你可以通过查找某一类索引里的一个关键词，从而找到涉及这个关键词的文章在何时何处发表过。当然，每一个索引覆盖的期刊都是与某个索引主题相关的，因此物理学期刊同在一个索引下，而化学期刊又在另一索引下。比较老的索引是印刷在纸上的，较新的索引刻录在光盘上或储存在网络数据库里，一般要有密码才能进入（图书管理员掌握着许多进人数据库的密码，但使用其中某些数据库需要收费）。

这就意味着，如果你想知道在某个领域已经做了哪些研究工作，友好的学校图书馆管理员将成为你的帮手。你可以从图书管理员那里了解到相关索引的位置。进入索引也就意味若，（a）你很有可能找到与课题有关的重要信息，以及（b）如果找不到任何信息，很有可能的确没有相关的学术文章发表过对于博士阶段侧重于原创性的研究来说，这是很重要的考虑因素。（找不到也可能是因为你的关键词输人错误，我们将在接下来的两方面谈这个问题。）索引的另一个优势在于它具有一定程度的质量监管只有声誉良好的信息来源才能够被列入索引。你通过索引找到的事实及论点往往是有依据的。

### 策略

找到了一个好的索引之后，就要有一个搜索策略。一般新手的策略是输入两到三个关键词，然后就等若出结果。这种情况下一般来说，屏幕上不是显示没有记录，就是显示有上百万条记录。相比之下，另一种更高级的检索方法就显示出优势了。

有很多介绍如何有效进行搜索的好文章，很值得一读。这部分只是就这方面做一些基本介绍，我们建议读者们还是要读一些专业性的文章。

一种有用的策略是在事先做检索计划。另一种策略是在检索过程中做记录，以避免循环检索。

检索方式多种多样。标准信息科学文献中有一个有用的概念，即“已知项目”检索。它指的是，你要寻找一个特定的项目或者事实——例如，你想要找哈特利（J. R. Hartley）写的飞钓》（*Fly Fishing*）这本书，或是想要知道该书的出版日期，而这些检索的前提都是，你是确定有《飞钓》这本书存在的。这类检索，一旦找到结果，检索任务就完成了。

在进行其他类型的检索时，有时你会不知道该在什么时候停下来。举个例子，如果你想找到对某个领域先前研究成果的概述，你就隔要做大趾的检索，而且几乎肯定会遇到这样的情况，那就是系统显示没有记录，或者列出上百万条记录。所以你需要采取策略提高命中率。

一种简单有效的方法就是输入一个关键词，再在系统给出的条目中寻找有关记录。你可以从这些相关记录中再次寻找可以作为关键词的选项，进行二次检索。作者的姓名往往可以用来做关键词（但像史密斯这样过于常见的姓名除外）在某个课题上发表过一篇文章的作者通常会有其他相关文章发表，这些文章的合著者姓名又可以作为关键词使用。技术用语也是如此，你可能会发现很多不同的名字指的都是同一个概念。你可以输入一个较具专业性的关键词（如果前一次检索得出的条目过多的话），或者一个较为宽泛的关键词（如果前一次检索得出的条日过少的话）。

### 技巧和命令

不同的检索引擎有不同的运作方式，如果把同一个关键词输入不同的检索系统，就会得出不同的结果，这种体验非常有教育意义。然而尽管彼此不同，它们的运作方式都建立在几个基本概念上，而掌握这几个概念能大大提高你检索的效率和效果。

两个关键的概念是加权（Weighting）和布尔数学检索（Boolean Search）。

加权
:   加权就是给各个事物分配不同的权重（比如从重要性或相关程度上来分配）在这里，通常指的是给关键词和记录分配不同的权重。这使得搜索引擎可以对给出的结果进行系统的排序。一种较为普遍的排序方法是使用“逆文本频率指数”（inverse frequency weighting）越不常见的词条得到的比重就越高，理由是它的指称对象会比较具体，信息含量也会较高。举个例子来说，如果输入“低墒系统”这个关键词，检索引擎会给“低”和“系统”分配低权重，因为在数以百万计的记录中都出现了这两个词，而“墒”分配高权重，因为这个词出现的频率很低。

    在选择关键词时应该记住一点：用具体的关键词会搜索出较少的记录，但其中有用记录占的比例会比较高。

布尔数学检索
:   布尔数学检索是在关键词中加入“AND”，“OR”以及“NOT”这些词。例如，如果关键词是“储存”AND“网络”，搜索得出的结果就是所有同时含有“储存”和“网络”这两个词的记录。如果关键词是“储存”OR“网络”，搜索得出的结果就是所有含有“储存”的记录，加上所有含有“网络”的记录。如果关键词是“储存”NOT“网络”，那么搜索得出的结果就是所有只包含“储存”而不包含“网络”的记录。如果你在检索过程中想要排除与你研究的课题名字相近的另一个课题的相关信息，这个方法就很管用。举个例子来说，如果你要查找有关巡回上演保留剧目的剧场（repertory theater）的信息，却发现很多检索结果是关于凯利方格技术（repertory grid technique）的，那么布尔数学检索就可以帮你解决这个问题。

学会高级检索是很有用的。你可以询问图书管理员有关高级检索的知识，他们通常会很乐意帮助你。

## 其他信息来源

与一位专家在喝咖啡时友好地交谈往往可以使你得到很多有利于你研究的信息。

也可以参考相关教科书的参考书目，它会列出很多对你有用的文章。更好的办法是参考评论性的论文以及较新的百科全书。评论性论文和百科全书都是可以在论文中引用并列入参考书目的。教科书则不适合列入参考书目，因为它传达的信息是：“我读的是为起步者编写的、简化事实的书，而不是专业书籍。”

与图书管理员保持友好关系也很有用——他们愿意与礼貌的、欣赏他们的人分享他们的宝贵知识。

## 有经验的评审人如何读论文

最有意思的东西往往在论文的文字背后。在美好的过去，导师的典型做法是约你喝一杯雪利酒，边喝边向你讲述这个道理（这是一种很让人感到惬意的教学方式，对师生双方都是如此）。如今的学生们则都是通过艰辛的实践才悟出这个道理的。

这部分讨论了有经验的专家（比如你的校外评审人）在审阅论文时会考虑的几个方面。

在一开始就需要指出的是，别以为论文中的错误只要出现在后半部分，就能躲过读者的注意。有些读者，尤其是校外评审人，会仔细地阅读论文的每一句话一——比如，他们会拿一把尺子，一行行地往下移，以确保他们不漏过任何细节。他们会记下每一个他们将要指出的错误、疑问和批评意见。同样需要指出的是，有经验的审阅人浏览文章和查找错误的速度是你无法想象的。

以下列出了评审专家关注的论文的各个部分，它们是按照审阅专家审查论文的顺序来安排的。这个顺序与这些部分在论文中出现的先后顺序不同，而它们在论文中出现的先后又与你写论文的顺序不同。

### 参考文献

评审人往往会在读论文主体前先看参考文献。参考文献包含着很多信息。参考文献的失败往往会反映在质量低劣的论文主体中。以下列出了评审人评估时依据的主要标准。

必须符合的要求
:   * 你采用的格式，包括每一个标点符号，都正确吗？
    * 你是否引用了所有重要的核心文献？
    * 你引用的文献是否具有多样性，有没有覆盖最重要的以及最新的文献？
    * 你的文献来源是权威性的学术期刊，还是教科书和因特网？（在这个阶段，你应该已经把学术期刊作为主要参考资料来使用，教科书和因特网只能是在极特殊的情况下才拿来使用。）

加分项
:   * 你是否引用了一些不常见的，只有某领域的高级研究人员才知道的文献？
    * 你是否引用了正在印刷、还未出版的文献？（如果是，这意味着你已经真正成为一名学术圈的成员，有资格获得预先印发稿。）
    * 如果你引用了预先印发稿上的内容，该稿件的作者在领域内是否占有重要地位？
    * 你是否引用了你本人在权威期刊上发表过的文章，其中有没有与著名学者合著的文章？

### 附件（对于博士论文而言，一般论文不要求）

经验丰富的评审人在阅读论文之前一般还会检查附件。附件包括你在研究过程中制作的材料，比如你给调查对象看的简要说明材料。如果附件中的材料设计得很糟糕，语言陈述也不清晰，那么你采集的数据很可能就没有什么价值。

好的附件
:   * 完整的研究各阶段样本，包括从最初的数据采集到最后的制表。
    * 给调查对象看的材料显得清晰而且专业。

不好的附件
:   * 附件中包含了所有的原始数据，使附件比论文的其他部分都长。
    * 给调查对象看的材料制作粗糙，版面不整洁，语言不清晰。

### 标题页与致谢

专业评审人在看学生论文的这两个部分时会留意是否有拼写之类的错误。他们也往往能发现有这样的错误存在。一个很普遍的错误是拼错了导师的姓名，或搞错了称谓。到了博士阶段，你可能已经了解了不同称谓的微妙差别，但对于攻读硕士学位的学生来说，有很多人，尤其是学工科的，往往懒得去确认导师的称谓，有的即使意识到这个问题的重要性，也弄不懂其中的规则。如果你有疑问，可以查看教师名单或问别人。把别人的称谓搞错是很有效的激怒别人的方法，在企业和学术圈都是如此。

在读摘要和论文主体前看看致谢词其实是一种无害的娱乐。某些情况下致谢词也很有用——比如，如果一个学生在致谢词中感谢一位领域内权威学者对他的帮助，那可能预示着这个学生的研究会很有趣。

论文的选题也是一件很有趣的事——题目是狂妄、模糊、充满了空洞玄妙的术语，充满了让人费解的技术名词，还是无聊乏味，无法给人留下什么印象？一个理想的论文题目应该提供有用的信息，简短好记。这样读者才会对你的论文留下长久印象。你在未来得到财富和荣耀的可能性也就提高了。将题目分成两部分往往是很奏效的方法。第一部分的题目应该是好记、能吸引人的，第二部分的题目用冒号与第一部分隔开，它解释和阐明第一部分题目的含义。我们自己创意的题目包括很多类型，比如“阶梯技术”，这是一个非常短的，极简主义风格的题目，我们用它作为一篇篇幅很短同样极具简主义风格的文章的标题。又比如“探究那不可知的：要求变化的原因和性质”，设计这个题目是为了吸引眼球，事实证明它的确吸引了很多读者的注意力。

要记住，人们在查找关于某个课题的文献时，往往会将题目作为检索项，所以如果你的题目离奇古怪，没有包含任何与课题有联系的关键词，这样的题目可能就无人问津了（除非你的论文非常出色，人们在谈起你的论文时也就留意到了它的题目）。而一个像“阶梯技术”这样的题目，虽然短而又短，但它却确保了当人们在检索有关阶梯技术的文章时，一定会命中以它为题的那一篇。如果你使用由两部分组成的题目，关键词往往会在第二部分出现（但没有规定必须如此）。

关于致谢，还有一种可能的说法：一些老道的研究人员，如果他们的论文需要提交评委会审阅，他们会在感谢词中感谢所有他们不愿意看到出现在评委会名单上的学者名字。这样做的逻辑在于，因为潜在的利益冲突问题，任何在感谢词中出现的人员都不会被请来当论文的评审人。所以，如果你与领域内的某个学者起过争执，关系不和，你不想让他审阅你的论文，你可以在致谢词中礼貌地写上：“我要衷心感谢X在这个问题上与我进行的多次讨论。”这样你遇到麻烦的可能性就大大降低了。

### 摘要

写论文摘要本身是一门艺术，需要练习才能完善。你应该在摘要中说明（博士论文最好是一页A4纸的篇幅，一篇普通论文最好是一个段落的篇幅）你做了什么，为什么这么做，你的发现是什么，你的研究在理论和实践上有什么重要意义。如果你在一开始就对自己是否能取得重要的研究成果心存怀疑，那你就应该重新设计研究方案，不过我们现在要谈的可不是这个。

我们能给出的最好的建议是尽可能多地获取专家的反馈。另一个好办法是阅读你的研究领域里的重要学术论文，学习它们的摘要是怎么写的。

好的摘要
:   * 恰当地使用专业术语
    * 清晰
    * 陈述重要发现及其意义
    * 拼写和标点符号使用正确（这是论文主体的第一页，决定着读者的第一印象，所以你应该费点心思把它写好）。

不好的摘要
:   * 不妥当的写作风格
    * 大话连篇
    * 自我推销
    * 空洞的内容
    * 不清晰的表达

### 目录页（对博士论文而言，一般论文不要求）

博士论文必须有目录页。

好的目录页
:   * 论文的框架结构符合特定研究领域的学术规范标准（如果该领域存在着统一标准的话）
    * 整洁
    * 清晰
    * 给出有用信息
    * 合适的表清单
    * 合适的图清单

不好的目录页
:   * 论文的框架结构不符合规范标准
    * 粗糙且不清晰
    * 图表清单与论文的研究领域不匹配
    * 目录页上的页码数与论文中的页码数不对应

每个研究领域对图表的规定都不一样。有的喜欢使用图表，有的不喜欢。如果你用了别人书上的表格，还要留意著作权问题。

每一张表格都应该是有用的。你认为有必要用多少表格就应该用多少表格，但不要多于必要的数目。还要防止将一个信息用多种形式表达——这会让人觉得是不必要的堆砌，读者们甚至会怀疑你在有意分散他们的注意力，为的是要隐藏论文的某个薄弱环节。当然，的确存在着特殊的情况需要用到多种形式表达同一个信息，但这样的情况非常少，如果出现，你应该在列出图表之前进行解释。

掩饰论文低劣质翟的惯用招数有：

* 幽默（第二条黄金法则：不要故作幽默）
* 剪贴画（clip art）
* 用不同图表展示同一材料
* 用很多颜色来装饰图表
* 附件材料过多

如果以上的任何一点表现在了你的目录页（或论文的其他部分）里，你就有可能遇上麻烦。

### 首页

首页通常是引言的一部分（虽然情况并不都是如此，有的学者写作风格奇特，不同领域间也有差异）。这一页很重要，因为大多数的考官或其他审阅人都会在看这一页时就形成对你整篇论文的第一印象——论文是很出色、一般、勉强合格，还是很糟糕。第一印象一旦形成就很难改变。以下给出了两个例子，它们都摘自己发表文章的首页。

::: {#exm-prf-page}
阶梯技术是由欣科（1965）最先发明的。与凯利方格技术（例如肖，1981）一样，阶梯技木同样起源于临床心理学和人格理论，尤其是凯利（1955）的个人建构论是（PCT）。然而，在认知心理学（例如格里瑟，1978；格里瑟，罗伯森，拉弗莱斯和斯万哈特，1980）以及职业心理学领域也独立出现了以层次任务分析（例如安奈特和邓肯， 1967；霍吉肯森和克劳肖，1985）为形式的类似方法。需要指出的是，虽然用后者得出的结果与阶梯技术相似，但后者荻取信息的方法大体是由无组织的采访构成的（参考霍吉肯森，op.cit）。
:::

::: {#exm-amt-page}
分类技术的基本概念是请调查对象将事物分成不同的组。用来分组的事物可以是具体物体，比如不同种类的老鼠，也可以是图像，比如各种样式的屏幕图像，还可以是描述物件或情景的卡片，比如写了很多编辑名宇的卡片。组别可以由调查人确定，也可以由调查对象确定，或者由双方讨论决定。分类技术在获取调查对象的不同类型，以及考察调查对象类型判断的分歧方面很有用。
:::

@exm-prf-page 里节选的论文文笔简练，包含了所有关键材料，还涉及了讨论类似技术的另外两类文献。这说明论文的作者做了充分的准备工作。文章还对不同的技术作了比较，体现了作者不仅仔细阅读了其他文献，并且真正读懂了这些文献。语言很正式，作者还用了学术写作的缩写形式，比如“op.cit”。这显然不是一篇业余人士用网上找来的资料拼凑出来的文章。

@exm-amt-page 节选的论文明显没有前一段正式。我们看不到任何相关文献的信息，论文的陈述因而显得毫无根据。作者显然在分类技术方面有一定实际经验，但我们无法通过论文判断，作者是一名学者还是相关领域的工作人员，是一位专家还是一个新手。

第一段论文容易使人产生艰深难懂、不顾及读者接受能力的印象，然而对于学术圈的读者，它却传达了一个明确积极的信息——这是一篇踏实、有含金量、专业性强的论文，作者对自己讨论的课题了如指掌。虽然读起来费劲，却不是那种意思模糊不清，充满了玄妙空洞的术语的文章。一名期刊审阅人或一位校外评审人在看到这段文章时会想：“看来我不会判这篇论文不合格，如果整篇论文都像这一段那么棒的话。”

这两段论文的有趣之处在于，它们出自同一个作者之手，讨论的课题也紧密相关，唯一的一个明显区别是两者的写作目的。第一段文章节选自一篇通过正常渠道投给期刊的学术论文。它必须显示出足够的学术分量才能说服审阅人，使他们相信这是一篇值得发表的论文。第二段节选自一篇写在百科全书上的文章。百科全书的读者群是非专业人士，这就意味若文章的特色和要求必须有别于期刊论文一比如不需要使用高度精简概括的句子。

好的首页
:   * 清晰
    * 合适的写作风格（要显得正式，即使这意味着文章枯燥生硬）
    * 使用正确的参考文献
    * 提出好的研究问题

不好的首页
:   * 体现不出学术性
    * 不清晰
    * 没有提出研究问题，或者问题提得不好
    * 恳求读者的同情体谅，以及其他透露出文章弱点的迹象

有判断力的读者在读完首页后，往往会翻到讨论方法或给出结果的章节（并不总是如此，但一般情况下，他们不会马上看第二页）。

### 方法部分

方法部分的存在是有原因的。那就是，如果任何人想要复制你的研究，或者在你研究的基础上继续改进，那么他们有必要了解你究竟做了哪些工作，是怎么做的，研究调查的对象又是谁。第二个原因是，读者了解你的研究方法才能对你研究工作的质量进行有效评估。比如，如果读者发现你在做关于业余爱好的调查时只访问了周六下午正在逛街的人群，那么读者就有理由认为，诸如爬山之类的爱好被你严重低估了。

某些诸如心理学之类的学科，方法部分一般有严格的学术规范和固定的写作模式，以至于它（a）极其简洁并且（b）无法被非专业读者理解。使用这类学术写作模式有利于向审阅人传达正确的信号。举个例子来说，如果审阅人读到类似这样的句子：”以对抗平衡法进行完全受试者内设计兀它就能暗示审阅人，它的作者是对课题非常精通的专业人士。

实验性研究的论文必须有方法部分，其他类型的论文往往不包含方法部分。

### 结果部分

各个学科在这方面有不同惯例。如果是实验科学学科，论文的结果应该尽可能明确地、不加修饰地给出，最好不要有评论或讨论。出现一些解释和澄清是可以接受的，特别是在篇幅受到限制而使你不得不用简短的名称作为表格数据列的标题的时候。

好的结果
:   * 足够多的表格
    * 表格设计和排列有逻辑
    * 表格看上去整洁美观
    * 数据合计没有错误

不好的的结果
:   * 表格太少或太多
    * 表格排列混乱，读者看不出每个表格说明的结果
    * 表格看上去粗糙，不整洁
    * 数据合计有问题

### 讨论部分

因为某些原因，往往很难从讨论部分看出论文作者对专业知识技能的掌握是否过硬。这可能是因为，即便是缺乏经验的研究员，也可能在绝望中生出灵感，编一些精彩又可信的故事来解释他们在研究中的发现。

合理地使用技术术语和引用相关文献在讨论部分仍然奏效；空洞的、故作玄妙的用词，宽泛非专业性的知识，以及引用过时的参考书（硕士论文更容易犯这个错误）都是应该避免的。在一篇组织严密的博士论文中，讨论部分的结构一般会与引言和结果部分的结构相对应：引言中提出问题，结果部分用表格回答问题，讨论部分讨论问题的答案。

### 结论

结论通常还包括关于不“将来研究”的部分。结论应该对引言中提出的问题给出一系列清楚明确的回答。这些回答应该由结果部分（如果是实验科学学科的论文）的数据以及讨论部分（每一类论文都必须有）的内容作为依据。

学者们常常利用将来研究的部分为自己在未来的研究领域抢得一块地盘。有经验的研究人员往往会在这个部分简要描述自己未来的研究计划和课题，有经验的读者能清楚认识到，到论文发表时，它的作者可能已经花了一年的时间在新课题的研究上了，所以自己也就没有必要草率地往那个研究方向上努力了。

### 批判性反思部分

有的学者喜欢在论文中包含批判性反思这个部分。在这个部分里，作者思考自己在研究过程中取得了哪些收获，吸取了哪些教训。别的学者认为这样的做法说得轻一点是做作的自我迷恋，说得重一点是不必要地暴露自己的弱点，而且还触犯了第三条黄金法则（不要惊慌失措而在压力下吐露真相）。赞同和反对的双方都有自己的道理。

有时候，科学硕士论文必须包括批判性反思部分。如果你是一名正在攻读科学硕士学位的学生，而你将来要写的学位论文又必须包括批判性反思部分，那么你就没有选择权可以完全忽略这个部分。然而即便在这种情况下，你也不用过于担心。以下的两个例子或许可以帮到你。

::: {#exm-neg}
# 反面教材

我现在意识到我的调查问卷设计得很糟糕，如果可以重来的话，我会在设计问卷上多花一些精力。
:::

（潜台词：我是一个彻彻底底的业余人士，懂得很少也不自信；我一无是处。）

::: {#exm-pos}
# 正面教材

如果将这里谈到的粗集理论（rough set theory）分析与劳施（Rosch）提出的边界模糊的典型集员概念（prototypical set membership with fuzzy boundaries）相比较，可能会产生有意思的结果。
:::

（潜台词：我放弃使用古老枯燥的内容分析法，而选择使用了最高端的、很少为人所知的数学方法分析我的调查对象的类别。同时，我对另一门学科的另一种完全不同的、同样极少为人所知的分析方法也很熟悉。我不是一个轻易暴露自己弱点的人，我也不打算在这篇论文里暴露自己的任何弱点。）

在上面给出的那个正面教材中，我们可以看出，自信的信号过于强烈也会带来潜在的危险。所以在使用这类方法时也要谨慎。

### 大量阅读

你需要进行大量的阅读。你要读的书包括关于自己所学学科的（这样你才能牢固地掌握这门学科），还包括关于其他学科的，这些学科有的可能和你的专业有关，有的则可能看上去与你的专业完全没有联系。很大部分的优秀研究成果都是来源于看上去亳无关联的领域之间的交叉综合。

在你自己的学科领域，你的阅读应该有深度、有广度、有时间跨度——和你选择的研究领域有关的文献你应该深入地了解，其他相关研究领域内的文献，以及你自己的领域内所有过去进行的研究，你都应该有一个大致的把握。与你自己的研究课题相关的所有学术作品，包括最具专业性的学术期刊文章，你都应该仔细阅读。而其他领域的书籍，你可以挑选个别章节来读（还要注意书的层次——为大众编写的畅销书完全不用考虑；教科书，除了亨有极高声誉的，其余都没有太大意义。）

### 终身读书的人有哪些读书习惯

* 持久稳定地阅读。读书的真谛不在于一口气念很多书，而是在于始终保持一定的阅读量。在这方面，乌龟策略胜过兔子策略。
* 身边常带着书——利用等地铁的十分钟，等导师的时间，讨论会间隙，或吃饭前的片刻来看书。
* 厕所里也放着论文。
* 将参考书目摘要汇集起来，并及时更新。
* 每天腾出一个小时作为固定的读书时间。很多人都把读书作为早晨的第一件事。去办公室之前先在图书馆待上一小时。
* 书和论文都要看。
* 很多优秀的读者都对读书着迷。他们希望在阅读一个新的领域时有一种是“完整”的感觉。他们会是“筹划”全面阅读某些
重要作家的作品。
* 所有的论文复印件都有详细的引用文献需要的信息，包括文献的国际标准期刊号，国际标准书号以及页码。
* 很多真正的读书人会在一天中留出多于一个的读书时段——比如早晨读技术类的书，晚上读哲学类的书。
* 每晚睡前读上一个章节，不管自己有多疲倦。
* 参加会议讨论时随身带着会议录，在讨论过程中做笔记和摘要。
* 即使碰到一篇枯燥乏味的论文，也要浏览全文，了解大致内容。
* 动用你的人际关系网络来帮你筛选阅读材料，以确保自己读的书都是值得一读的。
* 加入（或成立）一个阅读小组，或找一个读书伙伴。
* 费曼是（Feynman）这样说过：读难懂的书时，如果遇到读不下去的地方，就从头开始读（这样你就可以把之前读过的章节再复习一遍，纠正积累下来的，又因为隔了一段时间而得到了强化的各种误解）。
* 隔一段时间再读也可能对你有帮助：先快速地浏览一遍，然后把它放到一边，过一段时间后再仔细地阅读它。

### 使用文献中的材料

给予别人肯定永远不会使你蒙受损失。事实上，你很有可能因为这方面做得好而得到别人的尊敬和信任。

剽窃
:   不同文化对剽窃的定义各有不同，但你的论文是否有剽窃行为将按照英国学术界对剽窃的定义来判断。英国学术界对剽窃的定义是很严格的：剽窃是指间接或直接地使用别人的想法、语句或材料，而不对此进行指明。

规则很清楚：

* 你使用的任何想法、语句或材料，如果有确定的来源，你就必须指出这个来源。即便你用自己的语言表达（重新陈述），你也应该指出原话的出处。
* 如果你一字不差地引用了别人作品的某些部分，必须使用引号，并指出出处。

让我们把话说清楚，剽窃是学术上的自杀行为。在英国的学术圈，剽窃被认为是是“致命的罪行”。如果你的论文出现了剽窃，你一定会被判不合格。如果你准备在期刊上发表的文章出现了剽窃，你的文章一定会被退回来，你本人还会被列入黑名单。所以如果你对使用的材料和信息有任何怀疑，找出它们的来源，指出出处。

如何引用
:   在作者通过使用文献可以传达很多东西。其中有一些是关于论文内容的（工具性使用），而另一些则是关于他们自己的（表现性使用）：

    * 建立你的权威性；
    * 引用你自已发表过的文章；
    * 覆盖面——能体现出你熟悉学术规范的要求；
    * 深度——能体现出你掌握了那些最不为人所知的文献；
    * 在排除你不想涉及的领域同时，指出你是了解这些领域的；
    * 表达对审阅人的尊敬；
    * 体现你研究问题的合理性；
    * 体现你研究方法的合理性；
    * 体现你数据分析的合理性；
    * 提供一个理论框架或视角
    * 证实你的研究发现。

思考以下问题：

* 如果你引用的文献是在1925年出版的，这说明了什么？
* 如果你的参考文献涵盖的主要是书籍，这说明了什么？
* 如果你的参考文献只涵盖了3名重要学者的作品，这说明了什么？
* 如果你的参考文献只涵盖了最近两年内发表的论文，这说明了什么？
* 如果你的参考文献中有5成是你自已发表的文章，这说明了什么？
* 如果你引用的文献总是成群出现（比如，斯邦吉1982；布鲁戈1998；格鲁莫2002），这说明了什么？

现在尝试以下的做法：

* 阅览一些出版了的学术论文。
* 在这些论文中出现了多少处引用？
* 这些引用是怎样布局的？
* 第一处引用是在哪儿出现的？
* 引用的文献有哪些种类？标题是概括的，还是具体的？
* 这些参考文献是何时出版的？作者是谁？
* 再看一看论文的讨论及结论部分。
* 在这些部分里出现了几处引用？
* 是在什么情况下出现的？
* 它们与背景介绍或引言部分用到的参考文献是相同的吗？

### 参考书目不全

你坐在图书馆里，两年漫长的博士生涯已经过去，你的论文课题是对马克思主义的评论。然面你此刻为了换换脑筋，正在读一本与论文课题毫无关联的书。忽然你读到了以下这段话：

> 经典马克思主义理论的一个严重缺陷，正如麦凯（Mackay）关于这个问题的著作中明确指出的一样，是马克思是在系统理论（system theory）出现之前，甚至是在确定性博弈理论（deterministic game themy）出现之前完成他的著作的。麦凯将马克思的思想放到了这样的理论框架之中，那就是系统优化（system optimization）与通过多目的随机博弈理论（multi-goal stochastic game theory）实现的次系统优化的对抗。这种做法综合了涉及隐性行为的可能性理论，并为可以被称为要“关德数学”的政治理论莫定了坚实的基础。

在查阅百科全书和因特网，了解其中某些技术术语的含义之后，你意识到，你眼前的这段文字不仅暗示着一种有体系、有根基的马克思主义评论的方向，更预示着一个有体系、有根基的后马克思主义理论的可能性。这个理论如果产生，将在政治、经济两方面都具有重大意义。你意识到你先前的论文思路可能是错误的，所以你试图在参考书目中找到更多关于麦凯著作的信息。然而在那本书的参考书目中没有提到麦凯的著作，麦凯也没有作为合著者出现在任何一本列在参考书目中。除了这段话，书的其余部分也再没有提到麦凯这个人。你只好在图书馆的数据库里进行搜索，然而结果正如你所担心的那样，没有一个搜索到的麦凯与上面这段话的形容相符。你真恨不得要把那本书的作者，那个遗漏了一条关键参考书目的人给杀死。但同时你又希望能从书的作者那里了解一些有用信息，然而经过一番搜索，你发现作者已经在几年前去世了（或许是与你一样发现他遗漏了那条参考书目的学者杀了他）。

你现在面临着一系列的抉择。你是继续沿着原来的论文思路走（不管这条思路是否有致命的漏洞），还是花上好儿年的时间去查找那条遗漏了的参考文献信息？你会因为原先的思路不对而放弃它吗？你会向邪恶的一面屈服，将麦凯的思想剽窃过来，假装这是你自己的天才创意吗？如果你这么做了，你会不会噩梦缠身，在梦中你的导师在答辩前将你介绍给一位叫麦凯博士的校外评审人呢？

这可能是一个极端的例子，但很多研究人员都遇到过类似的情况，他们在另一个完全不同的学术领域中发现了一部对他们自己的课题研究有重大启示的作品。这种情况我们也遇到过。由于作品的作者没有给出足够充分的参考文献信息，他们不得不花上数月甚至数年的时间去寻找作品引用的相关文献的出处。这就是为什么参考书目受到学者们极大重视的原因。

### 文献回顾（literature survey）和文献综述这（literature review）有何区别？

在研究过程中，学生对文献的利用有一个不断成熟的过程。这个过程与研究问题不断形成、完善的过程是同时完成、互相对应的。过程中的几个阶段在表2中已经展示出来了。

所以，文献回顾与文献综述的区别在于前者是做汇总，后者是做批评。在理想情况下，做完研究后，学生应该已经形成了自己的“批评的声音”。论文中的文献综述部分应该是从作者的角度去理清文献的脉络。如果文献综述结构清晰，有一定的批评性，那么到最后，研究问题就会自然而然地这“浮出水面”，它应该被看做是文献综述的“不可避免的”结果。

### 做一份带说明的文献目录（annotated bibliography）

核心文献库
:   有建树的研究人员拥有的一样东西是对相关文献的不断更新的知识。他们中的大多数人都有这100到150部核心文献构成的储备，他们可以随时将其中任何文献调出来使用。这个核心储备是从他们读过的成百上于的文章和书籍中挑选汇集起来的。有了这个储备，研究人员就能将自己的学术思想放置在一个体系之中：这个体系包含了所有领域内的主要思想派别和所有重要的研究人员，并提供研究模型和样本。当然了，储备必须更新才能完善。

    博士生阶段学习的一个部分是形成自己的核心储备。编制一份带说明的文献目录为获取核心储备提供了一个有效机制。同时，通过记录核心储备以外的主要文献的信息，它又是核心储备的有效补充。带说明的文献书目是有用的研究工具。这个工具是你个人使用的，所以你可以按照你自己的思维和习惯去设计它。

| 刚入门的学生               | 练习一段时间的学生 | 练习更长时间的学生               | 完全熟练的学生                 |
|----------------------------|--------------------|----------------------------------|--------------------------------|
| 知道哪一个研究领域         | 知道哪一个研究主题 | 知道什么是研究问题               | 知道什么是研究证据             |
| 阅读寻找已知的内容         |                    |                                  | 阅读了解什么是还不知道的       |
| 调查研究、收集信息、写报告 | 组织信息           | 选择与研究问题相关的信息         | 评价信息（质量和差距）         |
| 思考如何组织资源           | 思考如何区分问题   | 思考关于这个问题什么是已经说过的 | 思考关于这个问题什么是没有说的 |

: 学生利用文献的发展过程 {#tbl-lit-usage}

说明应该包含哪些内容
:   最少应该包括的内容：

    * 参考书目的基本信息（读者要找到这部文献必须知道的信息）；
    * 你阅读该文献的日期；
    * 你认为它在哪些方面是有趣的／重要的／让人不解的，将你的感受记录下来。你的笔记不应该抄袋原文献的摘要部分，而应该是你自己的批判性思考。它可以是非正式的、不符合语法的，甚至是偏激的，只要它表达出了你想表达的意思就行。如果你在重读某一文献时有了新的感受，那么应该对笔记进行补充——但即使你改变了你的观点或看法，也一定要保留原来的笔记。

    它能包括其他一些有用的信息，比如：

    * 文献来源（是复印稿、图书馆藏，还是个人收藏？）；
    * 关键词，最好是不同类型的关键词；
    * 后续研究要用到的参考文献；）
    * 你是怎么发现某部文献的（比如是谁推荐了它，或引用了它）
    * 与某部文献相关的其他文献信息；
    * 有关作者信息的摘要。

学术训练
:   保存制作带说明的文献目录是一种学术训练。要养成这种训练的习惯，最有效的办法是在阅读文献的同时就做记录，并在记录完成后再开始阅读新的文献。如果你没有及时记录，你就会不得不试图重新拾起以前读过的东西，这样做的难度会大得多。因为记录参考文献是耗费精力的一笔“支出”，又因为记录的目的是为了更有效地使用文献资料，所以最好将每部文献的摘要精简到一页左右。

    不要删除以前做下的文献记录。“废弃物在”可以重新分类或单独保存，某一年的“垃圾”可能会成为下一年的“宝藏”（反之亦然）。同时，保留分类变动的记录是很有意义的，它的一个做法就是列出你现在使用的所有类别的在“定义”。在对分类进行调整之后，不要丢弃原来的分类方案，而是应该将它保存起来，作为记录的一部分。

    这种训练的目的是要持续性地积累你阅读和思考的记录。

文献目录的其他好处
:   * 它能帮助你回顾你的思考过程；
    * 它能反映出你的阅读和思想是怎样不断成熟的，你是怎样一步步认识到某些问题的重要性的，又是怎样一步步完善你的阅读记录的；
    * 当你看到一条参考书目却记不起那部文献的具体观点时，摘要能给你关键性的提示；
    * 当你在答辩前重读某些文献，产生了与以前不同的理解时，你以前做下的笔记会对你很有帮助。

    文献目录可以帮助你有效地规划你的阅读，并使你能够充分地利用丰富的文献资源，如果仅靠记忆力，你能支配的资源就会有限得多。要牢记：

    * 文献目录能使你在拥有一个在“死板的”、一目了然的文件归档系统（比如按作者姓名的宇母排序）的同时，进行分类、再分类和便捷的搜索；
    * 文献目录可以防止你重新阅读那些没有价值的、只是名字有趣的文献；
    * 文献目录可以帮助你记录文献的装帧形式和所在地。

方法
:   记录参考文献的方法多种多样。最普遍的两种形式是卡片分类和电子数据库。

    卡片系统的样本（来自萨丽在·芬舍）

    * Kenneth 0. May (1973) Bibliography and Research Manual of the History of Mathematics. University of Toronto Press. (particularly pp. 2-27).
    * Robert M. Prisig (1991) Lila: An Inquiry into Morals. Bantam Press (particularly pp. 22-9).

    文献管理软件

    * Papyrus: http://www.rsd.com/
    * ProCite: http://www.risinc.com/
    * EndNote: http://www.niles.com/

    许多人不使用这些文献管理软件，他们偏好使用数据库、表格和在Word文档等。很多有效的参考文献可能只是一个较大的文本文件而已。
