# 论文类型

论文有不同的分类方法。但很少有写作方面的书对这些方法加以介绍，它们通常被看做职业技能，并且是个人选择的事情。这里描述的分类是一个十分标准的分类，其中一些论文类型是十分正式的（如期刊中的“评论文章”这一类型），但其他的论文类型如“方法导向型论文”（method-mongering paper）则是不太正式的。

## 数据导向型论文（Data-driven papers）

这是大多数人最容易想到的一种论文类型。数据导向型论文集中描述和讨论数据（而不是描述和讨论收集数据所用的方法）。这类论文的代表包括报告调查结果的论文和报告正式试验的论文。

数据导向型论文因为儿个原因很重要，并且使用“学徒”研究模式的研究者将在他们的研究中至少安排一项数据导向的研究，以证明他们知道如何做这些工作。

如果你的论文的中心是数据，那么你需要好的数据。这意味着数据可靠并且有趣。“可靠”的意思是：样本的大小、质量和代表性等应该达到一个毋庸置疑的标准。研究人员中的新手（有时候不仅仅是新手）常常会担心样本的大小是否达标，被调查对象是否足够多。他们担心的另一个问题就是样本的代表性问题。代表性是他们喜欢考虑的问题，因为任何人，只要有一把舒适的坐椅和一点常识，都能够不费劲地想出各种理由来质疑样本是否具有足够的代表性。然而一旦问卷寄出（问卷是搜集数目庞大、可信度值得怀疑的数据的惯用方法），这种种担忧都会让位给怎么方便怎么来的原则。所以如果你正在进行这方面的工作，你有必要了解统计学的知识。

刚开始从事研究工作的人往往会忽视，得到有趣的数据是很重要的，这一点经验丰富的研究人员是决不会忽视的。新手们不重视这一点的原因可能是，他们在收到调查对象的问卷回答之前，往往不会去设想采集来的数据会是什么样子。由于采集来的数据没有新颖之处，他们研究结论的枯燥乏味也就可想而知，所以很快淡出公众视线之外。对于一个有经验的研究人员来说，去野外钓鱼还不如钓养在桶里的鱼（也就是说，数据能够吸引人的儿率必须足够大，才值得进行大规模的数据采集）。

能够吸引人的研究结果往往是让人吃惊的，同时又是有用的。这个结果应该有一个基础坚实的样本作为依据，样本数据必须足够可信，以至于可以将其作为未来进一步研究的基础。

你怎么判断你的研究领域是有鱼的桶（也就是在一个值得采集大量数据的领域），还是在一个没有鱼的空池塘呢？这时候对理论的透彻理解非常重要，因为它可以引领你去预测与直觉背道而驰的发现。另一个有用的办法就是在进行其他研究的时候经常留意有什么东西可以产生有意思的效果。

一篇经典的、建立在数据基础上的研究论文能为其作者带来声誉。然而大多数以数据为基础的研究论文都无法有新突破。你必须拥有可靠的、有趣的数据才能为这类数据导向型论文建立起在学术界的声誉。

## 教学指导性论文（Tutorial papers）

教学指导性论文是描述一种研究方法并解释如何使用这种方法的论文。这类论文很有价值，然而学术期刊往往不发表此类论文，因为原创性研究是学术期刊的精神所在，而教学指导性论文通常不涉及原创性的研究。但是如果你发表了一篇经典的、论述某种研究方法的教学指导性论文，这篇论文就会在未来几年里一直被人们引用。

## 方法导向型论文（Method-mongering papers）

这类论文同样描述一种研究方法，但目的是为了指出这种研究方法应该得到更广泛的应用。所描述的方法可以是原创的（比如由作者本人发明的），也可以是在别的领域里已经发展成熟，却还未在作者想要将其推广的领域内得到充分重视的研究方法。

这类论文与教学指导性论文会有重叠，但方法导向型论文并不一定要写成教学指导性论文的形式。一种很普遍的做法是，在论文里论述某种方法为什么可以应用到研究者本人的领域里，却不详尽地描述这种方法，而是在论文中列出讨论这种方法的教学指导性论文或教科书供读者查询。

方法导向型论文有一个好处，那就是如果你对某个其他领域的研究方法已经相当熟悉，那么你可以很轻易地写出一篇方法导向型论文来。你所需要的只是几个有说服力的案例，证明将该方法应用到你的领域内可以解决传统研究方法很难解决的问题。你所需要的样本数目也不必太多，因为少扯的样本（甚至是一个有说服力的例子）也同样可以有效地证明你的观点。

## 意识唤醒型论文（Consciousness-raising papers）

这类论文并没有它听上去那么玄妙。它的目的是为了唤起人们对某些问题的意识，因为这些问题在研究领域里还没有得到充分的重视。这些问题往往涉及其他领域的方法和概念在研究者所在领域内的应用。

意识唤醒型论文如果写成功了，可以吸引很多注意力，并改变整个领域的观点；如果写得糟糕，那只会给作者带去自大、夸夸其谈的坏名声。我们可以采用学术研究惯用的试金石来鉴定这类论文的优劣，那就是它有没有给读者带去新颖有趣的工具。比如，如果一篇论文告诉我们硬科学（hard sciences）的研究方法不能直接用于研究软科学（soft science），我们也许会觉得这没错，但我们并不能从这个结论中得到任何真正有意义的东西。但如果一篇论文告诉我们博弈论可以为演化生态学（evolutionary ecology）提供数学基础，这给读者带去的启示意义就好像是给了一个小孩一把玩具仓库的钥匙。同时也使约翰·梅纳德·史密斯[^jms]（John Maynard Smith）成为另一个全新领域的开创人。

[^jms]: 演化生物学家，将博弈论应用于演化，著有《演化与博弈论》（*Evolutionary and the Theory of Games*）。

博士一年级的学生往往喜欢抱怨他们的领域忽视了很多重要问题，但他们却不喜欢考察事实，查清楚这些抱怨仅仅是一年级新生的口头语，还是的确有一些重要问题被忽视了。有经验的研究员在这方面有很大的优势，因为他们（a）听了很多一年级学生的意见， （b）有值得信赖的同事帮助他们判断学生的意见是否有道理，所以他们可以在写这类论文前有成熟的考虑。

## 理论性论文（Theoretical papers）

理论性论文有很高的威信。这类论文讨论的是理论问题，比如象征推理（symbolic reasoning）的内在局限性。它可以产生巨大的影响力。发表了的理论性论文通常出自某个领域的权威之手，其中很重要的组成部分是文献评论和方法论（不引进文献和方法论就没有可能攻克艰深的理论问题）。这类论文中那些无法发表的通常是缺乏经验的新手写的。他们在写之前没有充分地阅读文献，这就好比是在学习新事物之前没有读相关的FAQ（常见问题）一样。我们的建议是，在你不能确认自己能够胜任，或者拿不出证据来证明你的能力之前，不要尝试写理论性的论文。

## 评论性论文（Review papers）

每隔差不多十年的时间，一个领域内总会有某些人决定，是时候写一篇论文，来考察自上一篇评论性论文发表以来领域内又取得了哪些重要进展。这些人于是会审阅过去一段时间内发表的所有主要论文以及很多其他次要论文。这项任务极其庞大，涉及阅读和评估数以百计的论文和书籍，并且要从中找出若干重要主题并在论文中总结这些主题。

评论性论文对普通读者来说很有价值，因为它的信息很完整，包括概述和关键的资料文本，为读者提供了进人某个领域研究体系的快捷渠道。

评论性论文的作者通常是对某个领域了如指掌的人，他们往往已经阅读了所有的相关文献（并且很可能自己也写了不少）。然而也有例外，这种例外情况可以为你所用；如果你的博士论文的文献综述部分写得很好，那么这部分理所当然可以作为评论性论文发表。实际情形是，大多数正在写博士论文的学生不是早已经厌倦了文献综述这份差事，就是害怕被告知忽略了关键性的文献，所以他们对写评论性论文都没什么兴趣。

## 概念展示型论文（Demonstration of concept papers）

概念展示型论文与很多其他类型的论文都有重叠，尤其是方法导向型论文。概念展示型的论文是为了向读者展示一个特定的概念（通常是一种方法，但也有例外——比如也可以是一种概念性框架）是可行的、有用的、有趣的。这类论文在申请研究经费时很管用。

如果你很清楚你要论证的是什么．该用什么方法去论证，那么只需要来自一个样本的一组数据就可以完成一篇概念证明型的论文。写这类论文最难的还是要找到一个好的概念。

## 以上几类论文都会使用到的研究方法

* 正式实验（Formal expeciment）
* 田野实验（Field experiment）
* 案例研究的（Case study）
* 行动研究（Action research）
* 调查研究（Survey）
