# 写作

如果你是一个经验丰富的学者，有人试图说服你收某个你从未听说过的人做你的博士生，那么你想要了解的第一件事就是这个人的写作能力如何。写作能力指的是：有能力用质量好的、学术性的语言写作，最好可以根据不同情况用不同风格写作，从学术期刊文章到为争取可能的资助人而写的公开信，都应该能够应对。如果那个学生的写作能力较差，那么极力说服你收那个学生的人在与你的交涉中就会处于绝对的劣势，因为任何理性的人都不会对指导一个写作能力较差的博士生太感兴趣。值得指出的一点是：质量好的学术性英语和正式的符合语法的英语不是一回事。我们遇到过很多学生，他们能写质量非常高的学术性英语文章，但他们的母语并不是英语，他们的英语语法在某些方面还存在着错误。相反的，很多母语是英语的学生，学术写作的水平却令人担忧。

那么，高质量的学术性英语究竟是什么样的？它又为什么不同于正式的英语语法？这一章讨论的就是这个主题。我们将会谈到如何建构写作框架，如何从文章的字里行间传达正确的信息，在遇到诸如写不下去的情况时又该如何应对。

这一章与第六章关于阅读的讨论有很多重叠的内容，所以如果你正打算着手写作，我们建议你可以再读一遍[阅读](#section-6)这一章。

## 学术期刊论文

虽然这部分讨论的重点是学术期刊论文，其中很多原则也同样适用于会议发言稿或其他类型的准备发表的作品，比如书的章节。我们之所以选用期刊论文作为讨论的对象，是因为发表期刊论文一般被视为你已经是一个真正意义上的学者的标志一人们普遍认为，除学术期刊以外的出版物在选取文章和质量监控方面参差不齐，学术期刊却总是独一无二、有洞察力的。这种看法当然并不完全正确，但可以作为一个有用的衡量尺度。如果你有志于学术事业，希望能给你的简历增光添色，你就更应该重视学术期刊论文的写作。

导师们对学生为学术期刊写文章有不同的看法。有的认为这是一件好事，并鼓励学生去做；有的认为这是一件坏事，不鼓励学生去做；还有的认为在某些情况下这是一件好事，在某些情况下却未必（如果一个学生的博士论文下周二就要交稿，他就应该把每一分每一秒的时间都用在博士论文上，而不是去写期刊论文）。

所以，在写期刊论文之前首先要与导师沟通，确认在你的特定处境下进行期刊论文写作是否是明智之举。如果导师持否定意见，并且给出充分理由，那么你就应该听取导师的意见；如果他们持赞同意见，并祝你好运，那你就可以计划下一步该怎么做了。

### 在哪里发表

要考虑的第一个问题就是在哪里发表．这涉及以下几方面的因素：期刊的声誉、读者群、你选的课题是否适合该期刊的侧重点、该期刊接受投稿的比例是多少。一个基本战略是挑选最有声誉的、同时又比较有可能发表你的文章的期刊。这就又涉及如何预测可能性的问题。与知情的内行坐下来喝一杯咖啡是一个很好的策略。

考虑了以上这些因素之后，你需要做一些基本的功课，而忽视这些基本功课的人在所有有志成为学者的人群中占惊人的比例。第一项功课就是阅读你所选的期刊为其投稿人写的投稿须知。投稿须知一般会印在期刊上，发布在期刊的网站上，或者从期刊的编辑那里得到。从投稿须知中，你能了解到文章的字数限制、图表的制作流程，以及你需要寄出的论文复印件的份数。这些规定都是有意义的。如果你遵守这些规定，编辑对你持正面看法的可能性就会高些。无端地和编辑对着干是愚蠢的。以下我们将会解释每一条规定的设定目的，并给出提高投稿命中率的若干办法。

期刊的侧重点非常重要。期刊必须有侧重点，因为研究论文的数量实在太多了——即使是专业性很强的期刊也会因为版面限制而不得不拒绝极大比例的优秀论文。（期刊编辑每年编辑多少文章受页数预算控制，于是一年中能得到发表的文者也因此受到限制。）所以．你应该确保你写的文章内容符合你选定的期刊的侧重点。如果你不确定，可以联系编辑咨询相关问题（要注意礼貌）。学术期刊编辑与商业性刊物的编辑不同，他们在各自的研究领域通常扮演着举足轻重的角色，他们将最终决定你的论文是否为期刊所接受。如果你很有技巧或很走运，编辑可能会喜欢你论文文字背后的思想，并会在怎样表达这个思想方面给你有用的建议（比如哪个主题需要强调，哪个主题需要低调处理）。这些建议很重要，值得你严肃认真地考虑（但你还是要记住，听从建议并不是成功的保证）。

### 关于递交材料的要求

你的递交材料应该包括一封附信、若干数目的文章原件、一份电子文档（如果要求的话），以及说明材料中规定的任何其他材料。附信应该简洁、有礼貌。编辑应该可以从中了解到，负责与他联系的作者是谁（如果文章由多人合著），以及这个作者的联系方式。文章本身应该符合投稿须知的要求。接下来几段文章将描述投稿须知中的一些规定，并对它们的重要性进行解释。

由于页数限制的原因，字数限制是很重要的一个方面。编辑可能需要在刊登一篇字数较多的文章还是在一期中挤进两篇字数较少的文章中做出选择。他们会很注意文章的页数多少。编辑会根据你文章的字数（包括图表）来计算版面数，而不是根据你的文章打印稿的纸张页数。所以调整字体和页边空白骗不了编辑。

你的文章通过了这第一道检验之后，编辑会将原件寄给审阅人，以征求他们的意见。这方面的流程各个期刊有所不同。大多数会寄去纸样，因为审阅人往往喜欢在纸上作注，而电子文档意味着他们还要将论文打印出来，而且论文的格式和字体还可能不符合他们的要求。编辑的通常做法是，他们会让投稿人提供足够的原件供审阅人使用，另外再提供一份原件供编辑自己归档保存。如果有两个审阅人，编辑会要求你寄出三份原件。我们曾经遇到过一份期刊，要求投稿人寄出八份原件。如果你寄出的原件数目不够，编辑就不得不替你复印。他们可有很多比复印你的文章更重要的事要做，所以寄出规定数目的原件是很有必要的。有一些期刊要求投稿人寄电子版的文稿。如果你寄去的电子文档是用Grunt2004格式或其他某个不适用于他们所使用的系统的格式写的．那他们就不可能对你的投稿感兴趣。你可以为自己辩护，说自己使用的格式在技术上比其他人使用的格式更加先进，但编辑们对你的辩解基本上不会感兴趣。同样的，如果你向一家要求用原件投稿的期刊寄去了一份电子文档．那么编辑们可能也不会考虑把你加到他们的通讯簿上去——电子文档原则上说是个很不错的主意，但现实与原则有时很不一样。

有些期刊使用双重匿名的评审（double-blind reviewing）方式，有些不采用这种方式。双重匿名的意思是：审阅人不知道文章作者是谁，你也不知道审阅人是谁。为了这个目的，投稿须知中可能会要求你将你的姓名和联系方式单独写在另一张纸上，与论文分开，这样寄论文给审阅人之前，编辑就可以将这页纸取下来。编辑可不愿意因为你在论文里留下了不应该留的姓名，而把半个上午用在涂修正液上。

审阅人可能会在你的稿件上划划改改，也有可能不那么做。然而文字编辑却一定会在你的搞件上留下修改记号。有些稿件看起来非常干净（也就是错误很少）以至于仅凭这一点就给编辑们留下了深刻印象。然而大多数的稿件都需要进行较多的文字编辑，其中的错误往往出现在对参考文献的引用上（比如引用的文献在论文中标注的出版年份与在参考书目中标注的出版年份不一致）。因为这个原因，文稿必须是两倍行距的，以便文字编辑以及审阅人作注和修改。如果你寄出一份单倍行距的文稿，那就说明你是个业余人士，根本不了解情况。

投稿须知还会规定．你投寄出的文章不可以是已经向其他出版机构投寄了的。如果你同时向两家或更多的期刊寄出同一篇文章，并被发现（可能性很大，因为一个领域内的审阅人数量有限），那么你就会被这些期刊列人黑名单（也就是永远不能在这些期刊发表文章）。这么做的原因是，向多家期刊投一篇稿件会浪费所有相关工作人员的时间，而且如果两家期刊同时发表了这篇文音，就会涉及版权等法律问题。编辑和其他人一样讨厌被法律纠纷缠身。投寄不同的稿件，或者阐述同一个课题的不同方面，这些做法是被允许的，但你还是要注意稿件间的差异性是否足够大——如果两篇稿件看起来很相似，编辑们很可能会不赞同。

### 接下去怎么做

你寄出了文章之后，将会在某个时间收到来自编辑的确认信。编辑们是大忙人，所以这份确认信可能会等上好几个星期才到。随后你的文章就会转到审阅人的手中，他们可能会审阅你的文章，也可能将它搁在一边，不予理睬，甚至把它给弄丢了，这一来又是几周或几个月的时间。编辑会在审阅人完成审稿后的某个时刻对如何处理你的论文作最后决定。如果你很幸运，编辑会给出具体的修改意见，你的论文只要进行了相应的修改就能被接受。如果你不走运的话，编辑会在来信中附上审阅人的要求，你的论文必须满足审阅人提出的要求才能被接受。审阅人的要求往往非常模糊、晖嗦、费解，有时甚至自相矛盾。比这种情况稍好一点的情况是，编辑很干脆地拒绝了你的论文。你的目标应该是使被拒绝的论文数量达到一个合理比例。如果你的每篇论文都被接受，这说明你选择的期刊水平不够高，你应该去找声誉更好的期刊。

修改论文的明智做法就是要发挥主观能动性。列出要求修改的环节，系统地进行修改，并在寄第二稿时附上给编辑的信，在其中详尽清晰地告诉编辑你在哪些地方做了怎样的改动。这么做会大大便捷编辑的工作，他们可能就会因此对你产生足够的信任，直接接受你的文章，而不再将第二稿交给审阅人鉴定。如果你没那么走运，你的稿件将再次受到审阅人第二轮漫漫无期的考验。在修改论文方面听取有经验的同事的意见会对你很有帮助。

### 发表的过程

接受
:   如果你进入到这个阶段，你会收到一份编辑的来信或电子邮件，通知你论文将被发表在《尤毛鼠研究》（*Journal of Nude Mice Study*）或其他某份期刊上。编辑可能会要求你再寄去一些改动后文稿的原件和／或电子文档。

文字编辑
:   你的文章被接受之后，期刊的文字编辑将与你联系。文字编辑对你文章的学术内容丝毫不感兴趣，他关心的只是文章的外观。他的职责就是保证你的文章拼写正确、符合语法、标点符号使用无误、正文和表格中提到的数据是否前后一致。文字编辑在发现一些有出人或遗漏的参考文献信息、正文和表格中数据不统一等情况时，将寄给你一份需要你澄清的问题清单。典型的问题清单是类似这样的：“第8页第7行引用了史密斯1999，然而参考书目中显示的是史密斯1998，哪一个是正确的？”要回答这类问题可不轻松，你必须要再找出原文来核对。水平高的、经验丰富的研究员通常会在收到文字编辑来信的当天就对其所有疑问给予完整的答复，这种做法很受文字编辑的赞赏。新手往往做不到这一点，他们在核对原文的痛苦过程中将会更加深刻地领悟：为什么导师如此强调参考文献的信息必须记录准确。如果文字编辑花了大量时间来修改你的论文，你可能就要为这部分时间支付费用（文字编辑的时间可是不便宜的），所以少犯错误也是有经济效益的。

图表
:   图表方面常常存在一些问题，使投稿人和期刊编辑双方都不愉快。我们在这里把图和表放在一起讲，因为它们的问题很相似。由于某些技术原因，很多出版社的印刷商分开处理图表和文字，最后再将图表插入到文字部分，还有一些印刷商却不这么做。写给投稿人的投稿须知会清楚地告诉你应该怎样处理图表。很多期刊都会要求将图表单独列出，附在正文后面，并在正文中需要插入表格的位置上标出记号，注明表格序号（通常是空一行．在需要加入表格的确切位置上画一条线，注上“表格1在此”）。如果你违反规定，将表格写在了正文中，你不是被要求用正确的格式重写文章，就是要面对文章发表后极不整洁的版面效果。你的文章的文字部分将非常整洁漂亮，而夹杂在其中的图表却像在泥里浸过一样，与在同一期刊登的其他文章中整洁专业的图表形成鲜明的反差。你当然可以告诉编辑组，在这个电子出版时代，解决这个问题的技术含最最高的方法应该是使用图文混排的电子文档，但这么说其实是很不识趣的。你应该问问自己，编辑组选择了他们目前所使用的这一套出版流程是因为他们不知道有更先进的技术存在，还是因为可能有其他方面的，为你所不知的因素致使他们必须选择目前使用的技术。

校样
:   下一个关键阶段涉及校样。校样是印刷厂出的初印稿，体现了你的稿子最终刊登在期刊上时的视觉效果。由于技术和物流方面的原因，校样在出版前的最后一刻才出来，作者在收到校样后必须在一个规定的、极短的时间内完成核对，并将核对后的校样再寄到编辑部，从收到校样到再次寄出校样通常仅24小时到三天的时间。你可以考虑一下这种流程可能会引起的问题，比如你因为正在外地度假而没有收到校样，而碰巧校样上有一个后果严重的打印错误，让你看起来像一个笨蛋或学术上的江湖骗子，那你该怎么办？你还可以考虑一下你对修改核对稿件懂得多少，你是否能用合理的方式指出打印错误（比如如果你在校样上写上了这样的评语“这应该是‘24’，你这个白痴”，没想到这句评语也被刊登了出来）。校样寄给作者时，般还附有帮助作者进行修改的指导性内容。但是如果能在正式进人这一阶段之前不是那么紧急的情况下进行一些校样修改的训练，这将对你很有帮助（与往常一样，与一位有经验的同事坐下来喝一杯咖啡会很有用——他们可能会向你透露，哪位秘书在文字编辑和校对方面最为擅长，你可以向这些行家讨教经验）。如果你估计在你外出时可能会有校样寄到，你可以让你的同事帮忙留意你的邮箱。

其他相关注意事项
:   还有一些相关注意事项。首先，你寄出的复印稿必须是你寄出的电子文档的无差别打印版本。如果编辑组发现你做了改动，电子文档和原件之间存在差异，他们会极其气恼。第二点，在校对时不要对文章内容进行改动一只有印刷错误才需要更正。如果你擅自添了几个词，这在排版上会引起连锁反应，影响到后面儿页的版面效果，还会大大提高印刷成本。编辑们在改动的显和文章页数上都有预算限制，所以如果你擅自添加内容而使他们的这两项预算超支，他们会对你很不满意。

在这里还需要指出的一点是：文字编辑们其实是比较人性的，所以如果你有什么不明白的地方，可以打电话或发电子邮件给他们，与他们展开建设性的讨论。（他们一般总有紧迫的任务缠身，要与他们联系的话，打电话这种快捷的方式比寄信管用的多。）传真在交换局部修改意见时非常有用——你可以把自己的修改意见和说明标注在需要改动的文稿上，并将其传真给文字编辑。

这些工序都完成之后，你就可以将这篇论文加入到你的简历里，并等待（a）登着你文章的若干份期刊出现在你的邮箱里，（b）登着你文章的期刊出现在图书馆的书架上。有些期刊会寄抽印本（将你的文章单独辑印成册的期刊版本）给你；有些则寄给你多份刊登着你文章的期刊。你应该珍惜它们，虽然你很想把它们发给你周围所有的人，但要记住它们是你的资产，你在今后很长一段时间里都可能要用到它们。大多数的系都会要求得到你文章的一份拷贝存档，在大学研究评估（RAE）或类似评估活动中使用。抽印本比你文章的复印件对系里更加有用，因为系里的年报需要包含发表你文紊的期刊的国际标准书号以及页码等细节信息，抽印本或期刊提供这些信息，而你自己的复印稿则不包含这些细节信息。

最后一点：大多数期刊会要求你签署一份放弃版权的协议作为出版你文章的条件。英国作家学会目前正在这个问题上进行平静、礼貌而有效的抗议，有些期刊已经因此开始转变它们的政策。与此同时，你无需对版权放弃协议感到恐惧。如果你有疑惑，可以联系作家学会或咨询有经验的同事。作家学会将在很多方面帮助你，它还为其会员提供一系列服务（包括在作家与出版杜的合同问题上提供免费的法律咨询）。任何出过书或得到过正式的出书要约的人都可以成为作家学会的会员，会费也很合理。

关于期刊文章要牢记的主要几点是：

* 大多数文章都会被拒；
* 成功的学者已经把自己的脸皮磨得很厚了，失败的学者却做不到这一点；
* 评审人也是人，他们说话不客气或彼此意见不一致时，不要太介意；
* 成功的学者之所以成功是因为他们在经历中学习成长；
* 即便是成功的学者也有迈出第一步的时候。

## 学位论文的发表

这些指导原则是我们所贯彻的。它们不是完美无缺的，也不是绝对的唯一的真理。但你会发现把它们作为出发点是有用的。这些指导原则对于本科生、科学硕士生及博士生都适用。发表学位论文这方面的政策各个学校有所不同，所以如果你所在学校的体制与我们在这里提到的有差别，你也不用觉得惊讶。

### 开始之前

* 如果你和你的导师认为论文有发表的可能性，那你们就应该尽早在基本问题上达成共识——最好在投身于任何具体项目之前。如果在此刻达不成共识，以后也不可能达成共识。如果双方争执激烈，那么就有必要更换项目或合作伙伴。因为牵涉到知识产权，所以如果发表获得经济利益，双方在知识产权上达成共识将非常重要。
* 在将论文寄给哪份期刊发表这一点上达成共识。
* 在如果论文被拒将采取什么行动上达成共识。你不希望在论文被拒后出现这样的情形：合著人对论文稍加改动后独立地以他们自己的名义寄给其他期刊发表。一个解决办法就是事先选出一个合著人，如果论文被拒，这个合著人将在改进论文、将论文投寄给其他期刊的过程中承担主要责任，如果论文得以发表，他也就是该论文的第一作者。

### 著作权

* 著作权是在一开始就应该达成共识的问题。一般情况下，作者应该包括学生和导师，学生是第一作者。如果这方面达不成共识，就不用再走下一步了。
* 如果要发表的论文是由若干个研究项目汇编而成的，那么汇编人应该是第一作者。
* 必须是对论文作了大量贡献的人才能被列为合著人。如果只是一次给予建议的师生谈话（比如你咨询了导师以外的一名教职人员），这不能构成对论文的显著贡献。如果你想要就论文的某些部分听取系里其他老师的意见，你应该在事先告诉你的导师，以免产生误解和不愉快。

### 投寄以及修改

* 在论文寄出去前，所有作者和合著人都应该看过并同意终稿的内容与形式。
* 不要同时寄给多家期刊。这么做会被期刊列入黑名单。这种惩罚是有道理的：同时向多份期刊投寄文章可能使编辑在无意中触犯版权法规。同时它还会浪费编辑和审阅人的宝贵时间。这些人的工作压力已经很大，他们不希望有人再给他们带去不必要的任务。
* 如果论文在修改后可以被发表，那么所有作者和合著人都应该在第二稿寄出前得到机会发表自己的修改建议（比如每人都得到一份拷贝，并且每人都得到指示，必须在两周内对其给出评论和建议）。
* 所有的作者和合著人都应该较早地被告知出版事宜的进展（比如期刊编辑的决定）。

### 发表后

* 每个作者和合著人都应该得到至少一份论文抽印本。
* 所有作者和合著人都应该得到至少一份关于论文的评论性报道的拷贝。

### 发生纠纷的情况

* 在情况恶化之前积极听取相关人员的意见。
* 如果可能的话，将每个阶段达成的共识以书面形式确认——比如通过电子邮件确认著作权。

## 论文检查一览表

### 内容

* 你有明确的研究问题吗？
* 你证明了问题的有趣性吗？
* 你证明了问题的重要性吗？
* 你证明了答案不是平淡元奇的吗？
* 你的“叙述线索”清晰可见吗？你的论证清晰有条理吗？

### 将你的论文放到学术研究的大环境中去考察

* 你有没有参照现存文献来定位你的论文？
* 你的论文是否清晰地体现出，它是建立在什么理论基础之上的，它又在哪些方面对该理论作出了贡献？
* 你是否讨论了你研究的前提、历史和局限性？
* 你是否讨论了你的论文对未来研究的意义？

### 根据

* 你有没有依照学科要求清楚地给出根据？
* 你对数据的阐释与数据本身有区别吗？
* 你的结论有根据吗？
* 读者能否根据你论文的描述复制或模仿你的研究？

### 给予别人应得的肯定

* 你和其他合著人有没有就著作权以及作者排序达成共识？
* 你有没有给予所有作出贡献或提供帮助的人应得的肯定？
* 你的参考书目是否正确完整？

### 文献使用

* 你引用了最具重大影响的文献吗？
* 你引用了经典文献吗？
* 你引用了基础性文献吗？
* 你论文第一页上的引用达到了五处以上吗？
* 你仗用的文献的时间跨度是否是从开创某领域的研究到新进的研究发展？
* 你是否引用了一些特殊的文献，能体现出你了解超出某个课题标准文献之外的信息？

### 发表在哪里？

* 你决定了要在哪里发表了吗？
* 你查清楚发表的最后期限了吗（如果有最后期限的话）？
* 你阅读和遵守了投稿须知吗？

### 论文外观

* 你遵守了投稿须知的相关规定吗？
* 你论文中的表格和引用符合出版社的印刷风格吗？
* 你有没有检查单词的拼写？
* 你有没有使用合适的具有国别性的拼写习惯（英英拼写或美英拼写）？
* 你论文中的小标题对内容有没有起到明确清晰的指示作用？
* 你的论文外观格式是否符合你所在学科的学术惯例？
