# 写作结构

令大多数博士生担心的是他们要写的论文的“工程”之庞大。这很可能是他们这辈子写下的最长的作品。大多数学生因此产生恐惧情绪，这是可以理解的。然而事实上，你一旦学会了把一个大问题分解成若干个小块，这个任务就变得没有你想象得那么可怕了。这一章讨论的正是这方面的技巧。一篇论文包含若干个板块，也就是若干个章节，而每个章节又可以划分为若干部分，也就是若干小节。你将论文分解到这个层次之后，每次就只需完成几页纸篇幅的写作任务，一下子就好办多了。章的主题构成你的写作结构：普遍意义上的结构，以及具体涉及论文写作的结构。

在每一个学科领域里都发展成熟了若干发表作品的类型，每一类都有自己的标准结构。讨论论文类型的 @sec-paper-type 以及讨论阅读的 @sec-reading 都涉及了这一点。你应该了解和熟悉你所在领域发表作品的类型及其结构，在你自己的写作中使用这些标准结构，直到你熟练到脱离这种结构也能游刃有余的地步。

描述实证性工作的论文的一种有用结构是在引言部分提出一系列明确的问题，在结果部分给出相应的表格和数据，在讨论部分展开针对问题和数据的阐释和分析。这种结构能使读者（以及你本人）对你论文的逻辑和目的有一个清晰的认识。举个例子来说，你可以在引言部分提出三个主要问题，在结果部分用三个板块给出针对这三个问题的实验数据，最后在讨论部分分别展开三组讨论。这样的结构可以使问题明确化，也使问题的答案明确化。

## 成稿

如果一切顺利的话，你会在未来的某一天将你所有的研究工作和研究成果都写进最后的论文稿中。大多数人对此抱有强烈的负面情绪。这些情绪包括恐惧、困惑、绝望以及彻底丧失对整个课题的兴趣。如果你也有同感，不要担心：这些情绪是完全正常的，也是可以消除的。那么，你应该怎么做呢？

### 好的建议

从你想要得到的美好结果出发逆向思考。你想要得到的结果是：评审人在读完你的论文之后感到非常满意放心，于是可以坐下来看一集最新的电视剧，比如《吸血鬼猎人巴菲》（Buffy the Vampire Slayer）。你不想评审人读了你的论文之后担心或生气。怎么做到这一点呢？

你可以站在评审人的立场上，尤其是校外评审人的立场上来思考问题。如果你的声誉和可信度已经大到被邀请担任校外评审人，你一定也同时肩负其他重要职责，并且痛恨别人浪费你的时间。所以你在审阅论文时一方面不想妥协自己的高标准，一方面又想尽可能快地把这个任务完成。这两方面产生的结果就是你希望看到一篇毫无疑问可以通过的论文。你最不愿意看到的是一篇悬在过与不过之间，经过大量修改可能会过的论文：这样的论文意味着你将要为它花去大量的时间，如果学生还将修改了的稿件寄给你审阅，你可能会好几个星期都得不到安宁。那么，作为校外评审人你判断论文通过还是不通过的根据是什么呢？

基本的问题是，在一个适合于博士生水平的层次上，这篇论文是否对知识作出了原创性的贡献。如果你的论文满足了三个标准，那么每个人都能皆大欢喜。作为学生，你可以在论文中加人一些显示你良好判断力的语句来体现你已经达到了前两条标准（“原创性”和“对现有知识的贡献”）。如果你写了类似这样的句子“通过应用粗集理论，它扩展了本领域史密斯和琼斯（2002）的经典工作”，那么你论文的“原创性”就清晰地体现出来了：你的原创性就在于你扩展了史密斯和琼斯的研究。如果你写了类似这样的句子“这些发现对领域内关于这个课题的研究具有重大启示意义，这个课题的重要性之前一直被相对低估”，那么第二条标准“对现有知识的贡献”也就显而易见了。单靠这些语句本身是不够的，你必须要做出研究成绩。然而，研究成绩只有在论文中清晰地体现出来才能被人认可，否则评审人可能无法在一堆结构混乱的稻草堆里发现原创性那枚针，清晰的结构能更有效地体现你的正面自我判断。文中应该有两个独立小节分别讨论你的研究课题或研究方法的“原创性”和“对知识的贡献”两个方面。（这两小节的小标题一定要比较含蓄，如果直接写成“原创性”和“对知识的贡献”，会显得有点低劣。）

第三条标准（“是否体现了博士阶段应该具有的水平”）并不是单靠论文的某些局部体现出来的，它体现在论文从头到尾的每个细节里。如果在论文中提到自已发表过的期刊文章句以此暗示你的研究水平符合水准，这种把戏可能会取得预想的效果，但如果在论文答辩时以此来作为一个论据，那你可能就有麻烦了——评审人最多把它视为一个加分项，也可能把它理解为你理屈词穷后的最后一招。本书关于阅读和写作的章节在这方面能派上用处：评审人会透过字面意思去寻找深层次的信息，如果你能通过字面意思暗示正确的信息，那么双方都能皆大欢喜。这些信息大部分都体现在细节之中，单个细节似乎微不足道，但放到一起就很能说明问题。如果你使用了分类学来研究中学教育的社会融合问题，那么在论文中体现你阅读过分类学理论的文献就是一种向评审人传达积极信息的方式。但这并不足以说明你的研究水平达到了博士阶段的要求——你还必须通篇使用合适的学术性语言或技术术语，引用应该被引用到的文献，以适当的抽象程度讨论研究结果等等。如果你在早期就形成了透过字面意思去阅读和写作的习惯，那么你在写博士论文时也就会自然而然地那样去做，从而大大提高论文的直接通过率。

### 标准建议

第一步就是做一些积极的事情使自己有一个好心情。标准的自助性质的书籍在这方面很管用。书里推荐的很多做法即便是没有多少空闲时间的博士生都可以尝试，而且它们通常很有趣。比如，你可以花15分钟的时间来做运动，这能使你心情好、身体棒，还可以使你的头脑更加清醒。这15分钟的运动可以包括打扫屋子、房间或阁楼的卫生死角。打扫卫生能够使你有一个更整洁舒适的环境，或者提高你写论文的积极性，对你无论如何是有好处的。

另一件首先要做的事（两件事可以同时进行）是停止把论文看做是一项庞大工程，而开始将它设想成一份由诸多部分组成的文件，每一部分都有其存在的理由，并且每一部分又是由其他更小的部分构成的。你可以以每个小部分为单位展开写作，这样你要处理的就不再是一个庞大工程，而是篇幅不长的若于个文字板块而已。你可以写下每一章的标题以及每一小节的小标题。你也可以就各个小节的写作时间安排制定一个计划，要注意必须留出足够的时间来制作表格、参考书目和附录。这方面的所有事项在专门讲博士学位标准程序的书上都能找到。

在那些专门讲博士学位标准程序的书里可能没有具体指出，但你仍必须牢记的是：你应该将“制作橱柜”的技能充分应用和体现在论文里。例如在参考文献方面：你是否将关键性的文献清楚地列在了参考文献中？不同时期的文献分布合理吗？你是否加人了一些标准参考文献以外的，能体现你独立阅读的文献？你是否加入了能体现你具有追求完美的研究态度，并已经做了全面的背景阅读的文献？……另外这种技能还包括你能够进行的研究类型。如果你的学科要求你会进行涉及广泛的、统计数据繁多的调查研究和深入的、不涉及统计数据的个案分析，那么你的论文就应该能够体现出你已经掌握了调查研究和个案分析这两种研究类型。

进行到这个阶段时你应该已经写了不少东西了。有些部分，比如参考书目，是你有意识地慢慢积累起来的。而其他部分，比如实验科学博士论文的方法章节，可以在做研究的同时成稿，并且一旦成稿，就不会再做太大的改动。

改动最大的是每一章的引言和讨论部分（包括第一章的文献综述部分）。通过过去几年的研究，你一定已经意识到了，对你的研究课题真正具有重要意义的问题并不是你在着手研究时所设想的那些问题。所以你在第三年写的文献综述一定不同于你在第一年写的文献综述。这是完全正常的。如果你好几年的研究得出的结论与你最初凭直觉猜测的一模一样，那倒是令人担忧的现象。修昔底德在撰写他的伟大著作时，或许也曾经在中途停笔，又重新从头写起，这才得以发现第一遍时错过的重要主题。在你发现论文的某些部分要卷土重来时，你可能没有心情去同情修昔底德这个没有幽默感的老学究，但如果这样一个著名的天才也遇到过要重写的状况，你遇到这种状况时也就没必要感到羞耻了。

修昔底德的故事对你有什么启示意义呢？它的启示意义就在于，如果你有基本常识的话，你应当认真考虑彻底重写引言和讨论部分。重写这两个部分可以使你的论文更有条理，每一章到下一章的过渡更加自然严密，而不是让人感觉是随心所欲拼凑起来的。比如说，你可以在引言部分提出一组明确的问题，在结果部分分别用一组图表来回答这些问题，并在讨论部分依次讨论引言中的每个问题。所有无关的、节外生枝的部分都应该被删除掉。

再次使用制作橱柜的类比，橱柜需要上光，写论文也需要润色。你应该确保评审人阅读的最开始几页展示了你多方面的学术技能——好的参考文献、专业的论证和好的表达。要有充足的时间做这些工作。修改参考文献中的标点符号错误听上去不是很费劲，但如果你犯的小错误太多，修改起来就会花去大量的时间。

这一章的其余部分将讨论一些你急于想知道答案却又不好意思问的问题，还将涉及一些你应该知道答案却可能从未问过自己的问题。与通常一样，你的导师有最后发言权。我们给出的只是基本原则，你的论文有其特殊性，需要用到一些不同的处理方法。

一些经典错误，以及如何避免它们
:   * 不要拖到最后一刻。事先制订计划，留出充裕的时间对付意外情况，包括装订文稿的时间都应该事先安排好。
    * 不要含糊其锌。
    * 不要用模棱两可的语句来逃避问题——评审人能一眼就看出你是在逃避问题，并会在答辩时无情地质问你。
    * 不要将问题简单化。你的读者也是专业的研究人员，把问题简单化会让他们认为你没有领会你研究领域的复杂性。
    * 不要使用连你自己都不确定是什么意思的大词（big words）。错误使用大词会让你看起来像个白痴。评审人知道的大词、生僻词一定比你多，他们不会对你炫耀词汇量的行为产生什么好感。
    * 不要依据别的学科领域或别的国家的学术写作惯例来写你的博士论文。如果你不清楚自己的学科有哪些写作惯例，应该先弄清楚。如果你反对自己学科的写作惯例，你也应该在拿到博士学位后再表示出反对意见，博士论文不是你说在“不”的地方。
    * 最后，也是最重要的一点，不要忘记三条黄金法则：不要说谎；不要故作幽默；不要惊慌失措而在压力下吐露真相。

## 论文结构

论文构架的原则是什么？很多原则在现有的文献中都有论述，比如：

* 发现漏洞引发漏洞补缺；
* 不断发现新的依据（一项研究引发出另一项研究）；
* 对理论的关注引发以假设为前提的研究，从而引发出理论的进一步完善；
* 完善或迭代开发（iterative development）（模型迭代；方法应用的迭代）；
* 以实践为基础（即反思历史发展）；
* 问题引发实证性研究，并最终导致理论产生。

虽然第一稿常常是按时间顺序写的（按时间顺序记录研究的过程和研究思想的发展），这种结构在大多数情况下并不是最合适的。以实验为基础的研究论文的一般结构应该是：

* 引言；
* 文献综述；
* 方法论／研究方法；
* 实验描述／研究方法的实施；
* 结果／讨论；
* 结论以及未来研究计划，可以在其中再次重复方法论／研究／结果的顺序，以方便读者做进一步研究或重复研究过程。

较常见的结构问题有：

* 没有为结论的得出做铺垫；
* 数据和讨论的内容与方法论混在一起；
* 事实依据太分散；
* 解释和讨论没有与实验结果分开；
* 涉及两个彼此不相关的主题；
* 没有形成一个完整的体系（也就是说，没有回到理论上去，没有体现出问题是怎样被解决的，没有将研究结果与研究目的联系起来）。

## 学位论文的常见问题、核对清单以及一些你应该间自己的问题

### 长度

论文应该包括多少章节？多长？

大多数大学对论文的篇幅上限（一般100,000单词左右）有明确的规定。有时你可以通过附录来添加内容，而不受上限的约束。但你始终要记住，你写多少评审人就要看多少。章节的数目应该由论文的结构来决定（一般一章内容对应一个独立的结构板块），论文的长度应该能学术性地概括你的研究工作，而无需比这更长。

### 结构

结构这个问题我们已经在书中多次讨论。下面一组问题是你应该问你自己的；

* 论证清晰有力吗？
* 论文中包含的所有内容都是论证必需的吗？
* 论证必需的所有内容都写在论文里了吗？
* 论文读起来一气呵成，还是像在念购物清单？

### 标题

标题是论证过程的“指示牌”：它们应该体现论文的结构，并暗示其内容。所以标题应该是描述性的。好的标题是清楚的、有内容的。一个检测标题优劣的办法是阅读目录，看看你通过浏览标题可以预测出多少关于研究的信息。用艾维克（Avic）的话说，“优雅的”标题应该是：“仅看它们我就能知道我该有什么预期”。

检查目录中的标题时号你可以问自己以下问题：

* 研究问题是在哪儿被提出的？你能看出研究问题来吗？
* 研究方法是在哪儿得到描述的？你能看出研究的实际操作方法吗？
* 证据是在哪儿给出的？你能看出是什么类型的证据吗？
* 论文的切入角度或观点是什么？
* 论文给出了新的模型或理论吗？
* 研究的重要性体现在哪里？
* 结论有哪些？

### 研究问题

这是论文的核心部分。论文作者很容易忘了把研究问题明确地提出来，因为作者本人对这些问题实在太熟悉了，他们无法想象居然有人会不了解这些问题。你应该问问自己：

* 具体的研究问题是在引言章节的哪个部分被提出的？（也就是说，读者要等多久才能被告知论文讨论的焦点在哪里？）论文的主题是用一句话还是一段话来陈述的？
* 研究问题的表述清楚、简洁吗？
* 研究问题是通过哪种形式来描述的，是把它看做目标（aims）、问题（questions）、目的（goal）、需要解决的问题、提出的挑战或是其他？

### 理论和证据

理论框架为你的研究提供了逻辑依据，而只有有了证据，你才能称自己的研究是对现有知识的原创性贡献。你可以问自己以下问题：

* 理论是如何在论文中给出的？
* 理论是如何被运用到论证中去的？
* 论文是否明确表明了研究与哪些理论相关？
* 研究设计有坚实的理论根基吗？
* 论文明确体现了研究对相关领域理论的贡献吗？
* 理论和证据各占多大比例？
* 证据的给出符合客观性原则吗？
* 有对前提的陈述吗？
* 读者能够根据你对研究方法的描述重复研究过程吗？
* 对数据的阐释（interpretation）是独特的吗？
* 证据是从数据中推导出来的吗？
* 结论是依据证据得出的吗？

### 引言

在引言部分，你应该（a）留给读者一个良好的第一印象，并且（b）让读者了解你花数年的时间研究某个课题是有重要原因的。引言的组成部分一般包括：

* 陈述研究问题；
* 概括研究问题的逻样依据；
* 解释语言和术语（如果有必要的话）；
* 目标和目的；
* 概述研究对相关领域的贡献，
* 指出研究方法；
* 指出论文其他部分的总体思路：论证的概述。

### 最后一章（或几章）

你要通过最后一章（几章）达成的目标与引言的目标相似：向读者证明你过去儿年的研究取得了成绩，并且给读者留下最后的好印象。最后一章（几章）的组成部分一般包括：

* 结果总结（可以具体地对照引言中提出的研究目标来写）；
* 讨论结果的普遍性；
* 讨论局限性（要用肯定的语气）；
* 陈述对现有知识的贡献；
* 未来的研究计划（陈述要有力、肯定）；
* 推断（要注意分寸适度）。

### 文献综述

文献综述是要综述文献，而不是简单地将文献堆在一起。文献综述应该出现在论文的什么地方？要回答这个问题就必须先弄清楚另一个问题：文献综述的目的是什么？这个问题的答案包括以下几点：

* 为研究提供框架（将它放在现有理论和先前研究的大框架中来考察，体现进行研究的动力从何而来，为什么有必要进行这项研究，以及它的重要意义）；
* 将作者从事的研究与其他研究项目区别开来；
* 确立权威性。

因为文献综述的作用之一就是为研究提供框架，所以它应该出现在论文的开头。很多论文还会在全篇范围内添加具体的参考信息——比如详细描述某种研究技术或在讨论部分提供与其他研究的比较和对比。有些论文把引言部分分散开来，分布在每个有必要做介绍的环节，其实也就是使每个主要的论文部分都拥有独立的引言和文献综述，这种做法可能会有效，但也有风险。把文献综述放到最后是少见的，也是不值得采取的做法（这样的论文一般不会被认为是篇优秀的论文）。

文献综述应该包括：

* 一些较具综合性、代表性的文献；
* 会议论文；
* 与论文焦点相关的文献。

本书在多处都讨论了文献需要涵盖的类型、引用数量的合适尺度，以及文献发表的时间跨度。

文献引用包括以下几种形式：

* 对某篇论文的有条理的、客观的总结；
* 一句话陈述；
* 直接引用；
* 集合性陈述一—将属于同一思想体系的文献集中起来陈述；
* 编辑性陈述.只陈述为你的论证服务的文献（也就是说，从文献如何服务于论证的角度来陈述文献，而不是描述文献本身）。

对文献的陈述应该与对其的解释区分开来。

你应该问问自己，你是单纯地陈述了文献内容，还是加入了自己的分析和解释。

写好文献综述的关键是建立起由在50到150篇论文组成的基础坚实的核心文献库，这样你就可以从中得心应手地选取你需要的文献了。

### 表格

怎样使用表格？表格的用途是什么？以下概括了表格的几方面用途：

* 总结（比如对实验结果、数据分析和文献的总结）；
* 比较（比如对多项研究的研究方法和结果的比较）；
* 提供背景材料以及帮助导航（比如帮助读者明确论证思路和论文线索）；
* 建立类别，并规定各个类别涵盖的项；
* 提供框架（比如为各个学术概念及其相互关系，技术及其应用提供框架）。

表格不能单独存在——它们必须在论文中得到描述，并与论文相关。还要注意按照规定的格式给表格标号，标号格式要保持一致。

### 图像

怎样使用图像？图像的用途有哪些？一般图像是用来：

* 强调重点；
* 展示（比如展示论文中提到的某个事物的图像）；
* 提供另一种叙述方式（区别于用文字或表格叙述）；
* 总结；
* 对比两个事物；
* 澄清；
* 作为掩盖写作水平差的把戏，但一般这类把戏都不会得逞；
* 提供一个概念性的地图（通过图像来梳理各种概念、论证和过程）；
* 作为娱乐性素材（不建议尝试——牢记笫二条黄金法则：不要故作幽默）。

### 附录

附录包括哪些东西？答案：支持论证但没有必要在正文的核心论证环节出现的材料，比如：

* 数据；
* 细节性的数据分析；
* 工具（比如问卷）；
* 案例；
* 编码（如果论文涉及软件编程）；
* 术语汇编。

记住；评审人是会去读附录的。仁慈的评审人读附录是为了找到让你通过的理由；不仁慈的评审人读附录是为了找到你不够格的证据。

## 关于写作的一些观点

* 写作是困难的、花费时间的。做个简单的算木：你在五分钟内能写几个有用的句子？然后再根据你的回答估算一下写一篇文章，一个章节要用的时间，这样你写论文的日程安排就会现实许多了。
* 写作就是要把你的思想表述明白（参看我们关于在“叙述线索在”的讨论）。
* 写作是有硬性要求的：内容（写的东西要有意义）；顺序（说理摆事实要有条理）；完整性（每个部分都要彼此衔接，不能留出空白）。
* 材料不可靠（不严密的思考、不完整的理论或不可靠的结果）会使写作难以进行。
* 在写作时遇到困难往往体现的是你的研究存在问题，而不是你的写作态度存在问题一如果你在写作过程中遇到困难，应该细致地考察你的研究目标、步骤，以及你在写作时使用的素材。
* 在动笔前组织好你的想法、概念和素材。
* 表达要准确。

### 怎样才算写“充分”了？

* 一个较为完整的、具有分析性的文献评论。
* 体现出研究目标已经完成，也就是要给出新的认识，并用事实根据来支持这种认识。
* 指出研究发现的重要性及其对知识的贡献。对研究发现的可推广性和局限性都要有认识。

## 关于论文的常见提问

问：有必要将研究过程中做过的每件事都写在论文里吗？

答：没有必要。如果你认为某组数据或者某项研究对整篇论文没什么贡献，你就没必要把它写进去。但要注意，如果你做的某项研究证明你最初的直觉预测是完全错误的，那么在这种情况下，你应该将这项研究写到论文里去。

问：论文需要包括原始数据吗？

答：这取决于你所在学科的惯例。你可以请教你的导师，并查看你所在大学关于博士论文的规定。一般的原则是在附录中收录你在每个研究阶段使用的样本，包括最初给调查对象的说明材料，你采集数据的所有工具的样本，以及一到两份完整的调查问卷反馈单的样本。这样评审人就可以考察你在每个阶段的研究步骤，并对这些步骤是否正确做出判断。

问：论文需要有多长？

答：答案是论文应该长到足以完成它的使命，但不能比这更长。但如果你没有辅导过本科生或讲授过研究方法一类的课程，你可能无法领悟这个答案真正的意味。所以我们给出的对你更有帮助的回答是：查看规定并咨询导师。另一个对你帮助不大的回答是：将论文控制在学校规定的篇幅上限之内。

问：我在交论文的两天前发现我在分析数据时犯了一个错误，我该怎么办？

答：问得很好。无论如何不要撒谎。立即联系导师，咨询他对修改错误的建议。如果这个错误很严重，你就必须重新进行数据分析，这是基于现实和道德的双重考虑。如果错误不是很严重，而你又快来不及完成论文了，你的导师可能会给你一些有用的建议，使你能够争取到更多的时间，使交稿期限不再是一个问题。另一个解决办法是将这个错误的数据分析从你的成稿中彻底删除，如果这个分析只占成稿的很小一部分的话。

问：我正在成稿的过程中，却发现有人发表过和我的论文几乎一模一样的东西。我该怎么办？

答：不要慌。同样的材料可以至少从两个角度去陈述，如果你保持头脑清醒的话。找你的导师谈谈这个问题。你应该可以重新组织你的文章，加人对那个人论文的讨论，并在同时体现出自己的研究与那个人的研究是有区别的。比如，他研究的社会群体可能和你研究的社会群体有所不同，如果是这样的话，你可以在论文中更加强调社会群体这个方面，而不是强调研究方法的新颖之处。事实上，通过将你的研究结果和其他人的研究结果进行比较和对比，你的论文可能会更加出色。

问：我写了一半，思路就被堵上了，我该怎么办？

答：指导博士生的书籍里给出了很多解决这个问题的办法，我们这本书在讨论写作的儿章里也提到了一些办法。比如故意做一些与写论文完全无关的事；在写作时故意表达不准确，从而引起你潜意识的反抗，使你能够重新开始写出真理；给自己一些奖励；为自己制定小的、可以完成的目标；找朋友激励你。

问：我可以按照你们写这本书的风格来写我的论文吗？

答：你一定是在开玩笑。这本书采用的是我们喝咖啡谈话的风格，我们学术性文章的风格是与此非常、非常不同的。
