# 写作风格

写作就像穿衣服。你根据不同的目的写不同风格的文章。如果你要去游泳，你会穿泳衣；如果你是名焊接工，你工作时就应该穿焊接工的服装。这个意义上的风格指的其实是功能，而非流行趋势。不幸的是，很多博士生的学术写作水平在差强人意与合格之间，就算是那些写得较好的也必须掌握更多的写作技巧才能使他们的论文达到优秀的水准。这就是本章要讨论的问题。它将帮助你把写作当成一种专业工具来使用，并教会你在不同的情况下用恰当的风格来写作，而这是你作为博士生需要掌握的技巧。

在一开始就应该认识到一个重点是：我们这里讨论的写作，重点不在于传统的语法规范或流畅的表达，而在于语言的工具性。另外一点对母语非英语的学生很重要，那就是你不需要说一口流利的英语才能写好论文。优秀学术写作的关键在于结构和形式，而语法并非关键。

本章讨论的是写作技能：如何避免让别人觉得你很可笑，如何使自己看上去是个有能力的专业人士。在不同学科里，优秀的写作技能的要求也各不相同。所以你应该了解自己学科的优秀标准，而不能想当然地认为写作技能在所有学科中都是一回事。

本章还收录了一些一览表、小诀窍以及对常见提问的回答，内容涉及普遍意义上的学术写作，也涉及特定的学位论文成稿。

## 不要暴露弱点

在鲨鱼聚集的水中游泳不是个好主意，尤其在水中有血的情况下。如果水中的血是你的，那就更糟了。这血会吸引鲨鱼来袭击你，同样的原则也适用于写作。具有批判性的读者在很远处就能觉察到水中的血腥味，于是会飞速游来捕获猎物。有时他们速战速决，但有时他们喜欢先和猎物挑逗一番。这可不是一件好玩的事。

还有一个比喻也可以用来说明同样的问题，虽然它不及第一个比喻抢眼，但更直接贴切。那就是狼群的比喻。狼群在进攻前会先接近猎物，观察猎物是否显示出了任何弱点。如果猎物看起来很健康、完全有能力自我防御，那么狼群就会立刻放弃捕获它的念头。如果动物看上去很虚弱，他们就会捕获它。如果你的论文（或者陈述发言）看起来质量很好、很专业，那么你就不会受到攻击或批评。如果存在着弱点，那么狼群就会快速展开围攻。试想一只肥硕的北美驯鹿在严酷的寒冬遭遇了狼群，狼群是不可能怜悯它，让它逃生的，而向你的批评者乞求怜悯和向真正的狼群乞求怜悯一样是没有用的。

那么，你该怎么办呢？

### 第一步：没有准备充分就待在家里别出门

第一步也是最简单的一步就是，在你的伤口还未愈合时，你不应该进入捕食者的领地。如果你的文章还没有准备好，就不要拿出来给别人看；应该回去改进文章，而不是把自己不够格的东西展示出来以后再为此道歉。这里有一个很好的例子（是参加某个讨论会的同事提供的）：“我们得到了以下结论……然而被调查者的反馈显示，我们在调查开始时给他们的指导不够明确。所以我们找到了一组新的调查对象，明确了指导信息，重新进行了实验，得到了以下结果……”。

这段话的潜台词是：“如果有必要重新做实验，那就应该重新做实验，我觉得这是很自然的事，费时费力都不是借口。我压根就没有想过要把不够格的数据拿出来给读者看，再请求他们的原谅，这完全不符合我行事的原则。”这段话有一处很关键，那就是第二句话紧接着第一句话，没有提到任何决定重做实验前的犹豫或在重做实验过程中遭遇的困难，而是直接给出第二次实验的结论。这体现了作者已经把发扬专业精神当成了再自然不过的事，这样的学者在研究的其他环节一定也会细致入微，所以那些试图挑刺的批评者明白，他们在这个作者面前是无机可乘了。

新手们常常会犯错误的两个方面是样本的大小以及数据的多少。这里还有一个很好的例子，摘录自一篇科学硕士论文：“有三组受访者，每组四人……”（接下去就开始描述每个受访组）。也就是说，一共只有12名受访者。12名，而不是好几千，甚至都不是好几百。一般的新手在这种情况下一定会为样本之小道歉，这就相当于让自己伤口的血涌进鲨鱼池里，其致命后果就是所有附近的鲨鱼都不惜放弃原先的捕食计划，转身来围攻和消灭你。而在这篇论文中，作者只是描述了每个受访组，接着论文就进人了下一个部分。

这个例子的潜台词是：“这篇论文讨论的是概念的检验。我不需要一个很大的样本去达成我要达成的目标，我清楚地了解这一点，我知道我在做什么，所以现在，让我们进入下一部分。”

样本的大小和数据的多少很重要。然而所需数据的多少取决于你论文的性质，它是数据导向的实证性论文，还是检验某个概念的论文，抑或是研究方法导向的论文？所需数据的数量随论文性质的不同而产生极大差别。没有太多新手能意识到这一点。过于庞大的样本其实体现了你的实验设计不理想，以及对推论统计的掌握不够格，这两方面都是吸引鲨鱼的地方，然而能认识到这一点的新手就更少了。如果以上几段文章让你感到焦虑担忧，那么你就应该考虑阅读一些关于论文类型、实验设计和推论统计的书。

### 第二步：准备好了以后就要传达正确的信息

要显示出你是专业人士，那么使用领域内专业人士的语言和写作惯例。如果你不清楚，就应该学习。读这本书以及其他相关书籍是一个好的开头。要使你的语言和其他非语言的方面都与没有经验的起步者区别开来。

惯例有什么用？
:   每门学科都有它自己的写作惯例。有一些高度正式，有一些则比较含蓄。要发现这些惯例，你就应该以分析的眼光来阅读文献。这些文献中的惯例可以：

    * 体现学科的学术标准；
    * 使读者能够读得懂论文；
    * 使读者能认识、比较和复制／重复研究方法；
    * 便于读者比较和综合一一使论文的形式转换成便于与其他论文相联系的形式。

    遵守学科惯例就相当于告诉读者，你知道什么是重要的，也就是说“你是内行”。

体现出你有重要的东西要说
:   要客气地、不带挑衅地传达这个信息。不能与你的读者产生对抗，但是应该让你的读者感觉到，你是一个专业人士，你不会给他们看二流的东西，浪费他们的时间。一个有用的诀窍是要换个角度考虑问题，不要让读者感觉到你是在说：“看着我”，而是要让读者感觉到你是在说：“看这个”。如果你在一篇论文的开头提出了一个有趣的问题，并暗示了一个可能解决问题的有趣的办法，而不是告诉读者是你想到了一个有趣的问题，又是你看到了解决问题的可能性，那么你就上了轨道了（这种写作思路的一个好处是，如果你提出的解决方法没有奏效，它也并不能反映你本人的判断力值得怀疑）。

    从别的学科领域引入可能解决问题的方法往往是一种有效策略。这个别的领域必须具有足够的可靠性以至于可以被应用到你本人研究的课题上——这往往意味着，你所要引入的这个领域必须比你研究课题涉及的领域更加正式，具有更加完善的研究方法体系。你应该充分掌握你所要引入的领域，否则你提出的解决办法就不会具有可信度，那个领域的行家会把你看做是一个典型的新手，没读多少文献就开始自作主张，犯了新手常犯的错误，只是你的错误还涉及别的领域而已。一点肤浅的对某个其他领域的了解可能会使你在会议上蒙混过关，因为会议的听众席上可能没有来自那个领域的专家来揭露你。但如果是寄给期刊的稿件，那么你蒙混过关的可能性就为零了，因为期刊编辑一定会确保你的论文由相关领域的专家来鉴定。专家学者对很多生僻知识的了解程度是惊人的。

## 了解你的敌人

到了这个阶段，你应该要警惕你的敌人。你真正的敌人是那些读者可能将你与他们混淆起来的人。应该含蓄地，而非明确地告诉读者，你与他们是不同的。如果你明确地指出有哪些人与自己不能相提并论，那只能加深读者对你的坏印象，他们会认为你擅自做主，把自己放到高人一等的地位。但如果你能含蓄地表达这个意思，那就应该没有什么问题了。

渴望成功的新手
:   一类敌人就是那些没有深入阅读文献、犯典型的入门阶段错误的新手。你的论文需要发出强有力的信号，告诉读者你不属于那一类人。可以与专业人士喝杯咖啡聊一聊，让他们给你讲讲新手的典型错误有哪些。还有就是要全面深入地阅读文献，历史久远的文献也要读。你可能不相信，二十年前的文献对你也会有很大帮助——很多研究人员过于急功近利，往往没有耐心做基本的功课，结果却发现他们的研究前人早已做过了。没有什么东西可以长久地替代文献阅读，这本书里介绍的简便途径只是用来帮助你更有效地完成任务，而不是帮助你逃避任务。文献和研究方法一样，应该是你的朋友，你掌握的文献越多，你能自信地应付的问题也就越多。

聪明的外行
:   你的另一类敌人就是那些聪明的外行。如果一个问题只需要一些基本常识就能解决，你就不应该把时间浪费在这个问题上。这也就是为什么文献中与直觉相反的结论特别有用的道理。

空话连篇的推销员与自封的天才
:   你的其他潜在的敌人还可能包括空话连篇的推销员以及自封的天才，这两类人都喜欢兜售自己的“万灵药”。声称自己解决了所有领域内的专家（意味着读者也包括在内）都困惑不解的问题，这不会让读者对你有什么好印象。

### 不要表现出自己的软弱或迟疑

永远都不要表现出自己的弱点，向读者道歉，请求读者的原谅。如果你的论文写得很好，你就没有必要道歉或乞求同情。如果你的论文没写好，那就不要把它拿出来见人——回去把它改好了再说。

有很多词语和句子都会表现出你的软弱。其中有一类称为不“推托话”（weasel words），这类话的目的是帮你躲避必须做明确判断或采取明确行动的局面。“推托话”在学术写作中不应该出现，在学位论文中更不应该出现。比如，说某件事“好像是”（seems）另一件事，那是不够的。到底是“是”还是“不是”？同样的，“可能”（probably）这个词也不好。“推托话”说明作者思考得不够深人，或是在做无根据的推断。

你在证明某件事的正确性或正当性的时候，也就同时提出了两个问题：这件事的正确性或正当性为什么需要证明，以及你的证明是否充分有道理。任何涉及前提假设的句子都很可疑，“可能”、“或许”（presumably）、“一定曾”（must have）这类的词其实是在告诉读者：“我没有事实根据，只是在猜测而已。”如果你有事实根据，就把它们摆出来；如果你没有，而涉及的问题又很重要，你就应该搞清楚自己的猜测是否正确。你要么明确地指出你的某个想法只是一种猜测（也就是说它与你的论证只存在着表面的而非确凿的关联），要么就把猜测留到结尾的讨论部分，为未来的研究作铺垫。

表意模糊是不可以被接受的。以下这段话摘自一份评审人的报告：

> “在一篇学术论文里，所有细节都必须尽可能是确定无疑的。最好省略你不能确定的信息。如果可以省略，那就说明它们没必要写进论文里。如果不能省略，那你就必须确认它们的可靠性。否则，你就无法得出准确的结论，而你的整篇论文就成了无法证实的猜想，这是博士论文所不能允许的。”

在这方面要注意的一点是，不要听信公众舆论的原则，并将其用于解释你的研究。因为这些原则往往是不正确的或者有严重误导性的。因特网提供了一个很好的例子——[sci.skeptic](http://www.faqs.org/faqs/skeptic-faq/)和不[alt.folklore.urban](http://www.rheingold.com/electricminds/html/vcc_dir_folklore.html)是两个资源丰富的新闻组，可是它们散布的很多观点都是没有事实根据的。你一定要保证论文中使用的解释原则来源于合适的学术资料。如果你找不到相关的学术资料，那么你使用的解释原则可能就是不正确的。

### 不要虚张声势

如果你对某个问题不了解，那就花时间和精力去学习，直到你理解为止。如果你使用了一个自己都不知道是什么意思的技术术语，具有批判性的读者一眼就看得出来。

有一个例外，那就是当你就专业性的检验（specialist tests）听取专家意见的情况。在这种情况下，很多学科的惯例是原谅研究者不具有他本人领域之外的专业知识，并允许他从一到两个独立的、相关领域的权威那里听取建议。如果建议不对，那也不是研究者的问题，因为他已经采取了他应该采取的行动。但研究者仍需要了解统计检验结果的含义。

## 将写作当成一种表现性行为

写作风格和语言还包括内容的选择，对于你的核心论证都很重要，然而它们更大的作用却显示在它们可以准确地传达关于作者本人的信息。

传达的负面信息有：

* 我无知、不了解情况、我很绝望；
* 我懒惰、不诚实、没礼貌、我该受到谴责。

传达的正面信息有：

* 我知道自己在做什么；
* 我是个态度端正的专业人士。

这些信息是怎样传达给读者的呢？情况各不相同。

### 我是个态度端正的专业人士（概念很简单，要为之付出的努力却很多）

* 我注重细节，比如拼写正确和引用在全文中的分布合理；
* 我做了所有该做的工作，并将其体现在成稿中；
* 我细致专业地完成了研究的每个环节，并将其体现在了成稿中；
* 我把我的研究清楚、完整地写在了论文里，论文符合我所在领域的写作惯例。

### 我知道我在做什么（要做到这点需要丰富专业的知识和辛勤的工作）

* 我知道所有关键文献，阅读了它们，并正确地引用了它们；
* 我也知道其他相关文献，并正确地引用了它们；
* 我知道并了解我所在领域内的所有技术性概念，并在我的成稿中谨慎使用了所有相关的技术性概念。

### 我无知，不了解情况，我很绝望（在不小心就会传达出这样的信息，尤其是对二年级的博士生而言）

* 我没有读过关键文献；
* 我犯了我这个阶段的一些典型错误，却连自己都没有意识到；我没有想到应该把稿子交给某位能给我指出错误的前辈过目；
* 我在论文里向读者道歉，请求他们的谅解。

### 我懒惰，不诚实，没礼貌，我该受谴责

* 我的论文里基本没有引用参考文献；
* 我引用的材料全是来自因特网、大众杂志和教科书；
* 我的拼写、语法和表达都一塌糊涂；
* 我试图用笑话、插图、花哨的装帧、彩色图表以及一大堆对导师的感谢词来掩盖我一塌糊涂的拼写、语法和表达；
* 在那一大堆写给导师的感谢词里，我却拼错了导师的名字，弄错了他的职称；
* 我的论文里找不出证据可以证明我做过研究；
* 我论文里的某些段落写得明显比其他段落要好，与网上的文章非常相似；
* 我做了导师明确告诉我不要做的事；
* 我在论文中声称理论和学术界要优于“现实世界”，但其实我口是心非，早就溜进“现实世界”了。

如果你符合以上几条，那么你可能根本得不到允许攻读博士——初期的挑选过程一定会淘汰你，把你抛到局外（虽然你仍有可能攻读科学硕士学位，但你糟糕的论文会让你连硕士学位都拿不到）。符合以上描述的人可能根本不可能在读这本书；我们加入这个部分基本上只是为了让那些勤奋却没有安全感的学生放心，使他们认识到，他们并不像有时所想的那么糟糕。

## 博士论文

你的论文能够体现出：

* 你对课题的驾驭能力；
* 研究洞察力；
* 对你所在学科的尊重；
* 可发表性。

让论文的形式和语言正确与让论文的内容正确一样重要——事实上，它们对内容的表达起到关键作用。如果你对此心存怀疑，牢记这条基本原则：论文应该能脱离作者独立表意——如果评审人误解了其中的内容，责任在于作者，而非评审人。

博士论文被广泛认为是最高形式的学术写作，它对内容、准确性、论证以及对全文的统筹规划方面的要求都要高于对单独发表的学术文章的要求。它是一部“杰作”，这并不代表它是“完美作品”，而是意味着它包含的写作技巧、技能、形式和功能可以展示出一个学生的全部才华。

### 论文“红线”

好的表达的核心是要有一个好的“情节”——不是小说的情节，而是一个将各个元素联系起来，使前后元素间自然过渡的顺序安排。博士论文必须有一条清晰的“叙述线索”。瑞典的学者们将它比喻成一条“红线”，贯穿全文（就像绣在平纹细布上的红线）。这条红线（有清晰论证过程的合适结构）是成功的必备要素。虽然红线与写作结构紧密相关，我们在这一章关于写作风格的讨论中也提到它，是因为风格也包括清晰，包括证明你知道什么重要什么不重要。

一位智者托马斯·格林（Thomas Green）曾经将红线表述成是“事情的伟大全局”，简写为GOST（Great Overall Scheme of Things）。你论文的所有元素必须要受GOST的支配，不符合GOST的内容要删除。托马斯的建议是要“和你的GOST交朋友”。如果你始终不断地重新评估你的GOST，你就能够写出一篇前后连贯、结构完整的论文。

## 学术写作风格

不同的情况要选择不同的风格。风格是通过结构、语言、修辞、事实根据的展示形式、文献的使用、图表的使用等来体现的。学术研究论文的风格与教科书的风格是很不一样的，而这两种风格又与商业报告的风格大不一样。要学习（通过分析样例）如何使用不同的风格，以及如何挑选适合你目的的风格。如果你选择的写作风格不合适，这就说明你还没有了解你所在领域的基本规定，读者们会认为你懂得很少。

认识各种风格之所以不同的原因也是很重要的——比如正式的学术写作就必须要引用参考文献，要按照惯例汇报实验结果。要注意不要受其他领域的写作指南的影响——适合商业报告的风格不一定适合写论文，反之亦然。同样的，“简单的语言”（plain English）理论上很不错，但任何推崇在专业性写作中使用简单语言的人很有可能自己都没有亲身尝试过那么做。最理想的学术写作应该达到使人愉悦的谈话性的语言，但同时仍要保持文风清晰、老练并准确。

### 语言

“语言”指的是你写作的特性，它能体现出你是一个什么样的人，你写作的态度如何，你心目中的读者群是哪一类型的。有的文章读起来是辩论性的（作者在与谁辩论呢？）、宗教性的（作者试图向谁传道呢？）、道歉性的（作者试图要取悦谁呢？）、屈尊的（作者低估了谁呢？）、自以为是的（作者小看了谁呢？）等等——这些作者的语言体现出了作者心目中的读者群。

清晰、简单、权威、诚实，这几点是作者语言的正面特性。不准确、宗教性、自卫性、自以为是，这几点是应该避免的负面特性。你可以找出一篇范文，分析它的优点何在。看看你是否能够总结出作者语言的特性，并从中发现作者的独特之处。

你的读者是谁？你所在学科领域的惯例是怎样的？研究汇报的标准是怎样的？一个诀窍是找到一个聪明的、读过很多书的、非专业的读者，把他当做你心目中读者的代表。如果你假设你的读者是个聪明能干、眼界开阔又对你的研究感兴趣的人，那么你就能避免在论文中使用不适宜的语言。

清晰对于论文来说是至关重要的。你应该在论文中展示自己对所选领域有详细的了解。这并不等于简化内容，或使用“大词”。一篇好的论文会恰当地使用技术术语，如果它是写给专业研究人员看的，普通读者可能会因此看不懂，然而这并不妨碍专业读者读懂文章。使用专业术语对于目标读者群并不构成阅读障碍，表达不清晰才会。如果你自己都不知道想说什么，你就应该先想清楚，这样表达起来就会清晰很多。普通技术术语是可以通过对其明确定义和解释被人了解的——这是术语的特性。所以大量使用普通英语术语是可以的。

要谨慎使用类属词典里的词。如果你在类属词典里发现了一个词不确定它的意思就用到论文里去了，你很有可能会用错这个词而使自己看起来像个傻瓜。

### 合适的评论性语言的特点

合适的评论性语言应该是：

清楚的
:   * 清晰，有条理地论证；
    * 不要离题；
    * 删除不必要的内容；
    * 语言应该是在“轻度正式”——不要太难懂，不要太正式，不要有太多术语，而应该是三思后写出来的能让人读懂的文字；
    * 关键词的意思要前后一致；
    * 例子要能够说明问题。

诚实的
:   * 从数据推导出结论的过程要严密；
    * 要考虑到其他说明；
    * 要承认局眼性。

中立的
:   * 问题的提出形式要中立；
    * 在研究和成稿时都要主动避免偏见；
    * 避免使用带感情色彩的语言。

权威的
:   * 熟练使用文献；
    * 没有含糊不清的语句；
    * 优先获得可靠性；
    * 内容涵盖的范围合理；
    * 准确恰当地使用术语。

充分论证的
:   * 决定或假设都必须是有理由的，并对其做出解释；
    * 不存在任何未经论证的断言；
    * 将数据与结果、讨论和结论区分开来。

批判性的
:   * 将论文与现有文献的联系体现出来；
    * 能够将论文中涉及的各种学术思想组织在一个框架之下；
    * 指出现有知识体系中的漏洞和缺陷；
    * 在报告的同时加入智力内容。

还应强调什么？
:   * 指出结论蕴含的意义；
    * 指出重要性和意义；
    * 指出未来的研究方向和计划。

## 读出字面背后的意思
评审人非常善于读出你论文字面背后的意思，所以你应该避免那些会向评审人泄露不利于你的信息的语句。一些好的、差的和模棱两可的写作的例子见[@tbl-alt-msg]。

: 读出字面背后的意思：一些典型例子 {#tbl-alt-msg}

| 论文中的表述                                                                     | 别人解读的文中表述的含义                                           |
|----------------------------------------------------------------------------------|--------------------------------------------------------------------|
| 史密斯说                                                                         | 我没读过太多期刊文章                                               |
| 史密斯博士解释说                                                                 | 我读了不少杂志                                                     |
| 约翰·史密斯博士充满热情地说                                                      | 我读了不少言情小说                                                 |
| 有一种普遍认识是（a）                                                            | 存在一定共识的观点是                                               |
| 有一种普遍认识是（b）                                                            | 我没有具体参考文献的支持，但我觉得这么说应该错不了。               |
| 很显然的是                                                                       | 我认为                                                             |
| 可以被证明的是                                                                   | 我希望                                                             |
| 一组更大的样本可能证明                                                           | 我不懂任何推论统计或调查方法的知识                                 |
| 最近的一项研究发现                                                               | 我拿不出具体文献，但我敢肯定这是真的                               |
| 有一些可以证明它的铁事                                                           | 有人在酒吧里告诉我                                                 |
| 激动人心的                                                                       | 我还没有掌握学术写作的要领                                         |
| 发挥出它的潜力                                                                   | 我想让自己看起来像一个没受过学术教育的人                           |
| 一个关于这种霸权的偶然获得的例子                                                 | 这是我从专家那里抄袭来的只有他们才能使用正确的大词                 |
| 客观                                                                             | 我不懂得研究方法                                                   |
| 没有偏见                                                                         | 我不懂得研究方法                                                   |
| 我想                                                                             | 我完全不了解情况，也从未听说过第三人称被动态                       |
| 参看格林et a1（预印本）对这部文献有趣的重新评估                                  | 我读过高级文献，我很优秀                                           |
| 例如格林和布朗1998；史密斯和韦森1999；捷克尔和海德1999；年轻，才华，以及黑人1999 | 我读过很多东西，但没有分辨力                                       |
| 史密斯（预印本）                                                                 | 我与诺贝尔文学奖得主史密斯的关系很好，以至于他寄给我他论文的预印本 |
| 史密斯（私人通信）                                                               | 去年我去参加会议时在施佛尔机场的洗手间遇到了史密斯                 |
| 与1950年展开过的一场辩论非常                                                     | 我对这个领域中大多数人出生以前的、过去的文献非常熟悉，我很优秀     |
| per se                                                                           | 我受过良好的古典教育，所以……                                       |
