# 写作过程

每个博士生迟早都会或多或少遇到写作问题。有时候这类问题会以写作瓶颈的形式出现——你坐在键盘前，打字机或纸张前，无论如何也写不出什么东西来。有时候这个问题又以逃避的形式出现——你找出种种借口来逃避写作任务。有时候它又成了一个涉及作者语言的问题——你可以写出与课题相关的东西来，但无论你如何尝试，你写的东西读起来总是无法达到你想要的效果。

如果你遇到了这些困难，首先要告诉自己的是，几乎每个人都会遇到类似的困难。成功的研究人员和论文作者并不是一帆风顺的人，而是克服了困难的人。你也可以克服困难。这一章讨论的是写作的过程，涉及写作过程中的普遍问题，也会涉及在写作进展顺利时如何更上一层楼。

如果你正在读这一章是因为你正在经历写作的挫折，你感到前途渺茫、情绪低落，那么你一定要记住写论文的底线：一篇论文不需要有趣或雅致，它只需要能体现你获取博士学位的资格。将来可能有一天，研究工作者也能获得诺贝尔文学奖，但获奖作品肯定不是他的研究论文。

由于讨论话题的性质，这一章毫无疑问还包含了一些清单和小窍门（但我们不建议你在自己的论文里尝试这种风格）。

## 写作诀窍

### 删除离题的内容

鞋盒子
:   把多余的文字片断和其他的想法都放到一个安全的地方（如鞋盒）保存起来，将来可能用得上。但在你写论文时不要被它们分散注意力。

在完整的第一稿出来之前不要修改

:   一段文字写得再好，脱离了全文就没什么用了——应该先把第一稿写出来，再开始以完美主义为宗旨的修改润色过程。

削尖你的铅笔
:   写作者和网球运动员一样，往往有自己的一套“仪式”来帮助他们对付手头的任务。关键在于，仪式要有时间限制和固定的形式，否则它反而会分散作者的注意力。所以，打个比方来说，你可以首先削尖三支铅笔，再清理书桌，然后开始写论文。

### 着手写作

找一个朋友谈谈
:   找一个聪明的朋友，告诉他你要写的“故事”。把你说的话，包括你对朋友提问的回答录音下来。如果你一下子找不到合适的听众，可以想象一个，然后对着录音机说。

先写“错”的
:   有很多写作诀窍都用到了一个原理，那就是尽可能早地写出初稿，这样你的任务就变成了重写或在原来基础上做改动。先写点肯定不是你想要的东西可以作为你反对或修改的对象——这往往比从无到有的创造来得简单。

提问——回答
:   可以和你的朋友，也可以单独进行一个提问一回答的练习。可以先由“论文的主题是什么？”开始问，以后每个问题都接着上一个问题的回答，多问一些“为什么”和“怎么样”类型的问题。

誉写员
:   让别人来扮演“誉写员”的角色，以你向他讲述的东西为基础写出一篇文章。誉写员可能很称职，也可能记录得不够准确，无论如何，他都给你提供了可以加以修改的材料。

抛弃前半小时写的东西
:   向自己保证，你会抛弃在前半小时写的任何东西。这意味着你可以在前半小时写一堆垃圾、一封给你母亲的信，或者对你心目中蓝图的描述－任何东西，只要是文字。关键是要开始组织句子和段落，而不关心质蜇如何。（如果写得好，你当然可以保留，写得不好，你保证过会儿扔掉它。）

开始就是简单的打字
:   有时候，逐渐启动身体各个系统也会对写作有帮助——比如，在开始时你要做的仅仅是敲击键盘，打出什么都行，目的只是为了让自已在键盘前调整到合适的坐姿，让自己的手指活动起来，接着你可以敲一点陈词滥洞到屏幕上，使从头脑到手指传输词句的通道流畅起来，然后再开始写文章。

别从开头开始写
:   跳过引言部分，从最熟悉的或最易于表达的材料开始写。你也可以选择从最有挑战性的材料入手。

高强度写作
:   制定一个目标，然后和你的一个朋友合作，共同在规定时间内完成高强度的写作任务。

### 使自己感到惊讶

改变模式
:   有时候仅仅改变作品的外观（比如字体大小、格式）或写作类型（比如把学术论文改变成儿童读物）或模式（比如用图来代替文字）或媒介（比如用纸张来代替电脑），就可以让写作素材看上去“焕然一新”或显露出某些与原先不同的地方。

写瓢虫版本
:   瓢虫系列是儿童读物类的出版物，其语言简单易懂。概括出你论文的核心内容，然后用很简单的语言把它写出来。

情景串联图板
:   学习制作电影的方式，将论文的陈述画成一连串的情景图，一幅图代表一个关键的陈述，用图形来代替文字。你甚至可以看图说话，把图中的情景演绎出来。你可能会觉得很做作，但这样做的确会对你有所启发。

### 整理思路

检索卡片
:   在每张检索卡片上写上一个关键点，然后把它们铺在地上，调整它们彼此的相对位置来说明各个关键点的类别以及它们之间的关系。

思维导图
:   用思维导图引导自己产生想法，并整理出各个想法之间的关系。用一张尺寸足够大的纸或者电脑软件来画这张思维导图。

### 找到重点

回想你的GOST
:   在你考虑细节前，先回想一下，对你来说，“事情的伟大全局”是什么。

找到一种模型
:   找到和你要写的论文功能相似（比如都是展示研究成果）的一篇论文或一个章节。分析它的优点何在，它的内容、结构、特点是什么。从中得出一个模板，然后用你自己的材料来填充这个模板。

逆向工作
:   开始时先想象你想要得到的结果：想象写完了的论文，或写完了的一个章节（可以让模板来帮助你，参考上面一段）。然后以这个完成了的作品为起点逆向思考，找出它的主要组成部分，再找到构成这些主要部分的关键环节，直到你找到写作的出发点为止。

标题
:   在写文章之前先把标题列出来。这样做可以使你在脑子形成一个论文的总框架，使你从一开始就可以有条理地展开写作，而不被细节性的问题纠缠。

### 完善你的想法

把问题反过来提
:   把你的关键想法反过来或换个方向陈述。如果你正在考虑：“女权主义是否会降低吸烟率？”你可以反过来考虑：“吸烟是否会抑制女权主义的发展？”

### 大声读

它起什么作用？
:   写出每个部分（或段落）在全文中扮演的角色（比如在这里我引出了论文的中心思想；在这里我概括了与我的理论对立的其他主要理论；在这里我给出了使用我这种研究方法的先例）。

寻找陷阱和隐患
:   在你修改稿子的时候，要考虑读者可能在哪些方面提出批评（比如你的观点是否有根据？术语使用是否前后一致？你在承认研究局限性的同时是否牺牲了研究结论的可靠性？你的图表是使论证更加清晰还是反而使它更难读懂？）。

### 继续写下去

曲奇饼
:   给自己一些小奖励（比如把曲奇饼摆放在附近，允许自己每写完一部分就吃一块；每写一星期就允许自己玩一天）。

进程表
:   把每部分的标题写在一张表格里，写完一部分就在表格相应的单元格里填入字数和写作时间。每天统计一次字数。

## 写作过程中的绊脚石

写作不是一项单独的活动。它不是单纯的“写下来”，不是把脑子里的东西誉写到纸上那么简单。写作是多项活动同时进行的过程：分析、阐释、记忆、综合、计划、排序、表达、澄清、修改、评论、组织、合理化——当然还有誉写。由于有这么多种认知活动同时进行，写作亳无疑问是复杂和艰巨的工作。对这项工作有正确的预期，可以使你在面对它时比较从容。在进行这项工作时遵守一些规定，可以帮助你较好地完成它。

很多人害怕写作。教育工作者将其描述为“对失败的畏惧”（害怕写错或写得不够好，这种焦虑情绪也构成了写作进程中的障碍）以及“对成功的畏惧”（害怕成功带来的更高预期和压力，这种焦虑情绪也构成了写作进程中的障碍）。认识和面对你的畏惧情绪很重要。是的，它很可怕，但它并不是不可能的任务。最重要的是要认识到，无论写什么都比什么都不写好。

一旦你将东西写在了纸上，你就自然而然地减少了活动的数目。把各种活动分开进行能帮助你更好地写作。你可以把写作看成是一连串的攻关：否决某些想法，强调某些想法，排列各个想法的先后顺序；在初始结构的基础上进行展开，把笔记组织成句子，调整结构，修改语言，检查是否有多余的部分，检查语气是否恰当等。要单独提出来讲的是“否决想法”这一环节。一旦你在纸上写下了一些东西，你的写作任务就从创造转为回应，“写作”也就随之成为“编辑”。要记住的一点是：要在第一稿完成后再开始编辑。

另一条原则是简单原则——这条原则适用于几乎所有设计活动。能达到效果的最简单的语言（最简单的词汇、句子结构、修辞方式）往往是最好的。简单原则不等同于“纲要式写作”。纲要式写作只表达最基本的概念（省略了大多数的细节和现实性）。而“简单”的写作则提供所有必要的信息和细节，并且用尽可能直接的方式来表达。这两者之间的区别就好比是伦敦地铁图和英国地形测星图的区别。两张图都标示了主要通道，但其中一幅图更加真实，保留了各条线路与周围环境的关系，并显示了所在地区的自然状况。

### 普遍性建议

* 写作是一项技能，和所有其他技能一样，写作也是熟能生巧的。
* 向自己保证，必须每天都练习写作，每周完成一篇两三页左右的文章。
* 将研究材料以书面形式带到导师辅导课上。
* 有人对你的文章提出批评时，花时间分析一下他们的批评：为什么他们提出这样的评论或修改意见？
* 有人对你的文章进行文字编轨或其他改动时，花时间分析一下他们做的改动：为什么要这么改？这些修改对文章有什么好处？

### 由学生自己造成的写作障碍

问题：如何开始写作？

记住：写什么都比不写好。不要担心它“不够好”。在完成论文前它很可能是不够好的写论文的过程其实就是不断把它变得“足够好”的过程。如果你不动笔写，不把自己写的东西拿给别人看，你永远都不会得到反馈意见，你永远都不会知道，你的思想表达得如何，你的课题是否有趣，你又在哪些方面启发了你的读者。

如果你写不出东西来，这很可能是因为你还没想清楚自己要写什么。尝试写任何你能写的东西，然后考虑一下为什么它们看上去不对劲，或不完整。扭曲的句子往往暗示着纠缠不清的思路所以你应该着重留意那些意思模糊的语句。

可以考虑使用以下技巧：

* 和一个朋友坐下来喝杯咖啡，把你要写的东西告诉他，也可以尝试让他把你要写的东西再转述给你听。
* 玩“艾丽莎”游戏。艾丽莎是一个电脑程序，可以模拟具有治疗效果的对话。事实上，这个程序只设有有限数量的问题，这些问题都是建立在同样数量的信息的基础上的，然而这些有限的问题却能够有效地导出信息。要玩“艾丽莎“游戏，你可以先说一句简单的话，然后再在这句话的基础上提一些简单的问题。比如：“我想写关于紫象的论文。”“为什么？”“因为紫象比灰象更有趣。”“它们更有趣在什么地方？”“灰象很普通，紫象很少见。”“所有的紫象都很少见吗？”你也可以时不时地问自己一些不合逻辑的问题（不需要与电脑程序艾丽莎通常会问的问题相似，比如在“紫色大象和你的妈妈有什么联系？”）通过这种方法，你其实是在反复问自己：我是怎么想的，为什么我会这么想，为什么别人要在意我这么想？

问题：

* 我知道主要论点有哪些，但我不知道怎样把它们表达出来；
* 我不知道怎么把草稿变成成稿；
* 表达不够清楚；
* 无法找到一个清晰的结构。

好的写作一般都是不断写，不断改出来的。所以不要指望能够一步就把想法变成最终的文稿。先要把想法变成笔记，这一步一般比较容易。那么笔记和文稿的区别在哪里呢？通常情况下有这些方面的区别：结构、顺序和完整的句子。最关键的是要找到合适的结构首先是将各个想法联系起来的大框架，然后是论证每个想法或陈述每个想法的平行结构。

可以尝试以下组织想法的窍门：

* 思维导图。你把你的想法都画在纸上以后，就可以试着整理出它们之间的先后顺序。
* 把想法写在检索卡片上（一张一个想法），然后把它们分组或按某种结构摆放。用不同的方式来分类和摆放卡片可以帮助你发现，哪些想法是不符合整体框架的，哪些想法是需要着重强调的。
* 写作纲要：有经验的写作者往往会建议，列出一个具体的写作纲要应该是第一件必须做的事。列出不同种类的纲要会对你有帮助，这些纲要包括：内容大纲、标题加上相应部分的概要（以体现出论文的是“故事情节”）、标题加上对相应部分“角色”的描述（这部分是什么，它有什么作用，它如何为整个论证服务）等。

问题：为什么我用了很多笔墨去说明的问题我的导师只要简单儿句话就说清楚了？

解决这个问题就必须练习，练习写作和修改。记住简单原则。但也要认识到，简单并不是单纯的字数少一有时候多加几个词反而会使文章更加简单易懂。应该从论证结构上找问题的根源，并将结构作为你修改的重中之重。文章的混乱与不和谐往往是由于你不知道该保留哪些合适的东西，删除哪些不合适的东西，结果就是所有该使用的内容和不该使用的内容都被堆到了一起。

在你把稿子交给导师审阅之前，先过自己的修改“关”，找出所有重复多余的地方。在导师对你的论文进行了删改之后，分析导师的改动：哪些内容是可以省略的？为什么？你之前认为这些内容的作用是什么？

问题：如何培养学术写作的风格？

收集写作风格和作者的声音都很好的论文样本。分析这些收集来的样本：它们有什么共同点？它们的哪方面赢得了你的赞赏？它们的作者是怎么处理写作难点的？它们又是怎样强调和表达关键论点的？它们是怎样使用专业用语的？在你自己写作的时候，想象一下如果你是那些优秀论文的作者之一，那么你会怎么安排和陈述你的材料。找一下在你收集的论文里，是否有一个与你的论文具有可比性的段落，可以为你的论文提供模型框架。

问题：从表格上得出结果很容易，但是如何用文字来表述结果呢？

图表必须在文中被引用，但仅仅说：“结果在表2中”是不够的；表2必须在文章中被讨论到，表格的说明文字最好也能传达出讨论的主题。这并不是说，应该详尽地，一项一项地去描述表2及其在论文中的作用。表格体现了什么？你希望读者怎么去解读它，文章对它的讨论应该包含它所具有的，使你做出对其特定解释的关键特征。文章对表格的描述应该使表格与论文的整体论证结合起来。你想通过表格传达什么信息，文章对表格的描述应该总结表格的信息，并传达你的意图。

问题：写作风格前后不连贯（比如引用格式前后不连贯）。

这是修改时要注意的问题。风格是多种多样的，并常常是个人化的。关键的是：

* 要符合论文呈交场合的规范（期刊一般有风格方面的规定）；
* 一旦确定了你的风格，就要前后一致。

你可以在你的论文中选择使用一种引用格式，要选用你本人觉得最合理的，定下来后就不要变。

问题：交稿期限（总是无法在期限内完成）。

写作是件困难的事，会花去很长时间。一定要给自己留出比你估计的时间再多一倍的时间。考虑一下写论文可能需要多少时间，然后把这个数目乘以2，再将时间的单位按分钟、小时、天、周、年的顺序升一级，然后再加1。所以，如果我估计一篇文章5分钟就能完成的话，5分钟×2=10分钟，分钟升级为小时，即10小时，10小时再加1，即留出11小时也不过分。

交稿期限是个永远都要面对的问题。随着你学术事业的发展，会有越来越多的交稿期限，越来越多的责任需要你去承担。愤世嫉俗的读者甚至会认为，赶在交稿期限内完成任务的能力只会使体制把更多的任务交给你，直到你无法完成为止。熟悉权力政治的读者则会辩解说，这取决于你是否分清了体制的交稿期限与实际交稿期限的区别。我们在这里对此不作评论。
