# 陈述报告

这一章讨论的是“现场”陈述报告（presentation），比如研讨会或会议上的发言。这方面的某些问题与写作也有关系——比如，如何建设性地对待批评意见，不论是来自观众中的批评意见（“现场”陈述）还是评审人的批评意见（书面作品）。

在陈述报告时有两件事你必须注意。第一就是内容与形式的区别，第二是我们提到过的三条黄金法则：不要撒谎，不要故作幽默，以及最重要的一条不要惊慌失措而在压力下吐露真相。

## 内容与形式

内容与形式的区别可以用一句话来概括：“你说了什么（内容）不是全部，重要的是你是怎么说的（形式）。”内容是陈述报告的核心。如果没有什么值得一提的内容，那么你的陈述报告最多也就是起到了娱乐听众的作用。这对你的学术事业是有害的，你的同事们将根据你的研究想法和研究结果中包含了多少有意义的内容来评价你。在一所历史悠久的大学里曾经出现过这样的情况，发言人刚讲了十分钟就被一名听众打断，那名听众敲着桌子对他说：“你到底打不打算讲点值得一听的东西？如果你还要继续讲废话的话，我就走人了。”这应该不是你想要看到反应吧。关于内容的问题我们待会儿还会再讲。

形式对于口头陈述报告至关重要。形式可以在很大程度上说明你是怎样的人，以及你是怎样的研究者。很多关于演说的畅销书中提供了怎样穿着，怎样说话等细节性建议。不幸的是，教学、商业报告和研究报告的陈述要求与公共演讲的要求有所区别，所以你应该谨慎地根据不同情况遵守不同要求。

### 详细的内容

关于内容有很明确的原则。

大部分口头陈述报告都分为三部分。通常的建议是：“首先，告诉听众你将要讲什么，然后开始讲，最后告诉听众你刚才讲了什么。”这条建议一般很管用。开头部分决定讲话的总体基调，向听众解释你所要讲的话题为何重要，并为接下来的讲话内容作铺垫。第二部分包含了讲话的主要内容，是最长的部分。结尾部分总结你的发言。每个部分可以再分出若干个小部分，这要视讲话的规定长度来定。

**在内容方面容易犯的经典错误**

在内容方面容易犯的经典错误很多。其中之一就是错误判断你在规定时间内能够讲的内容。避免这个问题最好的办法就是事先演练讲话并给自己计时，然后根据情况添加或删除内容，再次演练，直到时间恰好为止。这种方法对于较短的陈述报告非常有效。如果发言时间较长，比如要一小时，那么反复演练会很累人，这种情况下更好的办法是在演练一遍之后根据需要调整材料的数量，并事先拟定一个计划：如果到时候时间不够，将略去哪些内容；时间有余，将添加哪些内容。

要控制好时间有一个小诀窍，你可以事先计划好在什么时候应该讲到哪个内容，并把计划好的讲话进度写在纸上（比如，“10:15，展示关于软件失败率的幻灯片”），做陈述报告时你就可以参考这页纸，以确认自己是否跟上了进度。对于较短的陈述报告，认真地进行演练可以有效地控制好时间。我们中有人曾在应聘时被要求做八分钟的陈述报告，能否掌握好时间也是考察的能力之一。我们的策略是在事先进行若干遍演练，调整材料，直到将陈述报告时间控制在七到九分钟之间。当真正的陈述报告到来时，我们故意不看表，而是通过观察听众的面部表情来估计还剩多少时间，结果我们在离规定结束时间还有几秒钟的时候完成了我们的陈述报告，并使听众感觉我们根本不需要看表就能掌握好时间，故意卖弄？是的。但这却给听众留下了好印象——大多数发言人在八分钟的时间段里就算看表也难以把握好时间，不看表就能控制好时间体现了我们具有专业级的技能。

涉及内容的经典问题还有很多。最常见的一个问题是如何选择难度适宜的材料来陈述报告。如果你的发言技术含量很高，而你的听众对你讲的领域却只有一点肤浅的了解，那么你的发言很可能会让他们感到百无聊赖。相反，如果你对一群内行讲很基本的东西，这将使听众和你自己都显得尴尬。最好的策略是与活动主办方联系，事先了解听众的程度。大多数的主办方都会很乐意帮助你，他们会认为你在事先询问体现了你具有高度的专业精神。

与此相关的一个问题是，关于你所要讲的话题，听众已经知道了多少。同样的，你应该询问会议组织者。这样一来，如果你得知你要讲的话题是听众熟悉的，你就可以在陈述报告中加人大抵的细节来显示你对该领域的了解，然后再把讲话的重心迅速转移到听众较为生疏的内容上去。

指导如何做商业报告和公共演说的文章往往强调，陈述报告必须要有趣味性。要达到趣味性又往往暗示着，技术细节必须减到最少，并且要用简单的英语讲。然而对于学术报告，这并不是明智之举。

如果你攻读博士学位，你要做的口头陈述报告会有两大类。第一类是作为丰富你简历的一项举措，给科学学科的硕士生或本科生授课。第二类是与其他研究人员的交流（比如研讨会、会议发言、内部进行的论文进度汇报，以及使人畏惧的论文答辩）。对这两类口头陈述报告的要求截然不同。

如果你给学生授课，你应该制作讲义发给他们。讲义上应该标注权威性的期刊文章、教科书或其他形式的信息来源，用它们来为你的课堂陈述报告提供支持。这是非常值得推荐的做法。另外，你还需要对相关领域做一个清晰、一致、简单并主流的概述，不必要的细节都可以略去，以使陈述报告更加清晰。不幸的是，现实中你所在领域的学说往往不是清晰、一致、简单的，所以你在上课时给学生讲授的那个版本虽然不是谎言，却也不可能是一幅完整的图像。

以其他研究人员为听众的陈述报告有非常不同的要求。这类陈述报告的目的是要展示（a）你了解研究领域的前沿知识，（b）自已处于研究领域的前沿，并且（c）在前沿研究中取得了一定成果，会对某些研究人员有帮助。要注意的是，你的听众往往不属于某些其他研究人员（比如在内部进行的论文进度汇报）。对于这类陈述报告，简化事实会对你有致命危险，试图将自己藏在主流思想后面更是不被允许的，因为你应该陈述报告的研究应该是前沿的、新近的，以至于学术界还未对其达成共识的。做这类陈述报告还要注意的一点是，你汇报研究成果的对象是一群专家，他们往往比你更熟悉内行人的门道，你可能会使他们产生对你的敌意（比如，你简化事实，于是惹他们不高兴了）。所以，你在选择内容方面应该非常谨慎。

### 具体的形式

这部分讨论你谈话内容的陈述报告方式。形式与内容在某些方面有重叠，但通常两者的区别是很明显的，也是很有用的。

听众在见到你之前事实上已经对你形成了一个印象。他们对你的印象有很多来源。比如在应聘面试前，他们一定已经读了你的简历。你的简历里是否有值得一提的成就，附信是否给人留下了好印象？在学术场合，听众们在你发言前至少已经知道了讲话题目，或许还读了一段发言稿摘要。你讲话的题目和摘要吸引人吗？它们是否恰当地代表了你和你的研究工作？事先做点功课会对你很有帮助。

听众们了解你的第二个途径就是听主持人的介绍。理想的介绍应该是这样子的，比如，“我们很高兴能请到琳达（Linda），相信在座的诸位已经通过她与克里斯（Chris）的合作对她的研究非常熟悉了。”较为不理想的情况是，负责把你介绍给听众的人不断地看提示卡片还把你的名字读错了。如果你的学术事业蒸蒸日上，那么你受到第一种介绍的可能性就会大大提高。

听众也会根据你的外表和行为来形成对你的印象。你的着装正式到什么程度？整沽吗？是否适合发言的场合？学术界的职位应聘通常会非常注意着装；而在普通的研讨会上，除非你把自己打扮得实在太怪异了，听众一般不会注意你穿什么，而是把注意力集中在你陈述报告的内容上。如果你不清楚发言场合的着装要求，弄清楚。观察来你们系的应聘人的穿着，观察系里讨论会上人们的穿着。请人喝杯咖啡，问问他们在这方面的意见。

**在形式方面容易犯的典型错误**

大部分没经验的发言者总是以紧张的微笑来开始他们的讲话，接着他们往往又会在使用视觉和听觉设备时遇到问题，把自己弄得更加尴尬。在事先熟悉一下你将要使用到的设备是个很好的主意——要尽可能掌握更多设备。另外，要做好设备出故障的准备，拥有后备方案——比如你在陈述报告时要用到PowerPoint，为了防止由于PowerPoint出故障而使你的发言不能继续，你应该另外准备一些使用高射投影仪播放的幻灯片，作为保险起见的后备方案。我们中有人曾担任过科学学科硕士论文的答辩评审人。该答辩包括每人15分钟的口头陈述报告。在一位考生做陈述报告时，高射投影仪出现了故障，于是更换了另一台高射投影仪，考生在这个过程中没有慌张失措，仍然继续陈述报告。第二台高射投影仪不一会儿也坏了，考生还是没有慌张，在第三台投影仪被换上时完成了他的陈述报告。就算是用专家们的苛刻标准来衡量，这名考生的表现也是不俗的，它传达出了很多正面信息。连遭两部机器故障的概率很低，但一部机器出现故障的可能性则不小，所以你应该有所准备，以便到时能够沉着应对。

你在陈述报告开始前常会先介绍自己，一般情况下你会向听众展示一张写有你姓名和所在院校的幻灯片，你可以借此机会调整设备的焦距，并给自己找到一个合适的站立位置。最典型的错误是站在观众和你的幻灯片之间，因为这样会使你自己的阴影投射到屏幕上，同时幻灯片上的表格又会投射到你整张脸上。你应该形成习惯站在屏幕的一侧，并利用自己的阴影来指示幻灯片上的部分内容。

新手往往会试图在一张幻灯片上写尽可能多的内容。你应该使用大号字体，以便坐在后排的人也能看清。同时你的幻灯片上必须要留出部分空白，使观众们不至于被过于密集的信息吓倒。值得推荐的做法是在幻灯片上就关键概念列出要点句，然后通过报告去解释这些要点句，而不是念幻灯片上的语句。

表格是口头陈述报告过程中经常出问题的环节：表格里的数字一般比较小，坐在最后一排的观众往往看不清楚。所以你应该在事先检查一下幻灯片的清晰度和大小。另一个值得推荐的做法是给听众发讲义来补充幻灯片的内容——大多数的听众喜欢一页涵盖所有关键点的总结材料加上一份所有幻灯片内容的复印件。幻灯片内容在纸上的尺寸应该便于听众们在上面记笔记。

要使最后一排的听众也听得清楚，你讲话时声音要响亮清楚。最好在讲话一开始就询问后面的听众是否听得清楚，但不要这么问：“后面的人听得到我说话吗？”要以免有些爱开玩笑的听众回答说：“很不幸，我们听得到。”新手往往在一开始大喊，几分钟后就变成了喃喃自语。避免这个问题的办法是在你的讲话进程表上注上一笔提醒自己（比如要“幻灯片2：开始喃喃自语了吗？”）。另一个更难掌握的办法，同时也是在很多情况下非常有用的办法，是观察你的听众的反应。

观察你的听众的反应指的是看着你的听众，并估计他们对你陈述报告的反应。

典型的坏现象是：

* 有人看窗外；
* 有人和周围的人说笑；
* 有人摇头；
* 后面几排有人为了听清楚你说了什么不得不前倾身子，伸长脖子；
* 后面几排有人询问周围的人幻灯片显示了什么；
* 有人看表或看钟。

典型的好现象是：

* 听众做笔记；
* 你发表某个观点时听众点头；
* 听众在看你的幻灯片或书面材料时与周围的人低声交谈，表现出饶有兴趣的样子；
* 听众很有兴趣地观看幻灯片或阅读你发放的书面材料。

你需要让观众感觉到，你是个专业人士，你对相关课题有透彻的掌握。你可以使用写作时也会用到的方法来传达这类正面信息。比如在你引用了一篇经典文献之后，你可以再顺带提一下对于这篇文献的较新、较深刻的评论，这个评论最好是除了学术界的重量级人物之外其他人很少了解的。

同时你也必须掌握如何组织材料这类基本技能。如果你使用高射投影仪放映幻灯片，那你就应该把幻灯片按次序放好。这可不像听上去那么简单。你必须把每张幻灯片从“未使用”这一叠取出，展示完后，再放到“已使用”那一叠。一个比较方便的习惯是从左到右放置：未使用的放在左边，已使用的放在右边，就像洗盘子的做法一样。然而，幻灯片有个毛病，它们常常会粘在一起，要把它们整齐地叠放起来同时又不影响说话的语速很困难。有时你需要再次展示一张已经用过的幻灯片，解决这个问题的办法是，如果你知道你要再次用到某一张幻灯片，就应该准备两份这张幻灯片的拷贝。

会议（包括学生会议）是观察不同陈述报告风格的极佳场所。涉及某些领域的会议，比如安全系统研究领域、学术界和工业、企业界的代表都会出席，观众们于是有机会见识一系列不同的代表用不同的风格陈述报告同一个课题。我们曾见到过这样的情形：一位著名学者穿着粉红色的鸡尾酒会礼服用PowerPoint完成了她高水准的发言，接着另一位身若穿旧了的粗花呢西服的著名学者上台，并开始用手写的幻灯片做陈述报告，那些幻灯片看起来就好像是在来开会的出租车上写的，字迹玄妙莫测。

## 其他小窍门

考察往往不是浪费时间的事。如果可能的话，在陈述报告开始前先检查一下场地，不但要从你的角度，还要从听众的角度来考察。从你的角度是要看看：有哪些设备，你会操作它们吗？你可以活动的空间有多大，比如你在屏幕的一侧展示幻灯片的空间有多大？地上有诸如电线之类的“绊脚石”吗？你是否可以清楚地看到观众，最后一排观众的面部表情你能看清吗？有地方放你的包和幻灯片吗？如果你使用高射投影仪放幻灯片，你将分别把“未使用”和“已使用”的两叠幻灯片放在哪里？

从观众的角度是要看看：从场地各个不同的位置是否都能看清屏幕？如果可见度不佳，而你还有时间的话，应该考虑将幻灯片内容的复印件发给观众，这样他们就不会错过任何信息了。另外，别忘了告诉观众你发的材料是幻灯片内容的复印件（很多观众在陈述报告结束前不会去阅读材料，或者只有当他们觉得陈述报告枯燥乏味时才会翻看材料）。屏幕是否有反光问题？

某些类型的陈述报告，比如应聘陈述报告，是具有竞争性的。在这种情况下，值得推荐的做法是思考一下别人可能会做什么，然后想出一种与别人不同，比别人更好的做法。别人会把重点放在哪些话题上？他们想不到，但你可以在陈述报告中使用的元素是什么？

做别人陈述报告的听众——比如参加系里的研讨会，也是一个获取陈述报告经验的很好的途径。即使讨论会的主题与你的研究毫无关系，它也值得你参加，因为你至少可以观察别人是怎么做陈述报告的。（当然你也很可能在未来某一天发现其他领域的某个方面对你自己的研究具有重大启示作用。）如果陈述报告内容你丝毫不感兴趣，那么你可以利用这个时间留意陈述者使用了哪些内行人的招数，或者犯了什么错误，这祥你就能够间接地改善自己的陈述报告风格。我们曾在一场关于鼠类研究的讨论会上学到了很多陈述报告技巧，尤其是怎样在别人提问前就积极地回避对自己不利的问题，而当时我们在研究的是在西方对阿拉伯世界的看法问题上媒体的影响。

参加别人的陈述报告会，尤其是在新学期的头两周参加此类活动，也是一个很好的机会，可以从中了解这类场合的礼节和惯例。看到别人因为一个幼稚的问题或幼稚的发言而被攻击是很痛苦的，但要比亲身经历这类情形好受多了。你也可以在这种场合了解到你的同辈研究员对于某些行为的看法，比如坐在听众席上睡着了（通常被认为是不礼貌的行为，但有时也被当做是对讲话人的蓄意侮辱），问一些带敌意的问题（有的认为这很不应该，还有的则认为这是一门艺术）以及坐在听众席上编织毛衣（对它的看法非常不明确，褒贬兼有）。

经常碰面的听众（比如在系里的讨论会上，或定期举行的高端会议上）往往表现出在外人看来不易理解的奇怪行为，这有群体动力和历史两方面的原因。比如一名资深学者可能会去攻击一个善良无辜的学生做的陈述报告，尽管陈述报告本身并不针对任何人，那名学者这样做的原因其实是因为他与学生导师之间有长期未化解的私仇。这又会导致学生导师的报复行动，于是没过多久，场面就变得好像一部意大利的美国西部片前一分钟还是慷懒的墨西哥午后，后一分钟却已是尸骸遍地。有意思的是，在座的其他听众并不知道会场上正在进行两方面的交火，因为攻击的火药藏在学术语言的背后，外人无法察觉。

### 如果有必要的话可以回避问题

你不需要反对批评意见。你可以说：“这是一个有意思的观点，据我所知，它在文献中提及得不多。”对方很难充分地反驳这句话又使自己出丑。你既显示出了自己的礼貌、开明、乐于接受别人的意见，又暗示了相关领域的研究通常会忽略对方提出的观点，而并不是你在这方面的失误。

如果听众的确指出了你研究中的一个缺陷，那么向他们表示感谢，回去以后检验他们的说法——他们可能是对的，如果是的话，你越早改正问题越好。在这种情况下，你可以请听众详细地阐明他们的观点，作为对他们提问的回应。他们有可能是错的，或只是随口说说，如果你礼貌地请他们展开他们的问题，你就能看出他们的建议是否是认真的，是否值得考虑。

### 常备安慰自己的食物和“疗伤”用的“绷带”

这个世界是不公平的。有时候即使你是对的，你仍然会遭到人们没有理由的不礼貌待遇。有时候你一下子想不出一个既聪明又正确的回答，有时候甚至要过上好几年你才能想出该怎么回击多年前的那个敌人。

有时候批评意见是正当的，比如，有一次我们写了一篇比较艰深的论文，是关于凯利方格技术的某个鲜为人知的方面的。我们在论文里没有引用凯利（原始文献），因为我们认为能写出这篇关于凯利方格技术的论文，这本身就已经说明了我们读过凯利的研究文献。有一名评审人指出这是个错误，他是对的。我们改正了这个错误，并再没有犯过类似的错误。

但有些时候，批评意见的公正程度就值得商榷了。以下是别人遇到过的事例：

* 某个会议上听众发言的第一句话是：“这是我听到过的最无知、最没内容的讲话。”
* 在博士答辩时一名校外评审人发问的第一句话是：“你能给我一个充足的理由，告诉我为什么我不应该用这篇论文来擦背吗？”
* 在一次会议上，观众席里有人极不礼貌地抱怨，他使用了演讲者推荐的方法却没有得到效果，另一名听众给他的建议是：“或许你应该尝试正确使用这种方法。”

被批评后，一个好的战略（一旦你脱离了险境）是在那天余下的时间里深深地同情自己，然后在食物和包扎伤口的＂绷带”中寻找慰藉——可以是一小杯雪利酒、一块巧克力、一部电影，或者任何其他东西。这种做法可以使你调整心态。到了第二天，你就可以问问自己，面对批评你该怎么办？你该怎样继续研究？这些批评公正吗？如果公正，你需要想出办法解决问题。如果不公正，你将在今后采取什么措施来降低受这类不公正批评的风险？要记住，寻求报复与最初的不公正一样，都会对你造成重大损失——在很多情况下，最好的办法是继续踏上追求财富和荣誉的征程，把你的敌人抛到脑后（你还可以这样安慰自己，如果你吸取教训，下一次你与你的敌人相遇时你就可以轻易地战胜他）。

关于战略和公平的最后一点：虽然这不是一个公平的世界，但世上仍有许多公平的人。如果你给别人的印象是你是一个工作成绩突出、人品优秀的人，而不是一个为了一点小事就苦苦寻求报复的人，那么经验丰富的学者可能会赏识你，发现你的才干，并把机会提供给你。那些把一辈子用在无意义的钩心斗角中的人是不大可能获得这样的机会的。

## 关于陈述报告的检测清单

* 陈述报告应该多大程度地探讨细节，你确认了吗？
* 陈述报告的听众已经了解了哪些信息，你确认了吗？
* 你演练了陈述报告吗？
* 听众能读懂你的幻灯片吗？
* 你知道该如何操作陈述报告时需要用到的视听设备吗？
* 你事先检查过陈述报告场地吗？
* 你准备了陈述报告进度表吗？
* 如果设备故障，你有后备方案吗？

## 在会议上陈述报告论文的一些小窍门

### 预防紧张情绪

* 做足准备：做好准备工作并不会使你不紧张，但它能帮助你克服紧张情绪。如果你事先进行了演练，获得了不错的反响，并通过演练改进了可能出现问题的环节，那么你在实际做陈述报告时就会自信很多。
* 提示卡片：如果你必须记住某些关键信息（比如重要文献及其作者的名字），那么你可以把它们写在一张提示卡片上（也就是关键事实和论点的清单），这样你陈述报告时如果需要就可以参考卡片上的信息。
* 预料到你的恐惧：把自己最担心的事都想一遍。可能会发生的最糟糕的情况是什么？你将怎样去面对这种情况？问问别人是怎样处理它们的。
* 找到一张友好的脸：如果你把陈述报告看做是与某个人一尤其是对你所说的感兴趣的人的一次谈话，那么你的陈述报告就比较有可能显得温暖亲切，类似于谈话。
* 停下来呼吸：在陈述报告过程中做短暂的停顿用来呼吸，你会感觉停顿时间很长，但观众却根本觉察不到。让自己停下来片刻是有必要的，它使你能镇定下来，组织思路，均匀呼吸。你的陈述报告会因此而更加出色。
* 自我介绍时告诉观众你是个学生：如果你真的很害怕，在自我介绍时可以告诉观众你还是个学生，他们可能会因此而对你比较宽容。比如，你可以感谢你的导师，这样观众就知道你还是个学生了，当然，如果合适的话，你也应该顺带感谢你研究的出资方。
* 研究过去陈述报告会上的听众提问：很多人会对不同的讲话人提同样的问题（比如研究方法、统计学、理论的应用，以及与某个理论的联系）。所以如果有机会的话，你应该了解一下你的听众是哪些人，事先考虑他们会针对你的陈述报告提出哪些与过去类似的问题，并考虑该怎样回答这些问题。
* 穿让你感到舒适的衣服：你在做陈述报告时要想的事情够多了，容不得因为鞋子夹脚或担心衣服不合适而分心。所以一定要穿上让自己感觉良好的衣服。

### 选择哪种类型的讲话稿？

人们使用不同类型的讲话稿或者笔记来引导他们的陈述报告。考虑一下哪一种类型的讲话稿能够最好地帮助你。

* 标题：各级标题应该是陈述报告中涉及的所有关键思想的提炼。它们能够对你的陈述报告起到提示作用。
* 笔记：人们会把要在陈述报告中表达的论点按照计划好的表达先后顺序用笔记的形式记录下来。有的直接在记录了标题的复印件上作摘要，添加上更加完整的信息，提示标题背后的的“故事”。还有的则将笔记与标题分开，单独拟定笔记，但仍在上面说明笔记内容与标题的联系。
* 完整的讲话稿：有人喜欢准备一份完整的讲话稿一一并不一定是为了照着读，而是为了在想不出说什么的时候有可以依靠的东西。
* 陈述报告时间表，了解各部分陈述报告将占去多少时间是个好主意，因为这样你就能推算出时间过去一半时你应该已经讲了多少东西等等。如果你准备了讲话稿，或一系列笔记或按顺序排列的一组标题，你应该在上面注上各部分用去的时间。这样你在做陈述报告时就能掌握和控制自己的进度了。

### 对付提问

* 练习：如果你已经在小型研讨会上陈述报告过你的论文，那么你一定已经遇到过一些提问，并已经有了在“身临现场”的体验，这将对你很有帮助。
* 问题的规律性：在研讨会上或在别人做陈述报告时，留意听众一般会提出哪些类型的问题，试着从中找出规律。这会给你提供一个基础，使你能够较有效地预测别人在听了你的陈述报告后将提什么问题，你也就能够事先准备问题的答案了。
* 提问涉及你不熟悉的文献时如何防卫：如果你没有听说过提问者要求你做出评论的某部文献，可以把问题重新抛给提问者：“我不熟悉那篇论文，它的作者提出了什么观点？”或者你也可以通过一个问题将它与你熟悉的文献联系起来：“我不熟悉那篇论文，它是属于人工智能还是属于实证研究？”不要不懂装懂。记得在会后向提问者询问那部文献的出处。
* 对于技术性过高的问题可以在会后个别回答。（这个问题很有趣，但我无法给你一个简短的回答。我们能在休息时间讨论吗？）
* 没听明白的问题：如果你不确定自己听懂了问题，那么可以把问题按你的理解重新组织一下：“如果我听得没错的话，你是在问我如果……”然后给出你的回答。如果你根本没有听懂问题，可以要求提问者再问一遍——他或她在第二遍时可能会把问题说得简单一些。
* 很长的问题：准备好纸和笔。如果有观众提了一个由多部分组成的问题，或者借提问的机会长篇大论，那么做点笔记会帮助你记住在回答时要说的话。
* 怪异的问题：与对待技术性过高的问题一样处理这类问题，可以说些类似这样的话：“这点很有趣，我之前没有太多思考过这个问题。我回去后会对它做一些考证和研究。”千万不要提议在休息时间与提问者讨论。

让别人帮你记下听众的问题，最好连同提问者的姓名一起记下来。你不可能凭记忆记住所有问题，你或许也没有时间记笔记。一般来说，做好准备随时记笔记是个好主意——记下你要在今后建立联络的人、特别好的观点（听众的以及你自己的），或者你要在今后探究的问题。
