# 答辩

答辩对博士生来说很重要。答辩是你的博士阶段的两个重要成就之一，如果你写的论文和你的答辩都足够好，你才能拿到博士学位。如果不好，那就拿不到。没什么别的会对博士学位的取得起作用——不管你曾多么努力地工作过，或者你有多聪明，你多么在乎你的论题，这个论题对世界有多重要，你为之承受了多少苦难，你有多么想拿到博士学位。很有可能你写了一篇不错的学位论文，但是表现不佳的答辩却给你带来灾难性的后果。答辩如此重要，你应该为答辩做些什么呢？

第一件事情就是站在评审人的角度理解答辩的目的。博士学位是表明你已经值得被学术圈接纳的一个标志。用做橱柜来比喻，如果你制作的橱柜足够好的话，在此后你就可以脱离学徒身份成为一个羽翼丰满能够独立1作的木匠。上述两种说法的关键都在于两者皆不包含要完成得尽善尽美的意思。博士未必是“完美无缺的”。他们足够好就行了。“足够好”意味着你已经证明自己具有在你的学科中进行专业研究的必需技能。“足够好”的程度会很高，但是与完美无缺还很不同。没有人会期待你的论文完美无缺。从定义上来说，当你的工作涉及新的发现，就会有不确定性，没有绝对正确的答案。你的工作只能建立在前人工作的基础之上，建立在已经确立的技术基础之上；所有的这些最终都源自于估算、假设以及在这个领域内的共识，而不是绝对事实。部分成熟的专业研究者将会接受这种不确定性，并以一种在掌控之中的合适的状况来对待它。有时候不确定性是整个研究的关键点，但是另一种情况下你不得不接受，你必须在不确定性中工作，在一个可以预知的未来，这种不确定性可能无法证明清楚。

这种令人振奋的思想的最大意义就是暗示，你的论文中可以包含存疑的东西。这些存疑的东西给那些全面检验你的论文，验证你的技能的广泛程度的评议人提供了一个出发点。他们不想要论证不严密的意外发现。他们想得到保证：你对你的领域的掌控程度是经得起检验的。他们并不想看到，因为你的导师出于对你的绝对无私的爱护己代你写出了全部内容，所以你的论文精彩绝伦。他们不希望发现，由于你从未思考过某个显而易见的结论，所以你的论文没有提到它，而不是因为你认为这个结论太显而易见、不值一提而未在文中提及。

## 论证不严密的意外发现

### 蘑菇的故事

蘑菇的故事说的是一个农学的学生，他的本科论文包括观察农场中蘑菇的生长（很少有人感兴趣的主题），但是对于种蘑菇的农场主而言则是相当重要。出乎他意料的是，蘑菇并不是持续生长或者以天为周期生长，蘑菇的生长周期以小时计。这个发现是出乎意料的，他继续在博士论文做这个课题，提供了大量的数据和分析资料。答辩的日子到了，校外评审人提问的时间也就不声不响地到来，这位评议人轻轻地问了一句话但是却掷地有声，他的问题是：“我认为你让蘑菇棚里的中央供暖时开时关，是这样吗？”几秒钟可怕的沉默后，众人达成一致，答辩推迟，直到这个学生做一个后续的研究来证明这个结果不是由于中央供暖频繁开关所引起的。后续研究如预料之中的让人生厌：学生花了好几年时间在蘑菇大棚里测量中央供暖多长时间开关的频率。

### 啄木鸟的故事

安全头盔的开发者们决定到自然中寻找新设计方案的灵感。他们中的一个人想知道是否有某种动物，在头部经受了有力打击之后，还不会感到痛苦或者遭遇脑损伤。灵感来了，是啄木鸟。在啄木鸟醒着的时候，它大量的时间都用在用相当大的力量来敲击树木，这样会对头部造成撞击。小组因此研究啄木鸟的身体结构，发现在头和喙相连的部分有海绵状器官，吸收了部分撞击的力扯．小组应用这一灵感设计出一款头盔，此设计不是为防止物体击穿头盔，而是通过将头盔变形的方式，将头盔设计为可以吸收来自突然袭击的力董，吸收正在朝向佩戴者头部的大量能量。设计者很自豪地展示了他们的设计理念。故事中，在这个时候，观众中的一员问：“你怎么就知道啄木鸟不会头疼呢？”接下来就是痛苦的沉默。

在蘑菇的故事中，学生没能识别出相关的变量（中央供暖）。在啄木鸟的故事中，设计小组没有检测关键性假设（啄木鸟不会脑损伤）。事实上，啄木鸟的故事有一个很好的结局，现有的设计被证明是好的，设计者是对的，尽管如此，就我们所知，还没有人检测到啄木鸟的脑损伤率口然而，在另一个案例中，未经检验的假设导致数年时间浪费在无意义的研究上，这么长的时间本可以用在更有用的研究领域。

大多数学生都会收集答辩的恐怖故事，这些故事使他们噩梦不断。在我们的经历中，答辩中遭受失败的人是很少的，而且失败似乎只归咎于两件事情：

1. 学生不听自己导师的建议，也不听其领域内的任何别的导师关于答辩的建议。
1. 导师和学生之间的关系破裂，学生还不想办法去补救。

因此，答辩中的失败在原则上是可以避免的，以下是两项保护性措施：

1. 听从导师的建议。
1. 建立起有效的人际关系网，在答辩之前，通过专题讨论会或者出版的方式展示你的研究工作，这样你的疏漏就会尽早得到警告。

## 校外评审人

假设校外评审人正在检查你是否学会了怎样做“橱柜”，他们会怎样开始着手呢？

正常情况下，在你见到他们之前故事就已经开始了。在你博士生涯的某一时刻，你和你的导师要选择一个校外评审人。对于一些博士，这件事情在他们上博士之前就已经开始；对于其他博土，则在开始写作的时候才开始。对于大多数人，则在读博士的最后一年左右。在选择校外评审的时候有不同的因素。他们不应该和你有利害关系举例说来，如果他们和你合作申请诺贝尔奖，那么他们就有现实的动机保证你的论文通过，不管你的真实水平如何。

选定校外评审后，评审们的日子还会正常继续，直到你的论文和相关的评审表格放到邮筒里。他们会怎样处理你的论文和相关表格呢？那取决于不同情况。大多数校外评议会详细阅读论文至少一次。很多人会逐行阅读，逐页作记录。他们会很认真地阅读参考文献和附录。他们会检查参考书目，或者看起来并不正确的观点。他们或者会在某部参考文献上作记号，因为这本书十分有趣。然后接着向前翻看。也有另外一种情况，总是不断会有关于校外评审的故事，说他们在来参加答辩的火车上才读论文。不管怎样，你希望他们的内心反应是一样的：你希望他们在思考的时候带着善意并认为你的论文还不坏。因此，想办法使他们第一次看到论文就觉得是一篇可靠的文章——每一页，从包括导论的第二页、参考书目、结论都是可靠的。

评审人通常会先独自阅读这篇论文，然后互相联系并讨论论文。他们只有很有限的选择；你得到学位还是得不到学位，你不会得到像学年课程一样百分制的分数。尽管结果简单，评估体系还是很复杂的。评审人可能会不提任何意见就让你的论文通过（这种情况很少有，但是你肯定不知道怎么回事）；他们也可能完全不让论文通过（你也不会知道怎么回事）；他们可能会认为该论文可以授予研究硕±；或者是更通常的情况，论文做一些更严格的修改后他们就能允许论文通过。如果他们都一致同意论文一次直接就通过，或者不通过，或者直接获得研究硕士，那么他们的工作就太简单了；然而，更常见的情况，是需要做一些修改，这意味若评审人必须讨论需要怎样修改。这是一件耗时且烦人的工作，特别是如果你的论文很滥或者书写很差而需要改动。经过这些之后，他们会需要在答辩本身的游戏计划中达成一致——注意，他们不是简单地给你一张修改清单。如果出现了这样的事情，例如说，问题显然出在你使用了不常用的名词，那么这种变化可能仅仅是放人一段插入语，用来解释你说的就是那个大家都知道的名词。反之，如果答辩显示出你的主体部分存在极大的不可原谅的疏忽，那么最初的小的改动计划会变成大的计划，甚至是论文不予通过。

## 开放的舞台

通常，在答辩之前，考官们会在系里聚一次，开一个答辩前会议，确定他们的行动计划。在这种场合下，他们通常不会对见你有多大兴趣。这和私人感情无关：他们有工作要做，必须集中精力在工作上。诸多答辩都在下午举行，给考官们留足时间到达答辩地点，在这些案例中，正常情况下，答辩之前，你的导师会请老师们共进午餐。他们或许不会邀请你：这是礼节，并不是怠慢你。（如果你在上午面对他们进行了成功的答辩，你或许会被邀请参加午宴，但那是完全不同的）。经常会有一些有关人际关系的谣传，导师会在午宴时给校外评审人多劝儿杯酒，保证他们有一个好心情，如果真有这么回事，那就是例外。当他们准备好时，你就会被召唤进入房间内，如果你有什么地方和大多数准博士相似的地方，就是看起来真的很紧张。

### 开放的开场白

由于你可能非常紧张，大多数评审人会努力让你放松。既然答辩通常都安排在系内，很多校外评审人只是作为参与者，开场白就没有必要像传统的会议那样用很多的时间问评审人是否旅行愉快之类的问题。他们的自我介绍和答辩流程介绍都会较快结束。开场白可以有各种形式，对你来说都很容易通过，大多数的开场白是轻松的，而不是被那些神经紧张的答辩者所误传的。

一个开场白的例子就是校外评审人给你几张A4的纸，纸上列出他们发现的打印错误。你很容易认为这是评审人错过了你的论文的大的逻辑点，而吹毛求疵地找茬儿。事实上，根本不是这么回事。这实际上是一种礼节。一方面，这表示评审人真的如你恭维的那样，在百忙之际抽出时间细心阅读了每一页内容，他们真的发现在第174页你的拼写小错误。另一方面，更好的是，当你订正论文的时候有那样的清单，总比人家告诉你论文中有大橇的错误有待修正但是却不告诉你在哪好。第三个方面是，在一些案例中，评审人仅仅问几个象征性的问题，使用这些打字错误的勘误表作为一种非直接的表达方式来解释你的这篇论文很好，仅仅需要很细微的修正就足够。（在这些案例中，勘误表是一种间接方式说明他们只有做一些微小改动的选择，并不是因为他们太懒而不愿做别的事悄。）

另一种广泛应用的开场白就是评审人对着提纲来谈谈你的论文多有趣或者多有可读性。这样的开场白可能由不同的评审人来说效果可能也不同。对于一些学者而言，“可读性”是一种低级的侮辱，仅仅指代那些流行文学的学者写的东西。对于其他人，可读性是一种恭维，意味着你写的东西能让人明白，而非艰涩难懂。那么你怎样判断是褒是贬呢？一个判断因素是评审人的声誉，如果他们恰好是偏好使用艰涩语言的学者，那么你或许就遇到了麻烦。如果评审人以体谅的心情，那么你或许会有一个轻松的开始。尽管如此，值得记住的是就算是最体贴的评审人也是一个专业学者，会严肃对待答辩。如果你遇到这样的开场白，一个相对安全的回答就是干笑，用一种礼貌的声调说“谢谢”，表示你不是傻子。

第三个可能会误导你的开场白是让你给你的论文做大略的概述。对这样的要求一个完全可以理解的反应就是愤怒：当然，如果评审人阅读过你的论文的全文，他们还需要简单的概述吗？再一次说明，不是这样。概述是让一个紧张的候选人放松的最好的方式，他们通常沉浸在话题中，然后忘记了紧张。这也是告诉评审人这篇论文中你觉得最重要部分的机会，这样可以让评审人知道你有多么地专业。在一些案例中，如果论文的写作方式晦涩或者以一种不可读的风格出现，概述论文对于发现论文的意图就很有用。经常发生的情况是，一篇论文会包含着看起来很好的内容，但是组织结构混乱，叙述也不够好。如果内容够好，那么一点技巧性的修改就会给论文带来让人惊喜的变化，如果内容和风格都不怎么样，那么你就无法通过答辩了。无论是上述哪种情况，这种开放的开场白都将有助于评审人做决定。

在这个阶段，说出你做错事情的真相，打破第三个黄金法则是很容易犯的错误。但是不要屈服于任何诱惑。相反，清楚地说出事先准备好的论文概述，列出主要发现和主要贡献。你或者会用几句你自己的话去表示你知道游戏规则——小心谨慎地参考最近一篇核心期刊上的文章，或者是这个领域研究正在进行中的主要数据。尽管如此，别做过了头，记住你是一个候选人，不是一个评审人。

### 中场游戏

在开放式交流之后，真正答辩开始了。从结果来看，评审人有四个主要的选择：（1）直接通过，（2）做一些微小改动，然后通过，（3）做大的改动后通过，（4）不通过。从他们怎样对待答辩本身的意义来说，他们有更多的选择，要记住的是：答辩对你来说感觉起来像是严厉的质询，但是通常都以直接通过结束。

直接通过
:   这是一个让人心情舒畅的结尾。评审人从一开始就清楚直接通过是亳无疑问的事情，对他们而言只是如何把握进度的问题，他们在同你的导师到酒吧吃饭或者喝咖啡之前，出于礼节问你几个问题。他们或许会因为格式的原因，让你修正三四处文字错误。如果你有个好导师，这种情况通常都会发生，你和你的导师都知道这个游戏怎么玩，你们在论文上已经从头到尾做好了工作。

微小的改动
:   在接下来的答辩进程中，他们问你几个技术性问题检验你的专业水准，你或许不能回答出所有的问题，也不能完全符合他们的标准。不要让那些事情影响到你：没有人能明智回答所有的问题或者读过所有相关的书籍。以下就是个这样的例子，你已经做了关于人类错误类型的新的分类的博士学位论文，你已经阅读了重要著作。你已经通过查阅正式的生物学分类的文献进行了更进一步的阅读。校外的评审人问你阅读时是否使用了分类的多维统计法。你还没有，你该做什么呢？在一开始，你不应该惊慌。你可以礼貌地询问他们认为多维统计方法会给这个领域提供什么。然后你会和他们进人一场争论之中，这些争论最主要的一点就是让你证明你的能力。如果你在争论之中举了好的案例，你或许被要求增加一句话说明你选择的不是多维统计方法，并且给出不使用这种方法的理由，这就是小的改动。

大的改动
:   评审人提出的问题使你暴露出你的重大疏忽。这其中很好的例子就来自于统计学。假设你已经观察到不同组对大众媒体如何报道车祸的不同看法，并且收集了一些数据，你把这些写到一张整齐的表格上，并且在你的讨论中提到其中两组的观点有显著区别，并且另一项发现具有高度显著性。评审人在你的论文中看到了这一点，然后校外评审人提出质疑说你用了“显著”和“高度显著性”这两个词，但是却未提到你所做的测试或者相关的p值。

    对于这一质疑，没有什么回答是好的选择。最坏的是，你告诉他们你使用了什么测试，p值是多少；评审人会暗地里怀疑你是在论文中删除掉这些信息的傻瓜，并且会进一步寻找你的傻瓜行为的迹象。另外其他两个选择和这个一样的糟糕。其中一个是你告诉他们你仅仅使用定性的方法而原则上不赞成定量的方法，那么就会被一个选择定量方法的考官看成是傻子，认为你只会收集数据而不会进行定量分析。

    最后的选择包括你承认你从未听说过统计检验和p值，并询问p值到底有什么重要性。这种方法在某些学科或许是完全可以接受的，但是在统计学作为核心技能的学科中（例如试验心理学），结果就会很糟。如果你对校外评审人提出的问题承认全然无知，并且就此结束回答，那么你在校外评审人的选择上、在学科或者对你的学科的方法论的选择上已经犯了严重错误。对于后两个选择你能希望的最好的结果就是做一些非常认真的修改。假如你费尽九牛二虎之力终于摆脱这一质疑，那么也无法挽回答辩会议从一个完全例行公事的审查转到慎重研究你是否能通过的答辩，你的结局很可能是不通过。

不通过
:   答辩遇到的最糟糕的极端情况就是评审人认为你的论文一团糟，加上你在答辩时表现出来的无礼、无知甚至愚蠢。通常情况下（但不是绝对的），这些案例发生在学生不听导师的建议提交论文的时候。典型的例子是非全日制的博士生，作为忙碌的经理之类的在职人员，他们的工作不能受影响，只好把论文主题建立在教科书和职业杂志阅读基础之上的拼凑，还设计了糟糕的调查问卷以及答辩设计，还认为“得到这些内容非常容易，丝亳没有问题”。这样的案例是无可救药的。文献综述太过简单以至于不能导出一个有趣的研究问题；方法太枯燥以至于不能形成良好创作的基础；因为方法论上的缺陷，数据可能根本不可靠。这种工作注定是要失败的，并且失败了也是活该。

游戏结束
:   在评审会即将结束的时候，评审人通常需要互相商议，达成一致并作出决定。他们会礼貌地让你离开，当你在走廊里紧张的走来走去的时候，评审人会做他们该做的事情。

    评审人做的事情就是互相商置，达成一致意见，并且有回旋的余地。如果你的论文是明确的通过或者不通过，那么他们会明确地表态他们都同意。如果确定通过，那么他们不会在你离开30秒钟后立即招呼你回来，很多评审人认为让答辩者在门外等几分钟是一件好事情，这可以增强答辩者的心理承受力。

    如果大家达成共识认为你必须做一些修改，好的评审人会列出一张清单，这或许是一张手写的清单，或者是一份在一两天之后用电子邮件发给你的清单。

    如果没有达成共识，那么评审人必须在他们自己中间协调一致。在这个时候．你之前的其他努力会体现其价值，例如．如果你写了大量的不错的期刊文章，那么这证明你的工作质量有足够的专业性的．就算毕业论文写得不怎么样，对任何一个想说明你的论文有不错内容的人而言这都会增加你的筹码。同样，如果你写了一份很好的文献综述，就算你的数据收集有一点不完整，那么也能表示你已具备本领域内的专业知识。这两个例子中都需要工作尽早开始，都不是你能在最后一周进行修补的工作。在你做博士的一年或者之前的时间，阅读你的机构内部的规则．让一些人帮忙把他翻译成英语，这样你能找到在这些论文中可接受质量的标准。例如，如果有关“同行评议期刊发表标准”，在这种期刊上发表文章会在答辩之后裁决有争议的时候帮助你。

    在所有这些完成之后，评审人会就你的下一阶段事项和你的导师达成一致，并且把你叫回来。如果你能通过，他们会向你表示祝贺。这时你的朋友可能已经准备好了香殡。这一天会过得很充实，你生命中接下来的日子将会阳光灿烂。

## 答辩之前

在你做博士论文的早期，应该和你的导师讨论一下是否应该想办法在期刊上发表一两篇文章。在这个问题上，要根据不同导师和不同学科来定。在你写作的时候，要有足够的时间做出像样的工作，特别要对于那些能在论文中展示你“制造橱柜”技能的事情予以特别关注。用一种理性的方式选择一个合适的校外评审人：在你生涯的这一阶段，你应该对游戏规则以及相关人员有一个理性的概念。

### 答辩前一周

在答辩前一周，重新通读你的论文和数据，加上一些关键的文献。你或许在这个阶段前很长时间就已经对此感到恶心和厌倦，那么修改完论文后就用巧克力或者其他令人愉悦的东西来奖励自己。组织一次模拟答辩。模拟答辩包括开始的陈述部分，至少有一个模拟评审人。这个评审人要知道优秀的答辩和陈述的技能。如果他们是合格的，他们会知道在模拟答辩中用不着跟你客气，他们会给你一些建设性的意见以及反馈，告诉你在正式答辩的那一天怎么做。

### 答辩前一天

答辩的前一天，确认你在何时何地举行答辩（或许在最后一分钟地点会发生变化）。在答辩当日找一个可靠的朋友让你随叫随到。在前一天晚上不要出去喝的酪酐大醉：你需要在那一天保持清醒。确认你了解评审人的名字、头衔以及主要著作。这不是在让你去卑躬屈膝地献媚，这是让你表示专业礼节并且提升你朝着他们期待的方向回答问题的机会。确定你准备好了合适的干净衣服以及若于论文的副本。礼貌地问你的导师论文副本是否还需要任何改动，以防你在兴奋之中遗忘了事情。

### 答辩当天

答辩当天时间显得很长，当你在等待的时候要有些事情可做。如果你没有被介绍给评审人，没有被邀请和他们一起共进午餐或者是答辩会开始之前你一直在等待，不要感觉到自己受了委屈。所有这些都是答辩的过程中最正常的事情，并不能反映不礼貌或者没有效率。例如，你或许需要一直等着是因为某些傻瓜“非法”使用答辩的教室用于开非正式的讨论班，需要先把他们赶走，再让评审人去重新摆桌椅。

在答辩开始的时候，如果需要的话，礼貌地做你的准备并且保持安静。如果你没有被要求做陈述或者概述，也不要烦恼：模拟答辩的时间没被浪费，因为这会有助于你在答辩期间非常有效地整理你关于全篇论文的思路。

答辩很像击剑训练，答辩会用来评估你的击剑技巧，你需要用防御的方式证明你的剑术技巧。你既不需要让你的对手每一次都击中，也不会有人期待你能把你的对手一次扎个窟隆，然后一直扎到死。重要的是你怎样回答问题．不是你是否恰好知道正确的答案。在这个意义上，通常没有一个明确的标准答案。

另外，你没有必要立刻回答。你可以使用技巧给自己争取一些思考时间，诸如，用一种思考的方式说“嗯”，说“那是个有趣的问题”或“我需要考虑一下”等。

### 答辩之后

答辩之后，确证你没有从地球上消失；借用一个朋友的办公室休息片刻是一个好主意，但要确保人知道你在哪里，这样可以避免评审人到处找你。如果你没通过，平静地接受这个事实，保持礼貌并且阅读本书关于如果答辩不通过怎么办的章节。简而言之，离开教室并且在余下的日子里表示遗憾，然后收集一些理性建议并且为次日做计划——尽管如此，从统计数据来看，大部分人需要把论文的一些内容作些改变，然后才能通过。在这个阶段争论怎样修改是不明智的。相反，你应该感谢对你的论文提出的修改意见，礼貌地感谢评审人和你的导师然后再去庆祝。不要着急记住所有的修改；在此前你的导师应该已经安排好了，评审委员会将有一个清楚的修改清单，你次日就可以从他们那里拿到。如果你不需要改动就通过，那么一定要感谢你的导师。你现在可以出去开怀畅饮，或者去做你喜欢的任何事情来庆祝。

## 处理修改工作

答辩后的一天，你或许还有点宿醉，但你必须要出现在导师的门口，清楚地了解你还要做什么，何时必须做完。有一部分博士候选人忽视了这一阶段的工作。做一些修改是费时费力，但是比不通过答辩要好得多。列出一个清楚的时间安排表，用一段连续的时间，把修改工作做好。如果你想先休息，那就取决于你自己，但是不要把修改这件事情遗忘，抓紧时间去完成修改并且得到导师认可。写一封说明信详细阐述你在哪一部分做了改动，是如何改动的——这使得评审人更容易检查你需要修改的每一项内容。在大多数机构中，细节的改动只需要反馈给主评审人，但是如果有大的修改，就需要给答辩委员会全体成员每人一份，对于每一个参与此项工作的人而言，一封说明信会让工作变得更简单。

在答辩中或者答辩后，你需要具体弄清楚评审人需要你做的改动。哪一章？一章中的哪一节？一节中的哪一段需要改动？他们能否举例说明修改所要达到的要求？

你还需要查明修改提交的截止日期，不要指望所有的事情会在截止日期前五分钟会做完。你需要就修改问题和你的导师取得联系，在你修改之后，给你的导师足够的时间去检查你的修改。你最好在截止日期前几天上交修改版，因为极有可能你想在截止日期的前一天拿修改版给导师检查，但就在最后一分钟，你的打印机坏了，或者你的导师又发现了一个致命的错误，而这错误的修改需要数天的时间。

对于一些学生而言，可能会对这样的修改产生强烈的反感，要注意调整好情绪，可以向朋友倾诉并寻求支持。

一旦你的修改得到批准，你就可以做毕业的准备了。大多数机构都会允许你在毕业典礼上请两个客人。许多博士候选人都希望有一张好的穿博士服的照片，那么可去租借一周学位服（比租借一天要明智得多）。然后就可以拍一些好看的照片了。

所有的这些结束之后，你或者再也不想看一遍你的论文，甚至恨不得把它烧成灰。别那么做．这篇论文就像一张面具：你只看见了里面的缺点，而外面的人看到的是它闪闪发亮的外表。

## 答辩的一些注意事项

尽管答辩很神圣，到你到达答辩的时候，你已经完成了最艰难的部分。记住一点：答辩的结果只有通过和不通过。大多数考官都在寻找一个理由让博士候选者通过。你的工作就是让他们的寻找变得容易口完美不需要，但能力必须有。

### 你在答辩中做什么？

* 表现出对学术系统和学科的尊重。
* 表现出自己精通这个领域和该领域的智力工具。
* 证明自己的研究思考独立完成。
* 参加学术讨论。

### 导致答辩会失败的原因

* 认定答辩不是什么大不了的事情。
* 对于任何有关你所做的事情的回答都是要“我导师让我做的”。
* 回答时只用简单的一个词语。
* 表现出不让步的态度。
* 态度极端傲慢无礼。
* 表现出缺少兴趣。
* 无法清楚描述你自己做的工作。
* 无法给最基本的术语下定义。
* 无法对你所引用的学术论文加以评论。
* 对考官无礼并直呼其名。

这些都是经过检验的方法，我们已经看到学生们因为这些原因失败。

不要把时间浪费在揣测评审人的心理上。一个教授给我们讲了一个聪明学生的故事，学生看到他在备忘录中写上“失败”，就认为自已在答辩的后半部分彻底被判了死刑。教授不明白为什么这个学生先前的答辩毫无瑕疵，而后半场忽然大失水准。所以答辩后他问这个学生原因，学生说是因为看到教授写下“失败”二字，认为自己答辩没有希望通过了。而事实上教授只不过认为该学生回答中某一个有趣的假设无法成立，才在笔记本上随意写下了“失败”二字。

### 怎样打动评审人

* 来之前就精心准备。
* 认真聆听，理解问题并且直接表达。
* 进行目光交流。
* 表示出对你的工作的热情。
* 在一个更大的背景下看你的工作。
* 在回答问题时，能够直接指出问题针对的是论文中那一段落（强调关键段落）。
* 能够直接精确地说出引用的研讨会。
* 能够清楚地说出你的贡献的本质和大小。
* 除了自己的研究之外，对于未来的工作具有前轮性思考和达议。
* 深思熟虑能够清楚表达自己的工作什么是好的，什么是需要提高的，以及怎样提高。

这些也都是实验过的并且是好的方法。那些对自己的材料了如指掌的人，那些答辩时专注，充满知识、兴趣，并且礼貌的人会让人印象深刻，尽管他们也会犯一些错误，或者偶尔答的支支吾吾。评审人喜欢活泼且有趣的答辩者。

### 准备

毋庸置疑，对答辩的最好准备就是写出一篇好的论文。

* 标注你的论文，在你最想提的那些页面放上在“书签”（贴上注释或者类似的东西）。
* 判断一下是否需要相关的文件（例如关键性文章、数据示例），这些不包括在你的论文之内。你也可能根本不会用到这些东西，但是或者将这些材料准备好会让你感到安心。
* 在头脑中过一遍那些答辩时一般会问的问题，并且思考答案。
* 列出你最害怕的问题的清单，并为它们设计答案。
* 让有经验的人为你做一次模拟答辩，然后让他们说出什么地方表现较好，什么地方还有持进一步提高。（要知道，模拟答辩通常比正式答辩要难一些；模拟评审人经常会扮演极苛刻的角色，这样你才能知道如何做好最坏的打算）
* 浏览一下你的五个关键参考文献。如果在你没有记住足够多的参考文献信息，那么就在参考文献旁作注解：他们做了什么，为什么重要，你的作品在什么地方和这些论文相关，这些论文对你的作品的启发。准备好使用作者名来指代这些关键论文。
* 浏览一下你的评审人的作品，注意他们的研究领域、研究方法和研究风格。
* 如果已经用足够的时间做好了准备，在前一天做一些完全放松的事情：运动，沿着海岸步行，看最喜欢的经典电影，全身按摩等。但这不包括过度饮酒、过度运动和任何让你第二天状态不好的活动。
* 答辩前一夜睡个好觉。

### 战胜恐慌

* 暂停，让你有时间思考。
* 深呼吸，三次深度透彻心脾的呼吸，确保你的呼气缓慢，通常是有帮助的。
* 喝一点水：桌子上通常都放着水。
* 快一些做笔记。

如果你没有听懂某个问题或者不知道答案：

* 让评审人重复一下问题（他们有可能将问题简化）。当你第一次没有抓住问题主旨的时候，这就是最好的机会。
* 给考官转述一下问题：“我想您问我的是一个有关XX的问题，答案就是……”
* 给一个选择性的解释，是“我不清楚你的指的是X还是Y，您能区分一下吗？”
* 给问题提供一个解释比说“我不知道”要好得多，但是，你只能这样做一两次。

尽量保持简单。当你听到自己把一样的话说到第三次，停下来微笑一下“对不起，我重复一下自己的话”。我们都很紧张。在答辩中万一你无法控制自己的紧张情绪，你就应该完全放松一下僵硬的嘴唇然后说一些诸如“对不起，我感到很紧张，我需要一点时间……”之类的话。评审人通常会考虑一下，然后在正式开始之前问你一些热身问题。

### 评审人的问题

* 让你平静下来的热身问题：经常以这种形式出现，“你是怎么开始这个主题的研究的呢？”或者是“你能为我们归纳一下你的论文的核心观点吗？”
* 让你证明自已知识的证实性问题：通常是要求你阐述或者解释你论文中的一些内容。
* 深度证实性问题；让你证明你的知识深度不仅仅限于表面。保持头脑清醒继续就这些问题作出陈述。
* 确认理解是否有误的问题：这些问题帮助评审人检验他们自己对你的工作的理解是否有误。
* 学术问题：让你证明你对自己的领域和研究都很熟悉。
* 挽救性问题：如果你所写的一些东西出了差错，至少让你有机会表示你知道你问题所在以及如何弥补。
* 递进式问题：可以帮助评审人了解你对自己的知识掌握的深度。
* “这很好”问题：就是给评审人一个机会讨论你的有趣思想。
* 补救的“吸取教训”问题：给你一个机会承认你文中一些可怕的错误，以便于评审人能在不用担心你会再犯错误的情况下“给你放行”。
* “给我一个理由让你通过”的问题：通常情况下，如果评审人不停地就同一话题发问，那是因为他们对此感兴趣，如果是这样，你就该积极合作，而不是试图改变话题。

所有这些都是非常有利的问题。如果你让评审人生气或者引起他们怀疑你的文章某处出了错，那样的话，你就会被问一些尖锐难答的问题。下一部分列出一些经典的的“杀手”问题并且提出有效回答这些问题的建议。

### “杀手”问题以及如何应付

在这一部分，Q=问题，A=建议的答案，C=我们对问题的评价以及答案。

Q：你的作品和吉姆的·布洛格斯（Jim Bloggs）最近写的文章有什么关系呢？（你从未听说过布洛格斯，怎么办？）

A：我对这篇文章不熟悉，他使用的是X方法还是Y方法呢？

C：说一些你知道的相关的东西，然后，当评审人说出一个大概的时候，你说的“啊，他和某某的作品很像吗？”

Q：这和布朗的研究不一样吗？

A：这和布朗的研究不同，因为……

C：每个人都担心有别人同时和他们做同样的研究，而且就在他们的研究完成前出版。忘掉这件事情，一个完全不同的方法、技术、样本等，会让你的工作与众不同并保护你的贡献。如果你已经知道布朗的研究，那么你应该分辨他的研究和你的有多大不同；如果你不知道布朗做了些什么，就问清楚布朗的研究是什么样，再做对比。

Q：你在第四章和第六章以两种不同的方式使用了X术语，是什么意思呢？

A：在第四章，我使用了史密斯的定义，对论文的那一部分，那是最合适的，在第六章，我使用了布朗的……

C：回答这个问题，提供简明的澄清。给你所写的作出注释，因为你或者被要求在修改时修正成带有清晰区分的文本。

Q：为什么你不……

A：因为……

C：这就是你需要重读你的论文并且进行一次模拟答辩的原因了。再读一次论文会让你回想起你做一件事情的方式（并且，告诉你为什么你没有使用其他选择）。如果“为什么你不……”后面提出的建议是你的领域内很少有人知道的，那么你可以沿着这样的线索回答：“那真有趣，听起来应该被这个领域内更多的人知道。”然后你就能把这个问题转向方法方面的讨论，然后就有机会让你谈论你知道的事情。

### 一些表达论文弱点的方式

有时候，你不得不承认你错了。偶尔，带着幽默感地承认是有效的。

遵循以下三点更安全：

1. 详细说明在设计阶段这一研究是一个合理的选择。
1. 尽可能简单地解释你知道研究它们为什么失败，不要带着歉意。
1. 想出一些可选项，以提高你下次成功的几率。

没人期待博士研究进展一帆风顺，没有错误或者没有障碍。实际上，任何研究都不可能是这个样子——研究充满了随机的风险和惊喜。评审人期待的就是学生对自己的错误和障碍做出充满智慧的反应，并且从中学到东西。

### 一般的答辩问题

由于众所周知的原因，我们没有对这些答案提出建议。你会发现在模拟答辩时让一个朋友问你这些问题是可靠且有用的，然后看看你是否能回答出来。这个朋友无需懂得你的答案。如果你能信心十足地迅速做出简明扼要的反应，那就没问题了。如果你不能，那么用一些时间来思考合适的答案。

* 你是怎么想到用这种方法来进行此项研究的？
* 什么是你研究的主要成果？
* 你的文章对这个领域作出了什么贡献？
* 这个领域内的主要理论组成部分是什么？核心思想是什么？谁是主要的贡献者？
* 这个领域内主要问题（争论问题或者有争议的问题）是什么？
* 在现存的理论和争论中，你的论文处在什么位置？主要的研究者对你的思想会做出什么样的反应？
* 你认为谁会对这篇文章最感兴趣？
* 已经发表的什么研究与你的工作最接近？你的工作的不同之处在哪里？
* 为什么你选择你使用的研究方法？
* 什么是你作出的关键研究决定？
* 如果你再一次做这项研究，你还会考虑使用别的研究方法吗？
* 你认为这项研究的下一步是什么？
* 什么是你的研究结果中最有趣的发现？
* 所有这些不都是显而易见的吗？
* 你对你的研究结果吃惊吗？（如果是，为什么是这样，是什么让你惊讶的？）
* 你对刚进入这个领域的学生有什么建议？
* 你有什么出版计划吗？
