# 学术会议

研究者们主要通过三种方式来获取他们研究领域内的最新进展。口头传递是一种迅速且有效的方式——如果史密斯和琼斯巳经解决了他们领域中最重要的问题，他们领域内的主要研究者们会在消息公布于众前的儿小时通过电话交谈和电子邮件传递这件事情。如果你是这个传递网络主要的参与者，这是非常好的事情，但是如果你只是一个正在努力奋斗的博士生，那么这种方式就不是那么好了。

对于大多数博士生而言，跟上潮流的一个更为可行的方式就是阅读期刊。不幸的是，期刊文章要在研究结束后两年左右才能刊出，因此，你的图书馆里新上架的期刊的文章大概都是三年前完成的研究内容。在学术会议上获得最新的研究进展则相对容易得多。每年，大多数研究领域都会开一些年会，来自世界各地的研究者们会聚在一起，展示他们的工作并且聆听别人阐述工作。更重要的，他们也开展社交并建立他们的社交网络，通常的方式包括去酒吧喝酒。因此，学术会议给你一个机会发现不超过一年甚至更近一段时间的研究，并且也给你机会结识世界各地的同领域研究者。

基本情况就是这些，但学术会议怎样才能把你需要知道的传达给你呢？我们会从这个部分开始，从一个完全新手的角度来解释，然后再转到那些组织者的角度来解释，最后给出一些建议，让你知道该怎样运用这些知识帮助你参加大多数学术会议。

## 学术会议过程：新手的视角

你能够参加的学术会议有两种内容。一种是介绍自己的工作，而另一种是不介绍自己的工作。我们接下来讨论的情况是你介绍自己的工作，当然这已经包括作为一名听众你需要做什么。

在一个学术会议上展示自己的研究进展有儿个主要途径。其中之一是你想公开发表一些东西，但概念没有完全成形，学术会议就是一个好地方。另一种情况：一开始就是为了免费游览会议所在地点而去的，这需要你把研究精力集中在你所向往的会议地点举办的会议的会议主题上。第三种情况：期待让一篇论文被一个特殊的会议选中，因为这是这个领域内的主要会议。巧合的是，会议通常在夏威夷之类的地方召开，并且他们对可以接纳的论文的标准又相对较低。

不管过程怎样，最后都需要适合那个会议的论文。征文通知将说明哪种类型的论文会被接受，会给每一种论文的类型提供指导原则，也会告知截止日期。征文主要类型通常包括一些或者以下的全部。

* 长论文（full papers）；
* 短论文（short papers）；
* 论文摘要；
* 海报（posters）。

有关摘要需注意的主要事情就是一旦你的摘要被接受，你需要依据摘要写一篇文章。你很容易忘记这件事，直到在会前两周才惊恐地想起你必须写这篇论文。另外，如果你希望你的文章被接收，你需要阐述你在摘要中表达的所有思想。关于海报你要忍受的主要事情是参会的大多数人会对你和你的海报视而不见；这不是什么个人问题，但是的确会感到很残忍。关于海报需要忍受的其他主要事情就是大多数提问的人会给你一种不舒服的眩晕感，因为他们提间是想要证明他们在这个领域内有更广博的知识，或者因为他们是一些古怪的人。再一次强调，这并非针对你个人。

所以，已经写完了论文把它寄出去之后，仔细考虑数日，然后把它湮没在日常工作中。某一天你会收到大会组委会关于你递交的论文的裁决并且需要做出决定。如果决议不利于你，那么你做的决定就涉及怎样处理此论文（或者把它送到别处，或者扔在一边）。如果有钱的话，还可以考虑是不是只单纯地作为观众去参加学术会议。如果结果是被录用，你需要做各种准备工作。如果你完全是一个新手，或者想看看什么是会议潜准则，那么你可能需要作出一项有趣的决定，即关于如何游说某个机构为你支付在夏威夷的希尔顿酒店的旅行费、会费以及接待费等等。如果你之前没有这么做过，而那些在你的学科内比你好很多的研究者仅仅能得到在斯凯格内斯（Skegness）两天的专题研讨会的费用资助的时候，那么他们会让你解释为什么为你付几于英镑去让你过一个愉快的假期。一个明智的导师会为你争取资助来支付年度学术会议的花费，但理智告诉他这项花费的范围通常不会扩大到某个有异国情调的地方举办的大型学术会议。

假定学术会议资助已经得到批准，你仍然需要安排旅行、食宿等事务。如果会议在西班牙或者会议语言为西班牙语，而你只会很有限的西班牙语，那就会很有压力。如果你是一个令人高兴且理性的人，你或者会发现一个说着流利的西班牙语的秘书或者研究助理会乐意为你提供帮助。如果你的为人不怎么样，那么获得帮助的可能性就会很小。

我们着装整齐地出发，去寻找旅馆和预订的地方，或许就在本地时间凌晨两点，你到达会议的举办地，你被旅途折腾得很累，还要一手拿着手提箱，另一只手拿大衣，并且还要腾出手来开门。接下来会发生什么？你遵循会议的指示，如果你的会议有几个说明，那么你就根据标记着“签到”的说明办手续。在签到的地方，你通常会得到一个参会证、会议进程表以及有关信息。从这时开始，你就不用为近日的日程安排伤脑筋。很有可能负责签到的人说从未听说过你，特别是你忘记了预定的时候，遇到这种情况你可以找一个好的理由或者找一个对会议熟悉的人一起去。这种问题通常会用某种方法得到解决，当然也有些事情是你无法解决的。

许多学术会议使用两个或者更多的会议大厅，以便能够同时进行两个或者多个演讲。在这种情况下，你只需要决定你参加哪一个分会场。你没有必要每天场场不落——除非你真的很想去。

现在，我们转移到组织者的角度，这会帮助你更清楚地了解学术会议过程的细节。

## 组织者的视角

人们为什么要组织学术会议？主要原因有三，即利益、荣誉和对学科的益处。一个好的学术会议会给有关的组织机构带来相当丰厚的利润。并且能够给学术组织者带来荣誉和权力（至少在学术圈子之中）。一个组织周密的学术会议是振兴一个走向没落的研究学科的最佳方式，也是开拓新的研究领域的方式。

因此，如果你想要开创一个新的研究领域，或者振兴已有的研究领域，你或许就需要组织学术会议。一个需要抓住的重要问题就是怎样吸引足够多的人来参加会议。一个标准的解决方案就是邀请一些重要的演讲者，他们的演讲会吸引其他人前来。如果有一个或者更多的著名演讲者的演讲既总结了这一领域的现有状态，又提出一些有趣的新思想，那么参会人数就不用担心了。一个好的开会地点会是另一个吸引参会者的要素。第三个吸引人的经典方式就是出版会议论文集，另外和某个期刊的编辑达成协议，把参会的最佳文章在这个期刊的特刊上发表。这会成为吸引部门基金资助会议的有利条件。如果多个研究者同一时段申请同样数鼠的基金用来召开学术会议，然而不可能都申请到基金，那么依据顺序可能得到基金的研究者如下：计划出版论文集和特刊的研究者作为第一选择，仅仅出版论文集的研究者作为第二选择，不出版论文集的研究者作为第三选择。

我们将略过后勤保障过程而将精力集中在有关的文章和论文集上。如果你正组织一个出版论文集的学术会议，那么你就需要与出版商取得联系，这能迅速提升参与者的兴趣。同时也需要提出限制有关字数长短、截稿日期等的内容的要求。出版商们有其工作的统一要求而不是为某客户定制规则。因此，如果你由于没有准备好论文副本，错过了一个出版时间，你就需要再找另外一家。这会让你花更多的钱。因此你要确保演讲者能够及时地提供正确版本。对于许多学术会议，论文集在大会之前就已经印好了，以便于代表们听演讲的同时有论文集可看。这就有确定的截稿日期，因此，作为一名组织茬你不会同情不能及时提交论文或者没有以正确的格式通过电子邮件提交的作者们。

在正常情况下讨论是按时段分批进行的这些时段为：大清早到早间咖啡时间；早间咖啡到午饭前；午饭到下午茶；下午茶到本日结束。每一组都会有各组织者中来协调，每一组通常会有一个综述性的介绍，或者由一位特邀嘉宾的演讲开始。这些讨论还可能超时，可能因为代表们在开会前还在拖拖拉拉以至于不得不推迟开始时间。也可能因为设备发生了问题，还有就是演讲者多说了三两分钟一对一个人来说不是一个大事，但是每个人都拖二三分钟，影响就扩大了口每场都会包括至少一位说话让人听不见、听不懂、枯燥乏味或者带了放不出来的幻灯片的演讲者。

作为一个参会者，这种情况显而易见对你有负面影响，但是让人惊讶的是没几个参会者会严肃对待这些事情。我们的建议是：

* 尽可能早地提交论文。
* 按给作者的要求做。
* 练习演讲以便你能在指定时间内保持会场秩序。
* 细致耐心，试着从组织者的角度来看事情。
* 如果你遇到问题，尽可能快地让主办方知道，以便事情能得到安排。

## 多方面的好建议

在你完成博士学业之前，你的第一次学术会议可能会是一次让你把一个完全幼稚的自我展示在一群你的领域的主要研究者面前的机会。不幸的是，对你而言那是一场不对称的力星对比。对于听众而言，你看起来不具有神奇的吸引力，最简单的原因就是你在你的职业舞台上可能还没有任何重要的新鲜和有趣的事情可说。你要尽量避免一些让你显得愚蠢的表现，这些表现如下：

* 在公开场合醉酒。
* 因为在私下场合醉酒，结果抱病不能参加会议。
* 由于相信没有人会知道或者认为不是什么大不了的事而和某人发生性关系——事实上，每个人在次日的茶歇时间都会知道，你的床上伴侣可能会让你犯可怕的错误。
* 问一些新参会的博士年年都会问的愚蠢的问题。

你的首次学术会议会是一个学会聆听的好机会。即便你确信你对某人谈论的某个问题已经有了精彩的解决方案，你也不要着急去发言或和演讲者争辩。如果你是对的，那么明天你也还是对的，学会耐心地听是一种难以估价的研究技能。

你的第一次学术会议是一个认识人并交朋友的好机会，这些友谊会延续到你的整个职业生涯。最好的方式就是在酒吧里和那些愿意和你谈话的人在一起进行一次严肃而且谦恭的对话。

如果你的第一次学术会议同时也是你第一次带着文章去陈述的会议那么你有压力，这很正常。一个减压的好方式就是在你去之前通过在公开场合演讲获得经验——例如，系里的讨论会，可以是一个很好的练习机会。你也可以举办一个非正式的讨论会，在会上陈述你的观点并收集反馈意见以改进你的陈述。另一种方式是和你的导师合著并且请你的导师作演讲，而且保证你自己下次一定自己去做演讲。你能学到导师的经验。牢记三条黄金法则：不要说谎；不要故作幽默；不要惊惶失措而在压力下吐露真相。你在说话时要谦逊有理，既不说太多也不说太少。你的使命不是娱乐或者迷惑听众——那是嘉宾演讲者该做的事情。你在第一次学术会议上的主要目的是积累经验，以便你知道你在第二次学术会议上将做什么。

## 如何最好地利用学术会议

### 参加不同规模学术会议的策略

* 小型：目标是全面了解（例如：和那里的每个人谈话）。
* 中等：致力于和尽可能多的人说话，但是主要目标是了解与自己相关的研究情况。
* 大型：做精心安排，保证能够和关键人物联系上，并关注主要事件。

带上你的名片并且在背面记录一些能帮助你的谈话对象回忆与你的谈话内容的信息。

### 在学术会议上建立联系

* 利用活动（研讨会、小组讨论、新人聚会等）。
* 陈述论文（这会把你介绍给你的听众中的每一个人）。
* 问好问题（其他人发现你的问题很有趣，或许向你介绍他们自己，人们会更容易记住你）。
* 如果你听到很有趣的对话，那么就站在周围可以让人看到的位置，直到你有机会参与谈话。一个短问题或者是一个玩笑都很好，或者直接问你是否可以参与这一话题的讨论。
* 让你的导师或者熟人介绍一些人给你认识。
* 同关键人物尽早接触。
* 同与你坐在一起的人说话。
* 养成习顷每天同不同的人在一起吃午餐。
* 当你在与别人对话的时候，避免滔滔不绝或者用你的观点来取悦别人，这时候问题往往比陈述要有效得多。

写好自己的简短介绍并记在心中。（例如简单说清楚你是谁，你在研究什么）。

### 如何保持联系

* 会议联系通常会有很高的“折旧率”，你应该尝试将会议上认识的人转变为长期联系。
* 永远履行你作出的承诺：真的寄送论文，或者用电子邮件发信息。
* 在与某人进行了很好的谈话后，发一封感谢邮件给他来保持联系。
* 建议访问或者进行友好的相互交流。
* 邀请好的联系人到你的机构，比如请联系人来做一次演讲。
* 如果在大会上你没有机会同演讲者交谈，那么会后可以通过邮件来进行交流。

### 做好你的家庭作业

当你收到会议相关资料后：

* 看一眼与会人员名单。谁在这个名单上，你最期持见到谁？他们提交了论文吗？
* 看一下会议分组和论文标题并计划你如何出席哪一组的讨论。哪一部分不应该错过？什么时候讨论开始？谁是你期待在会上取得联系的第一个人？
* 参加全体会议通常是个好主意。

每个晚上：

* 浏览或阅读你计划参加的小组论文。
* 看一看其他分会场的论文（你可能会在喝咖啡时遇到他们的作者）。
* 检查自己的次日计划。

带上你的会议论文集到会场：

* 查找文章并且加以分类。
* 给文章加注释：例如，如果作者在演讲期间增加了一些信息或者如果对你的文章有一些特别的联系。
* 列出要问的问题。
* 如果会议变得枯燥乏味没有意义，有事可作（例如，阅读其他文章）。

### 信息

你得到的东西和你的投入是息息相关的——如果在这个会上做工作，坚持不懈地寻求对话机会，抓住信息，那么你就能与许多人取得很好的联系。记住大多数会议的在“真实在”价值不在会场上——它来自于酒吧中的对话。如果你不喝酒，那么请记住，酒吧也提供无醇饮料。
