project:
  type: book
  output-dir: docs

book:
  title: 给研究生的学术建议
  subtitle: The Unwritten Rules of Ph.D. Research
  author:
    - （英）戈登·鲁格 玛丽安·彼得【著】
    - 彭万华【译】 彭凯平【校】
    - 张亮【编】
  date: now
  site-url: https://psychelzh.github.io/phdrule/
  repo-url: https://github.com/psychelzh/phdrule
  repo-branch: master
  repo-actions: issue
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - 11.qmd
    - 12.qmd
    - 13.qmd
    - 14.qmd
    - 15.qmd
    - 16.qmd
  appendices:
    - rules.qmd
    - glossary.qmd

# https://github.com/quarto-dev/quarto-cli/issues/2285
# https://github.com/quarto-dev/quarto-cli/issues/251
lang: zh

format:
  html:
    crossref:
      prp-title: 原因
    theme: cosmo
    code-link: true
    comments:
      hypothesis: true
  epub:
    toc: true
