# 有用的原则和建议 {-}

以下可能不包括那些我们认为是理所应当的重要建议，但这些建议是我们最喜欢的好建议：

1. 你75%的项目申请书、论文和工作申请都将会遭到拒绝，请做好心理准备。
:   如果你一直是是100%成功的话，这说明你的目标设定得太低。是75%的被拒绝率证明你的标准定得大致合理。（当然是75%这个比例并不能适用于所有的学科，但是其道理是通用的。）

1. 从目标出发。
:   如果从期望得到的结果出发，来安排你应该做的事情，那么你会更加有效地实现目标。如果你随机地跌跌撞撞，却希望收获一个目标，那么你很可能最终一无所获。

1. 如果一个聪明的人在一个问题上花了三年以上的时间，而仍没有找到解决办法，那么解决办法很可能是不存在的。
:   两到三年是许多学者从开始尝试到将结论成文再到在学术会议上陈述研究成果的一般时间跨度。如果三年后仍没有任何解决办法那么这样的办法很可能不存在。

1. 详细了解你的领域内所有的工具手段。
:   大部分研究者对于开展研究时需要的工具和手段了解得很详细，但这还不够。要知道你知道得越多，你就能够工作得越好。

1. 发自内心地善待他人。
:   真诚善待他人会让世界变得更加美好，而且你会获得长期的回报，因为人们会记住你，并且会帮助你更加顺利地做好每一件事情。

1. 与智慧的、能够给你提供帮助的人一起喝一杯咖啡是最有价值的投资。
:   在恰当的时候（通常是在开始做某事之前）向恰当的人咨询一下可以让你少走很多冤枉路。记住一定要向在相关领域很有发言权的人咨询，一个糊涂的同事或是对另一个领域比较了解的人，也许他们会给你鼓励，但是对于你的问题却不会有很大帮助。

1. 如果你有选择，一定要与你尊敬的很优秀的人一起工作。
:   你以这样的方式工作会有最大的收获，并且工作的过程也会很快乐。

1. 如果你不知道自己在干什么，马上停下来想清楚。
:   再来一杯咖啡在此刻是个不错的选择。

1. 用两种颜色的记号笔在你所写的重要文档（论文的前几页、求职信等）上作标记。
:   用一种颜色的笔标记那些聪明的外行说的话，用另一种颜色的笔标记那些一个聪明的外行说不出来的、只有深入了解这个领域的人才会说的话，还有那些有形的事实（例如参考文献和数据）或是成就，以及其他卓越的地方（例如更深层次的阅读、对你所应聘的单位所作的调查了解）等。将前者全部删除，并且做到后一种颜色的标记至少在每段中出现一次。

1. 记住，心灵是最重要的。
:   要有远见，生活本身比名和利都更加重要。

1. 三条黄金法则
:   * 第一条黄金法则：不要撒谎。
    * 第二条黄金法则：不要故作幽默。
    * 第三条黄金法则：不要惊慌失措而在压力下吐露真相。

# 一些有用的术语 {-}

标准化的术语在相应的教材中解释得十分详细，这部分我们将重点介绍那些非标准化但是却十分有用的术语，还有那些本应该广为人知的术语。另外，我们还将详细说明那些你们不是很确定但必须知道的术语。

Big name
:   在某个研究领域十分有声望的人，也可称为这“权威”（authority）。

Bounced
:   （投递到会议或者学刊的论文）被这“拒绝”这的委婉说法。

Buzzword
:   指时下非常流行的词汇，但往往与上下文无关联。如果你所工作的领域最近在媒体上很时髦（例如生物工艺和纳米技术），那么你在写文章的时候，要显示出你对这个领域了解得十分全面，切不可对这些词汇一知半解就随意使用。

Chair
:   教授职位。

Cup of coffee
:   与某人闲聊的一种说法。事实上闲聊也经常发生在喝咖啡的时候，高档写字楼都十分重视咖啡间，因为那是非正式信息交流的理想场所，包括告诉博士生们有关学术界的一些“小道消息”。

Eyeballing the data
:   浏览原始数据，这样做在分析数据的时候是十分有意义的。如果数据处理的结果和你浏览时的印象不一致，那么很可能在处理数据的过程中出现了错误。而错误是会经常发生的，所以浏览是个好习惯。

Funded research project
:   有资助的研究项目。如果研究项目需要资金，可以向多方申请。这些基金少则几百英镑，用于差旅或者设备费用；多则上百万英镑，来建立一个研究机构．此类项目普遍采用的形式是：聘用一位项目助理一到两年的时间，由他来管理这笔资金下的研究项目。这是大学资金的来源之一，也是研究项目中很重要的部分。

Good Thing
:   来源于《1066 and All That》这本书，是对流行事物的一种反讽说法，暗示其将很快被别的事物所取代。

Great Departmental Annual Report
:   大多数的系都会隔一段时间出一本关于教学或是研究的报告，通常不是由于自己想要这样做，而是上一级的部门（比如学院或者学校）要求的。这些报告常常是十分令人恼怒的，不仅是因为它经常要求你用一种非常不方便的形式来汇报信息，还因为它甚至需要任何一个你递交过论文的会议的具体时间，以及所有出版物的国际标准书号（ISBN）和国际标准连续出版物编号（ISSN）。如果你没有记录下这些信息，那么“The System”会不停地催你，直到你查清楚为止。所以应当吸取教训，把所有出版物的信息都简明完整地记录下来，至少也应该把所有的会议文件都存放在一个文件夹里，以备查找。

Harmless
:   一种略带贬义的评价。描述某物没有特别好或者不好的品质，它的平庸不会吸引任何注意，但也不会给世界带来什么损害。

Inaugural
:   新任教授向同事和邀请嘉宾作的一场演讲。

Journal
:   针对某一学科的学术期刊，与杂志（Magazine）有很多不同点：学刊的阅读对象是专家，而不是一般的读者，一般学刊上的文章都是学者写的，而不是记者；学刊比杂志更具有学术权威性，在优秀学刊上发表文章是学术成就的体现。

Named candidate
:   撰写项目基金说明书（为一项研究项目筹集资金）时，一些基金会会问你是否已经列好参与研究项目的人员名单。因为在通常情况下，找到合适的人选来进行某一专业领域的研究是很困难的，有大量的研究项目失败就是因为没有找到合适的人员来完成工作。在这里，候选人就是指被列在名单中来完成研究工作的人，明智的学者会平常留意物色这样的人选，例如某位深谙研究之道的博士生。

Periodical
:   一本定期发行的出版物，通常是一年出版几次。例如学刊或者杂志，和一次性出版的书籍不同。

PhD
:   拉丁文学“博土”（philosophiae doctor）的正式缩写。是普通高等大学所授予的最高学位，通常学生要完成一篇特定领域的论文，并且顺利通过论文答辩才能够获得此学位。

Professor
:   最高学术头衔（相对于行政），资深教授通常都获得了博士学位，但这并不是必需的。资深教授相当于一个传统部落中地位很高的老者，而如果在40岁以前就成为一名资深教授，那就是年轻有为的标志。

RAE
:   研究评估。在质量控制的名义下，教育主管部门会隔一段时间让学校报告其出版物数目和其他研究活动的情况。学校的研究做得越好，就可以从教育主管部门获得越多的拨款。然而怎样才算学“好”呢？精明的院系知道评估中学“好”的标准（通常是在顶尖学刊上发表论文的数量以及研究所带来的经济收人）。

Reader
:   普通教授的学术地位介于讲师和资深教授之间，其工作是专注于科研而不涉及行政管理。通常情况下，普通教授很快就可以升为资深教授。我们将“Reader”这个词的第一个字母大写以减少误解。

Reducing the problem space
:   将似是而非的可能性都剔除，以减少需要检测是否正确的可能性的数量。

Research assistant
:   受雇于某个基金资助项目从事一定研究工作的研究助理。大部分博士生毕业以后的头几年里都会作为博士后继续从事辅助的研究工作，这是一种积累经验的有效方式。曾经被人们以一种讽刺的口吻描绘为“研究步兵”（影射美国海军陆战队中那些最容易被忽视但却发挥巨大作用的基层士兵）。

Research community
:   任何的研究领域都有一定数置的研究人员；当这些领域被进一步细分成更易管理的子领域的时候，这个数鼠通常是十分小的。在各自的研究领域中，所有的学术权威和绝大多数的重要研究员都是互相认识的，至少熟悉彼此的名字和声誉，他们通常每年都会在学术会议上见面。对于大多数人来说，常规的学术道路就是找到一个自己感兴趣的，并且能在学术圈中建立一定学术声誉的研究领域。

Sanity check
:   一种非正规测试，用以确保某种论断或发现没有明显的谬误。适用于首次使用统计软件并有可能产生错误结果的情况，而且这种情况通常形式是正确的，但其实质却是完全错误的。

Significant
:   “显著性”这个词是有着特殊统计学含义的。如果那些没有意识到这一点的学生在日常生活中随意使用它，将会导致一系列的误解。

Significant absence
:   关键缺失。有些东西只有当它缺失的时候，你才能感受它的重要性。在一个歇洛克·福尔摩斯探案故事中，主要线索就是一只看门狗在罪犯进屋的时候没有发出吠声。这种吠声的缺失就是十分关键的，因为它显示狗是认识那个罪犯的。如果这只狗平时就是一种非常友好的动物，从来不对任何人吠叫，这也就不能构成一种“关键缺失”。学术界的关键缺失往往体现在有些现象和事件未引起重视也没有重要的针对这些现象和事件的研究成果发表。

The System
:   一种广泛流传于学生和导师之间的，关于学校的上级主管部门的一种讽刺性形象。

Tacit knowledge
:   隐性知识。总体讲是指那些常常不被明确提起的知识，或者是大家都习以为常的，或者是有关一些敏感话题。很多专业技术是包含大量隐性知识的，掌握这些隐性知识是攻读博士学位的一个重要组成部分。这些知识通常在博士生的课程和书本中是学不到的，而被留给导师来传授的。

There is a literature on that
:   这是一种略带贬义的评价，意思是，这个题目已经有很多人研究过了。显然，你没有很好地完成家庭作业，论题的挖掘也不够深入。你花费了大量的时间来重蹈前人的老路。

Viva
:   拉丁文“论文答辩”的缩写。通常是由答辩人自己导师以外的评审老师参加的现场问答，以考察你对所选题目相关知识的掌握程度。论文答辩是攻读博士的最后一关，有的时候也会用于硕士和本科生教育。在有些国家，答辩通常是向公众开放的，任何人只要有兴趣，都可以去学术报告厅旁听论文答辩。
